// Code generated by ent, DO NOT EDIT.

package supplierwithdrawal

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the supplierwithdrawal type in the database.
	Label = "supplier_withdrawal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSupplierID holds the string denoting the supplier_id field in the database.
	FieldSupplierID = "supplier_id"
	// FieldRequestNo holds the string denoting the request_no field in the database.
	FieldRequestNo = "request_no"
	// FieldAmountCny holds the string denoting the amount_cny field in the database.
	FieldAmountCny = "amount_cny"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldPayoutSnapshot holds the string denoting the payout_snapshot field in the database.
	FieldPayoutSnapshot = "payout_snapshot"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReviewedBy holds the string denoting the reviewed_by field in the database.
	FieldReviewedBy = "reviewed_by"
	// FieldReviewNote holds the string denoting the review_note field in the database.
	FieldReviewNote = "review_note"
	// FieldReviewedAt holds the string denoting the reviewed_at field in the database.
	FieldReviewedAt = "reviewed_at"
	// FieldPaymentProofKey holds the string denoting the payment_proof_key field in the database.
	FieldPaymentProofKey = "payment_proof_key"
	// FieldPaidAt holds the string denoting the paid_at field in the database.
	FieldPaidAt = "paid_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSupplier holds the string denoting the supplier edge name in mutations.
	EdgeSupplier = "supplier"
	// Table holds the table name of the supplierwithdrawal in the database.
	Table = "supplier_withdrawals"
	// SupplierTable is the table that holds the supplier relation/edge.
	SupplierTable = "supplier_withdrawals"
	// SupplierInverseTable is the table name for the Supplier entity.
	// It exists in this package in order to avoid circular dependency with the "supplier" package.
	SupplierInverseTable = "suppliers"
	// SupplierColumn is the table column denoting the supplier relation/edge.
	SupplierColumn = "supplier_id"
)

// Columns holds all SQL columns for supplierwithdrawal fields.
var Columns = []string{
	FieldID,
	FieldSupplierID,
	FieldRequestNo,
	FieldAmountCny,
	FieldMethod,
	FieldPayoutSnapshot,
	FieldStatus,
	FieldReviewedBy,
	FieldReviewNote,
	FieldReviewedAt,
	FieldPaymentProofKey,
	FieldPaidAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestNoValidator is a validator for the "request_no" field. It is called by the builders before save.
	RequestNoValidator func(string) error
	// DefaultReviewNote holds the default value on creation for the "review_note" field.
	DefaultReviewNote string
	// PaymentProofKeyValidator is a validator for the "payment_proof_key" field. It is called by the builders before save.
	PaymentProofKeyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Method defines the type for the "method" enum field.
type Method string

// Method values.
const (
	MethodAlipay Method = "alipay"
	MethodWechat Method = "wechat"
	MethodBank   Method = "bank"
)

func (m Method) String() string {
	return string(m)
}

// MethodValidator is a validator for the "method" field enum values. It is called by the builders before save.
func MethodValidator(m Method) error {
	switch m {
	case MethodAlipay, MethodWechat, MethodBank:
		return nil
	default:
		return fmt.Errorf("supplierwithdrawal: invalid enum value for method field: %q", m)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending  Status = "pending"
	StatusApproved Status = "approved"
	StatusRejected Status = "rejected"
	StatusPaid     Status = "paid"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusApproved, StatusRejected, StatusPaid:
		return nil
	default:
		return fmt.Errorf("supplierwithdrawal: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the SupplierWithdrawal queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySupplierID orders the results by the supplier_id field.
func BySupplierID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupplierID, opts...).ToFunc()
}

// ByRequestNo orders the results by the request_no field.
func ByRequestNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestNo, opts...).ToFunc()
}

// ByAmountCny orders the results by the amount_cny field.
func ByAmountCny(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCny, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReviewedBy orders the results by the reviewed_by field.
func ByReviewedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedBy, opts...).ToFunc()
}

// ByReviewNote orders the results by the review_note field.
func ByReviewNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewNote, opts...).ToFunc()
}

// ByReviewedAt orders the results by the reviewed_at field.
func ByReviewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedAt, opts...).ToFunc()
}

// ByPaymentProofKey orders the results by the payment_proof_key field.
func ByPaymentProofKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentProofKey, opts...).ToFunc()
}

// ByPaidAt orders the results by the paid_at field.
func ByPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySupplierField orders the results by supplier field.
func BySupplierField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSupplierStep(), sql.OrderByField(field, opts...))
	}
}
func newSupplierStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SupplierInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SupplierTable, SupplierColumn),
	)
}
