// Code generated by ent, DO NOT EDIT.

package supplierledger

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the supplierledger type in the database.
	Label = "supplier_ledger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSupplierID holds the string denoting the supplier_id field in the database.
	FieldSupplierID = "supplier_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldReversalOfID holds the string denoting the reversal_of_id field in the database.
	FieldReversalOfID = "reversal_of_id"
	// FieldEventKey holds the string denoting the event_key field in the database.
	FieldEventKey = "event_key"
	// FieldEntryType holds the string denoting the entry_type field in the database.
	FieldEntryType = "entry_type"
	// FieldBucket holds the string denoting the bucket field in the database.
	FieldBucket = "bucket"
	// FieldBaseRate holds the string denoting the base_rate field in the database.
	FieldBaseRate = "base_rate"
	// FieldAdminAdjustment holds the string denoting the admin_adjustment field in the database.
	FieldAdminAdjustment = "admin_adjustment"
	// FieldEffectiveRate holds the string denoting the effective_rate field in the database.
	FieldEffectiveRate = "effective_rate"
	// FieldModelCostUsd holds the string denoting the model_cost_usd field in the database.
	FieldModelCostUsd = "model_cost_usd"
	// FieldRechargeRatio holds the string denoting the recharge_ratio field in the database.
	FieldRechargeRatio = "recharge_ratio"
	// FieldEarningUsd holds the string denoting the earning_usd field in the database.
	FieldEarningUsd = "earning_usd"
	// FieldAmountCny holds the string denoting the amount_cny field in the database.
	FieldAmountCny = "amount_cny"
	// FieldAvailableAt holds the string denoting the available_at field in the database.
	FieldAvailableAt = "available_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSupplier holds the string denoting the supplier edge name in mutations.
	EdgeSupplier = "supplier"
	// Table holds the table name of the supplierledger in the database.
	Table = "supplier_ledgers"
	// SupplierTable is the table that holds the supplier relation/edge.
	SupplierTable = "supplier_ledgers"
	// SupplierInverseTable is the table name for the Supplier entity.
	// It exists in this package in order to avoid circular dependency with the "supplier" package.
	SupplierInverseTable = "suppliers"
	// SupplierColumn is the table column denoting the supplier relation/edge.
	SupplierColumn = "supplier_id"
)

// Columns holds all SQL columns for supplierledger fields.
var Columns = []string{
	FieldID,
	FieldSupplierID,
	FieldGroupID,
	FieldUsageLogID,
	FieldReversalOfID,
	FieldEventKey,
	FieldEntryType,
	FieldBucket,
	FieldBaseRate,
	FieldAdminAdjustment,
	FieldEffectiveRate,
	FieldModelCostUsd,
	FieldRechargeRatio,
	FieldEarningUsd,
	FieldAmountCny,
	FieldAvailableAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventKeyValidator is a validator for the "event_key" field. It is called by the builders before save.
	EventKeyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// EntryType defines the type for the "entry_type" enum field.
type EntryType string

// EntryType values.
const (
	EntryTypeEarning          EntryType = "earning"
	EntryTypeReversal         EntryType = "reversal"
	EntryTypeRelease          EntryType = "release"
	EntryTypeWithdrawal       EntryType = "withdrawal"
	EntryTypeWithdrawalRefund EntryType = "withdrawal_refund"
)

func (et EntryType) String() string {
	return string(et)
}

// EntryTypeValidator is a validator for the "entry_type" field enum values. It is called by the builders before save.
func EntryTypeValidator(et EntryType) error {
	switch et {
	case EntryTypeEarning, EntryTypeReversal, EntryTypeRelease, EntryTypeWithdrawal, EntryTypeWithdrawalRefund:
		return nil
	default:
		return fmt.Errorf("supplierledger: invalid enum value for entry_type field: %q", et)
	}
}

// Bucket defines the type for the "bucket" enum field.
type Bucket string

// Bucket values.
const (
	BucketPending   Bucket = "pending"
	BucketAvailable Bucket = "available"
	BucketFrozen    Bucket = "frozen"
)

func (b Bucket) String() string {
	return string(b)
}

// BucketValidator is a validator for the "bucket" field enum values. It is called by the builders before save.
func BucketValidator(b Bucket) error {
	switch b {
	case BucketPending, BucketAvailable, BucketFrozen:
		return nil
	default:
		return fmt.Errorf("supplierledger: invalid enum value for bucket field: %q", b)
	}
}

// OrderOption defines the ordering options for the SupplierLedger queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySupplierID orders the results by the supplier_id field.
func BySupplierID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupplierID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByReversalOfID orders the results by the reversal_of_id field.
func ByReversalOfID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReversalOfID, opts...).ToFunc()
}

// ByEventKey orders the results by the event_key field.
func ByEventKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventKey, opts...).ToFunc()
}

// ByEntryType orders the results by the entry_type field.
func ByEntryType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryType, opts...).ToFunc()
}

// ByBucket orders the results by the bucket field.
func ByBucket(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucket, opts...).ToFunc()
}

// ByBaseRate orders the results by the base_rate field.
func ByBaseRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseRate, opts...).ToFunc()
}

// ByAdminAdjustment orders the results by the admin_adjustment field.
func ByAdminAdjustment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminAdjustment, opts...).ToFunc()
}

// ByEffectiveRate orders the results by the effective_rate field.
func ByEffectiveRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveRate, opts...).ToFunc()
}

// ByModelCostUsd orders the results by the model_cost_usd field.
func ByModelCostUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelCostUsd, opts...).ToFunc()
}

// ByRechargeRatio orders the results by the recharge_ratio field.
func ByRechargeRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRechargeRatio, opts...).ToFunc()
}

// ByEarningUsd orders the results by the earning_usd field.
func ByEarningUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEarningUsd, opts...).ToFunc()
}

// ByAmountCny orders the results by the amount_cny field.
func ByAmountCny(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCny, opts...).ToFunc()
}

// ByAvailableAt orders the results by the available_at field.
func ByAvailableAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySupplierField orders the results by supplier field.
func BySupplierField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSupplierStep(), sql.OrderByField(field, opts...))
	}
}
func newSupplierStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SupplierInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SupplierTable, SupplierColumn),
	)
}
