// Code generated by ent, DO NOT EDIT.

package supplierledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldID, id))
}

// SupplierID applies equality check predicate on the "supplier_id" field. It's identical to SupplierIDEQ.
func SupplierID(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldSupplierID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldGroupID, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldUsageLogID, v))
}

// ReversalOfID applies equality check predicate on the "reversal_of_id" field. It's identical to ReversalOfIDEQ.
func ReversalOfID(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldReversalOfID, v))
}

// EventKey applies equality check predicate on the "event_key" field. It's identical to EventKeyEQ.
func EventKey(v string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldEventKey, v))
}

// BaseRate applies equality check predicate on the "base_rate" field. It's identical to BaseRateEQ.
func BaseRate(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldBaseRate, v))
}

// AdminAdjustment applies equality check predicate on the "admin_adjustment" field. It's identical to AdminAdjustmentEQ.
func AdminAdjustment(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldAdminAdjustment, v))
}

// EffectiveRate applies equality check predicate on the "effective_rate" field. It's identical to EffectiveRateEQ.
func EffectiveRate(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldEffectiveRate, v))
}

// ModelCostUsd applies equality check predicate on the "model_cost_usd" field. It's identical to ModelCostUsdEQ.
func ModelCostUsd(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldModelCostUsd, v))
}

// RechargeRatio applies equality check predicate on the "recharge_ratio" field. It's identical to RechargeRatioEQ.
func RechargeRatio(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldRechargeRatio, v))
}

// EarningUsd applies equality check predicate on the "earning_usd" field. It's identical to EarningUsdEQ.
func EarningUsd(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldEarningUsd, v))
}

// AmountCny applies equality check predicate on the "amount_cny" field. It's identical to AmountCnyEQ.
func AmountCny(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldAmountCny, v))
}

// AvailableAt applies equality check predicate on the "available_at" field. It's identical to AvailableAtEQ.
func AvailableAt(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldAvailableAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// SupplierIDEQ applies the EQ predicate on the "supplier_id" field.
func SupplierIDEQ(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldSupplierID, v))
}

// SupplierIDNEQ applies the NEQ predicate on the "supplier_id" field.
func SupplierIDNEQ(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldSupplierID, v))
}

// SupplierIDIn applies the In predicate on the "supplier_id" field.
func SupplierIDIn(vs ...int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldSupplierID, vs...))
}

// SupplierIDNotIn applies the NotIn predicate on the "supplier_id" field.
func SupplierIDNotIn(vs ...int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldSupplierID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldGroupID, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldUsageLogID, v))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotNull(FieldUsageLogID))
}

// ReversalOfIDEQ applies the EQ predicate on the "reversal_of_id" field.
func ReversalOfIDEQ(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldReversalOfID, v))
}

// ReversalOfIDNEQ applies the NEQ predicate on the "reversal_of_id" field.
func ReversalOfIDNEQ(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldReversalOfID, v))
}

// ReversalOfIDIn applies the In predicate on the "reversal_of_id" field.
func ReversalOfIDIn(vs ...int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldReversalOfID, vs...))
}

// ReversalOfIDNotIn applies the NotIn predicate on the "reversal_of_id" field.
func ReversalOfIDNotIn(vs ...int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldReversalOfID, vs...))
}

// ReversalOfIDGT applies the GT predicate on the "reversal_of_id" field.
func ReversalOfIDGT(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldReversalOfID, v))
}

// ReversalOfIDGTE applies the GTE predicate on the "reversal_of_id" field.
func ReversalOfIDGTE(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldReversalOfID, v))
}

// ReversalOfIDLT applies the LT predicate on the "reversal_of_id" field.
func ReversalOfIDLT(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldReversalOfID, v))
}

// ReversalOfIDLTE applies the LTE predicate on the "reversal_of_id" field.
func ReversalOfIDLTE(v int64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldReversalOfID, v))
}

// ReversalOfIDIsNil applies the IsNil predicate on the "reversal_of_id" field.
func ReversalOfIDIsNil() predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIsNull(FieldReversalOfID))
}

// ReversalOfIDNotNil applies the NotNil predicate on the "reversal_of_id" field.
func ReversalOfIDNotNil() predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotNull(FieldReversalOfID))
}

// EventKeyEQ applies the EQ predicate on the "event_key" field.
func EventKeyEQ(v string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldEventKey, v))
}

// EventKeyNEQ applies the NEQ predicate on the "event_key" field.
func EventKeyNEQ(v string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldEventKey, v))
}

// EventKeyIn applies the In predicate on the "event_key" field.
func EventKeyIn(vs ...string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldEventKey, vs...))
}

// EventKeyNotIn applies the NotIn predicate on the "event_key" field.
func EventKeyNotIn(vs ...string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldEventKey, vs...))
}

// EventKeyGT applies the GT predicate on the "event_key" field.
func EventKeyGT(v string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldEventKey, v))
}

// EventKeyGTE applies the GTE predicate on the "event_key" field.
func EventKeyGTE(v string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldEventKey, v))
}

// EventKeyLT applies the LT predicate on the "event_key" field.
func EventKeyLT(v string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldEventKey, v))
}

// EventKeyLTE applies the LTE predicate on the "event_key" field.
func EventKeyLTE(v string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldEventKey, v))
}

// EventKeyContains applies the Contains predicate on the "event_key" field.
func EventKeyContains(v string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldContains(FieldEventKey, v))
}

// EventKeyHasPrefix applies the HasPrefix predicate on the "event_key" field.
func EventKeyHasPrefix(v string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldHasPrefix(FieldEventKey, v))
}

// EventKeyHasSuffix applies the HasSuffix predicate on the "event_key" field.
func EventKeyHasSuffix(v string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldHasSuffix(FieldEventKey, v))
}

// EventKeyEqualFold applies the EqualFold predicate on the "event_key" field.
func EventKeyEqualFold(v string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEqualFold(FieldEventKey, v))
}

// EventKeyContainsFold applies the ContainsFold predicate on the "event_key" field.
func EventKeyContainsFold(v string) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldContainsFold(FieldEventKey, v))
}

// EntryTypeEQ applies the EQ predicate on the "entry_type" field.
func EntryTypeEQ(v EntryType) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldEntryType, v))
}

// EntryTypeNEQ applies the NEQ predicate on the "entry_type" field.
func EntryTypeNEQ(v EntryType) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldEntryType, v))
}

// EntryTypeIn applies the In predicate on the "entry_type" field.
func EntryTypeIn(vs ...EntryType) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldEntryType, vs...))
}

// EntryTypeNotIn applies the NotIn predicate on the "entry_type" field.
func EntryTypeNotIn(vs ...EntryType) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldEntryType, vs...))
}

// BucketEQ applies the EQ predicate on the "bucket" field.
func BucketEQ(v Bucket) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldBucket, v))
}

// BucketNEQ applies the NEQ predicate on the "bucket" field.
func BucketNEQ(v Bucket) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldBucket, v))
}

// BucketIn applies the In predicate on the "bucket" field.
func BucketIn(vs ...Bucket) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldBucket, vs...))
}

// BucketNotIn applies the NotIn predicate on the "bucket" field.
func BucketNotIn(vs ...Bucket) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldBucket, vs...))
}

// BaseRateEQ applies the EQ predicate on the "base_rate" field.
func BaseRateEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldBaseRate, v))
}

// BaseRateNEQ applies the NEQ predicate on the "base_rate" field.
func BaseRateNEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldBaseRate, v))
}

// BaseRateIn applies the In predicate on the "base_rate" field.
func BaseRateIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldBaseRate, vs...))
}

// BaseRateNotIn applies the NotIn predicate on the "base_rate" field.
func BaseRateNotIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldBaseRate, vs...))
}

// BaseRateGT applies the GT predicate on the "base_rate" field.
func BaseRateGT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldBaseRate, v))
}

// BaseRateGTE applies the GTE predicate on the "base_rate" field.
func BaseRateGTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldBaseRate, v))
}

// BaseRateLT applies the LT predicate on the "base_rate" field.
func BaseRateLT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldBaseRate, v))
}

// BaseRateLTE applies the LTE predicate on the "base_rate" field.
func BaseRateLTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldBaseRate, v))
}

// AdminAdjustmentEQ applies the EQ predicate on the "admin_adjustment" field.
func AdminAdjustmentEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldAdminAdjustment, v))
}

// AdminAdjustmentNEQ applies the NEQ predicate on the "admin_adjustment" field.
func AdminAdjustmentNEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldAdminAdjustment, v))
}

// AdminAdjustmentIn applies the In predicate on the "admin_adjustment" field.
func AdminAdjustmentIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldAdminAdjustment, vs...))
}

// AdminAdjustmentNotIn applies the NotIn predicate on the "admin_adjustment" field.
func AdminAdjustmentNotIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldAdminAdjustment, vs...))
}

// AdminAdjustmentGT applies the GT predicate on the "admin_adjustment" field.
func AdminAdjustmentGT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldAdminAdjustment, v))
}

// AdminAdjustmentGTE applies the GTE predicate on the "admin_adjustment" field.
func AdminAdjustmentGTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldAdminAdjustment, v))
}

// AdminAdjustmentLT applies the LT predicate on the "admin_adjustment" field.
func AdminAdjustmentLT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldAdminAdjustment, v))
}

// AdminAdjustmentLTE applies the LTE predicate on the "admin_adjustment" field.
func AdminAdjustmentLTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldAdminAdjustment, v))
}

// EffectiveRateEQ applies the EQ predicate on the "effective_rate" field.
func EffectiveRateEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldEffectiveRate, v))
}

// EffectiveRateNEQ applies the NEQ predicate on the "effective_rate" field.
func EffectiveRateNEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldEffectiveRate, v))
}

// EffectiveRateIn applies the In predicate on the "effective_rate" field.
func EffectiveRateIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldEffectiveRate, vs...))
}

// EffectiveRateNotIn applies the NotIn predicate on the "effective_rate" field.
func EffectiveRateNotIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldEffectiveRate, vs...))
}

// EffectiveRateGT applies the GT predicate on the "effective_rate" field.
func EffectiveRateGT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldEffectiveRate, v))
}

// EffectiveRateGTE applies the GTE predicate on the "effective_rate" field.
func EffectiveRateGTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldEffectiveRate, v))
}

// EffectiveRateLT applies the LT predicate on the "effective_rate" field.
func EffectiveRateLT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldEffectiveRate, v))
}

// EffectiveRateLTE applies the LTE predicate on the "effective_rate" field.
func EffectiveRateLTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldEffectiveRate, v))
}

// ModelCostUsdEQ applies the EQ predicate on the "model_cost_usd" field.
func ModelCostUsdEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldModelCostUsd, v))
}

// ModelCostUsdNEQ applies the NEQ predicate on the "model_cost_usd" field.
func ModelCostUsdNEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldModelCostUsd, v))
}

// ModelCostUsdIn applies the In predicate on the "model_cost_usd" field.
func ModelCostUsdIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldModelCostUsd, vs...))
}

// ModelCostUsdNotIn applies the NotIn predicate on the "model_cost_usd" field.
func ModelCostUsdNotIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldModelCostUsd, vs...))
}

// ModelCostUsdGT applies the GT predicate on the "model_cost_usd" field.
func ModelCostUsdGT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldModelCostUsd, v))
}

// ModelCostUsdGTE applies the GTE predicate on the "model_cost_usd" field.
func ModelCostUsdGTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldModelCostUsd, v))
}

// ModelCostUsdLT applies the LT predicate on the "model_cost_usd" field.
func ModelCostUsdLT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldModelCostUsd, v))
}

// ModelCostUsdLTE applies the LTE predicate on the "model_cost_usd" field.
func ModelCostUsdLTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldModelCostUsd, v))
}

// RechargeRatioEQ applies the EQ predicate on the "recharge_ratio" field.
func RechargeRatioEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldRechargeRatio, v))
}

// RechargeRatioNEQ applies the NEQ predicate on the "recharge_ratio" field.
func RechargeRatioNEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldRechargeRatio, v))
}

// RechargeRatioIn applies the In predicate on the "recharge_ratio" field.
func RechargeRatioIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldRechargeRatio, vs...))
}

// RechargeRatioNotIn applies the NotIn predicate on the "recharge_ratio" field.
func RechargeRatioNotIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldRechargeRatio, vs...))
}

// RechargeRatioGT applies the GT predicate on the "recharge_ratio" field.
func RechargeRatioGT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldRechargeRatio, v))
}

// RechargeRatioGTE applies the GTE predicate on the "recharge_ratio" field.
func RechargeRatioGTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldRechargeRatio, v))
}

// RechargeRatioLT applies the LT predicate on the "recharge_ratio" field.
func RechargeRatioLT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldRechargeRatio, v))
}

// RechargeRatioLTE applies the LTE predicate on the "recharge_ratio" field.
func RechargeRatioLTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldRechargeRatio, v))
}

// EarningUsdEQ applies the EQ predicate on the "earning_usd" field.
func EarningUsdEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldEarningUsd, v))
}

// EarningUsdNEQ applies the NEQ predicate on the "earning_usd" field.
func EarningUsdNEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldEarningUsd, v))
}

// EarningUsdIn applies the In predicate on the "earning_usd" field.
func EarningUsdIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldEarningUsd, vs...))
}

// EarningUsdNotIn applies the NotIn predicate on the "earning_usd" field.
func EarningUsdNotIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldEarningUsd, vs...))
}

// EarningUsdGT applies the GT predicate on the "earning_usd" field.
func EarningUsdGT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldEarningUsd, v))
}

// EarningUsdGTE applies the GTE predicate on the "earning_usd" field.
func EarningUsdGTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldEarningUsd, v))
}

// EarningUsdLT applies the LT predicate on the "earning_usd" field.
func EarningUsdLT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldEarningUsd, v))
}

// EarningUsdLTE applies the LTE predicate on the "earning_usd" field.
func EarningUsdLTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldEarningUsd, v))
}

// AmountCnyEQ applies the EQ predicate on the "amount_cny" field.
func AmountCnyEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldAmountCny, v))
}

// AmountCnyNEQ applies the NEQ predicate on the "amount_cny" field.
func AmountCnyNEQ(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldAmountCny, v))
}

// AmountCnyIn applies the In predicate on the "amount_cny" field.
func AmountCnyIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldAmountCny, vs...))
}

// AmountCnyNotIn applies the NotIn predicate on the "amount_cny" field.
func AmountCnyNotIn(vs ...float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldAmountCny, vs...))
}

// AmountCnyGT applies the GT predicate on the "amount_cny" field.
func AmountCnyGT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldAmountCny, v))
}

// AmountCnyGTE applies the GTE predicate on the "amount_cny" field.
func AmountCnyGTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldAmountCny, v))
}

// AmountCnyLT applies the LT predicate on the "amount_cny" field.
func AmountCnyLT(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldAmountCny, v))
}

// AmountCnyLTE applies the LTE predicate on the "amount_cny" field.
func AmountCnyLTE(v float64) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldAmountCny, v))
}

// AvailableAtEQ applies the EQ predicate on the "available_at" field.
func AvailableAtEQ(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldAvailableAt, v))
}

// AvailableAtNEQ applies the NEQ predicate on the "available_at" field.
func AvailableAtNEQ(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldAvailableAt, v))
}

// AvailableAtIn applies the In predicate on the "available_at" field.
func AvailableAtIn(vs ...time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldAvailableAt, vs...))
}

// AvailableAtNotIn applies the NotIn predicate on the "available_at" field.
func AvailableAtNotIn(vs ...time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldAvailableAt, vs...))
}

// AvailableAtGT applies the GT predicate on the "available_at" field.
func AvailableAtGT(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldAvailableAt, v))
}

// AvailableAtGTE applies the GTE predicate on the "available_at" field.
func AvailableAtGTE(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldAvailableAt, v))
}

// AvailableAtLT applies the LT predicate on the "available_at" field.
func AvailableAtLT(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldAvailableAt, v))
}

// AvailableAtLTE applies the LTE predicate on the "available_at" field.
func AvailableAtLTE(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldAvailableAt, v))
}

// AvailableAtIsNil applies the IsNil predicate on the "available_at" field.
func AvailableAtIsNil() predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIsNull(FieldAvailableAt))
}

// AvailableAtNotNil applies the NotNil predicate on the "available_at" field.
func AvailableAtNotNil() predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotNull(FieldAvailableAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSupplier applies the HasEdge predicate on the "supplier" edge.
func HasSupplier() predicate.SupplierLedger {
	return predicate.SupplierLedger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SupplierTable, SupplierColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSupplierWith applies the HasEdge predicate on the "supplier" edge with a given conditions (other predicates).
func HasSupplierWith(preds ...predicate.Supplier) predicate.SupplierLedger {
	return predicate.SupplierLedger(func(s *sql.Selector) {
		step := newSupplierStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupplierLedger) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupplierLedger) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupplierLedger) predicate.SupplierLedger {
	return predicate.SupplierLedger(sql.NotPredicates(p))
}
