// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/supplier"
	"github.com/Wei-Shaw/sub2api/ent/supplierdocument"
)

// SupplierDocument is the model entity for the SupplierDocument schema.
type SupplierDocument struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SupplierID holds the value of the "supplier_id" field.
	SupplierID int64 `json:"supplier_id,omitempty"`
	// StorageKey holds the value of the "storage_key" field.
	StorageKey string `json:"storage_key,omitempty"`
	// OriginalName holds the value of the "original_name" field.
	OriginalName string `json:"original_name,omitempty"`
	// ContentType holds the value of the "content_type" field.
	ContentType string `json:"content_type,omitempty"`
	// SizeBytes holds the value of the "size_bytes" field.
	SizeBytes int64 `json:"size_bytes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupplierDocumentQuery when eager-loading is set.
	Edges        SupplierDocumentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SupplierDocumentEdges holds the relations/edges for other nodes in the graph.
type SupplierDocumentEdges struct {
	// Supplier holds the value of the supplier edge.
	Supplier *Supplier `json:"supplier,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SupplierOrErr returns the Supplier value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupplierDocumentEdges) SupplierOrErr() (*Supplier, error) {
	if e.Supplier != nil {
		return e.Supplier, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: supplier.Label}
	}
	return nil, &NotLoadedError{edge: "supplier"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupplierDocument) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supplierdocument.FieldID, supplierdocument.FieldSupplierID, supplierdocument.FieldSizeBytes:
			values[i] = new(sql.NullInt64)
		case supplierdocument.FieldStorageKey, supplierdocument.FieldOriginalName, supplierdocument.FieldContentType:
			values[i] = new(sql.NullString)
		case supplierdocument.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupplierDocument fields.
func (_m *SupplierDocument) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supplierdocument.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case supplierdocument.FieldSupplierID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_id", values[i])
			} else if value.Valid {
				_m.SupplierID = value.Int64
			}
		case supplierdocument.FieldStorageKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_key", values[i])
			} else if value.Valid {
				_m.StorageKey = value.String
			}
		case supplierdocument.FieldOriginalName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_name", values[i])
			} else if value.Valid {
				_m.OriginalName = value.String
			}
		case supplierdocument.FieldContentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_type", values[i])
			} else if value.Valid {
				_m.ContentType = value.String
			}
		case supplierdocument.FieldSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size_bytes", values[i])
			} else if value.Valid {
				_m.SizeBytes = value.Int64
			}
		case supplierdocument.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupplierDocument.
// This includes values selected through modifiers, order, etc.
func (_m *SupplierDocument) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySupplier queries the "supplier" edge of the SupplierDocument entity.
func (_m *SupplierDocument) QuerySupplier() *SupplierQuery {
	return NewSupplierDocumentClient(_m.config).QuerySupplier(_m)
}

// Update returns a builder for updating this SupplierDocument.
// Note that you need to call SupplierDocument.Unwrap() before calling this method if this SupplierDocument
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupplierDocument) Update() *SupplierDocumentUpdateOne {
	return NewSupplierDocumentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupplierDocument entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupplierDocument) Unwrap() *SupplierDocument {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupplierDocument is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupplierDocument) String() string {
	var builder strings.Builder
	builder.WriteString("SupplierDocument(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("supplier_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupplierID))
	builder.WriteString(", ")
	builder.WriteString("storage_key=")
	builder.WriteString(_m.StorageKey)
	builder.WriteString(", ")
	builder.WriteString("original_name=")
	builder.WriteString(_m.OriginalName)
	builder.WriteString(", ")
	builder.WriteString("content_type=")
	builder.WriteString(_m.ContentType)
	builder.WriteString(", ")
	builder.WriteString("size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SizeBytes))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupplierDocuments is a parsable slice of SupplierDocument.
type SupplierDocuments []*SupplierDocument
