// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/supplier"
	"github.com/Wei-Shaw/sub2api/ent/supplierresourcerequest"
)

// SupplierResourceRequestCreate is the builder for creating a SupplierResourceRequest entity.
type SupplierResourceRequestCreate struct {
	config
	mutation *SupplierResourceRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSupplierID sets the "supplier_id" field.
func (_c *SupplierResourceRequestCreate) SetSupplierID(v int64) *SupplierResourceRequestCreate {
	_c.mutation.SetSupplierID(v)
	return _c
}

// SetGroupName sets the "group_name" field.
func (_c *SupplierResourceRequestCreate) SetGroupName(v string) *SupplierResourceRequestCreate {
	_c.mutation.SetGroupName(v)
	return _c
}

// SetRelayName sets the "relay_name" field.
func (_c *SupplierResourceRequestCreate) SetRelayName(v string) *SupplierResourceRequestCreate {
	_c.mutation.SetRelayName(v)
	return _c
}

// SetRelayURL sets the "relay_url" field.
func (_c *SupplierResourceRequestCreate) SetRelayURL(v string) *SupplierResourceRequestCreate {
	_c.mutation.SetRelayURL(v)
	return _c
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (_c *SupplierResourceRequestCreate) SetAPIKeyEncrypted(v string) *SupplierResourceRequestCreate {
	_c.mutation.SetAPIKeyEncrypted(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *SupplierResourceRequestCreate) SetModel(v string) *SupplierResourceRequestCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *SupplierResourceRequestCreate) SetNillableModel(v *string) *SupplierResourceRequestCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetSupportedModels sets the "supported_models" field.
func (_c *SupplierResourceRequestCreate) SetSupportedModels(v []string) *SupplierResourceRequestCreate {
	_c.mutation.SetSupportedModels(v)
	return _c
}

// SetProbeEnabled sets the "probe_enabled" field.
func (_c *SupplierResourceRequestCreate) SetProbeEnabled(v bool) *SupplierResourceRequestCreate {
	_c.mutation.SetProbeEnabled(v)
	return _c
}

// SetNillableProbeEnabled sets the "probe_enabled" field if the given value is not nil.
func (_c *SupplierResourceRequestCreate) SetNillableProbeEnabled(v *bool) *SupplierResourceRequestCreate {
	if v != nil {
		_c.SetProbeEnabled(*v)
	}
	return _c
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_c *SupplierResourceRequestCreate) SetRateMultiplier(v float64) *SupplierResourceRequestCreate {
	_c.mutation.SetRateMultiplier(v)
	return _c
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_c *SupplierResourceRequestCreate) SetNillableRateMultiplier(v *float64) *SupplierResourceRequestCreate {
	if v != nil {
		_c.SetRateMultiplier(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SupplierResourceRequestCreate) SetStatus(v supplierresourcerequest.Status) *SupplierResourceRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SupplierResourceRequestCreate) SetNillableStatus(v *supplierresourcerequest.Status) *SupplierResourceRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReviewedBy sets the "reviewed_by" field.
func (_c *SupplierResourceRequestCreate) SetReviewedBy(v int64) *SupplierResourceRequestCreate {
	_c.mutation.SetReviewedBy(v)
	return _c
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_c *SupplierResourceRequestCreate) SetNillableReviewedBy(v *int64) *SupplierResourceRequestCreate {
	if v != nil {
		_c.SetReviewedBy(*v)
	}
	return _c
}

// SetReviewNote sets the "review_note" field.
func (_c *SupplierResourceRequestCreate) SetReviewNote(v string) *SupplierResourceRequestCreate {
	_c.mutation.SetReviewNote(v)
	return _c
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_c *SupplierResourceRequestCreate) SetNillableReviewNote(v *string) *SupplierResourceRequestCreate {
	if v != nil {
		_c.SetReviewNote(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SupplierResourceRequestCreate) SetGroupID(v int64) *SupplierResourceRequestCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *SupplierResourceRequestCreate) SetNillableGroupID(v *int64) *SupplierResourceRequestCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *SupplierResourceRequestCreate) SetAccountID(v int64) *SupplierResourceRequestCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *SupplierResourceRequestCreate) SetNillableAccountID(v *int64) *SupplierResourceRequestCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetMonitorID sets the "monitor_id" field.
func (_c *SupplierResourceRequestCreate) SetMonitorID(v int64) *SupplierResourceRequestCreate {
	_c.mutation.SetMonitorID(v)
	return _c
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (_c *SupplierResourceRequestCreate) SetNillableMonitorID(v *int64) *SupplierResourceRequestCreate {
	if v != nil {
		_c.SetMonitorID(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *SupplierResourceRequestCreate) SetReviewedAt(v time.Time) *SupplierResourceRequestCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *SupplierResourceRequestCreate) SetNillableReviewedAt(v *time.Time) *SupplierResourceRequestCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupplierResourceRequestCreate) SetCreatedAt(v time.Time) *SupplierResourceRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupplierResourceRequestCreate) SetNillableCreatedAt(v *time.Time) *SupplierResourceRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSupplier sets the "supplier" edge to the Supplier entity.
func (_c *SupplierResourceRequestCreate) SetSupplier(v *Supplier) *SupplierResourceRequestCreate {
	return _c.SetSupplierID(v.ID)
}

// Mutation returns the SupplierResourceRequestMutation object of the builder.
func (_c *SupplierResourceRequestCreate) Mutation() *SupplierResourceRequestMutation {
	return _c.mutation
}

// Save creates the SupplierResourceRequest in the database.
func (_c *SupplierResourceRequestCreate) Save(ctx context.Context) (*SupplierResourceRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupplierResourceRequestCreate) SaveX(ctx context.Context) *SupplierResourceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupplierResourceRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupplierResourceRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupplierResourceRequestCreate) defaults() {
	if _, ok := _c.mutation.Model(); !ok {
		v := supplierresourcerequest.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.SupportedModels(); !ok {
		v := supplierresourcerequest.DefaultSupportedModels
		_c.mutation.SetSupportedModels(v)
	}
	if _, ok := _c.mutation.ProbeEnabled(); !ok {
		v := supplierresourcerequest.DefaultProbeEnabled
		_c.mutation.SetProbeEnabled(v)
	}
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		v := supplierresourcerequest.DefaultRateMultiplier
		_c.mutation.SetRateMultiplier(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := supplierresourcerequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ReviewNote(); !ok {
		v := supplierresourcerequest.DefaultReviewNote
		_c.mutation.SetReviewNote(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := supplierresourcerequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupplierResourceRequestCreate) check() error {
	if _, ok := _c.mutation.SupplierID(); !ok {
		return &ValidationError{Name: "supplier_id", err: errors.New(`ent: missing required field "SupplierResourceRequest.supplier_id"`)}
	}
	if _, ok := _c.mutation.GroupName(); !ok {
		return &ValidationError{Name: "group_name", err: errors.New(`ent: missing required field "SupplierResourceRequest.group_name"`)}
	}
	if v, ok := _c.mutation.GroupName(); ok {
		if err := supplierresourcerequest.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "SupplierResourceRequest.group_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RelayName(); !ok {
		return &ValidationError{Name: "relay_name", err: errors.New(`ent: missing required field "SupplierResourceRequest.relay_name"`)}
	}
	if v, ok := _c.mutation.RelayName(); ok {
		if err := supplierresourcerequest.RelayNameValidator(v); err != nil {
			return &ValidationError{Name: "relay_name", err: fmt.Errorf(`ent: validator failed for field "SupplierResourceRequest.relay_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RelayURL(); !ok {
		return &ValidationError{Name: "relay_url", err: errors.New(`ent: missing required field "SupplierResourceRequest.relay_url"`)}
	}
	if v, ok := _c.mutation.RelayURL(); ok {
		if err := supplierresourcerequest.RelayURLValidator(v); err != nil {
			return &ValidationError{Name: "relay_url", err: fmt.Errorf(`ent: validator failed for field "SupplierResourceRequest.relay_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKeyEncrypted(); !ok {
		return &ValidationError{Name: "api_key_encrypted", err: errors.New(`ent: missing required field "SupplierResourceRequest.api_key_encrypted"`)}
	}
	if v, ok := _c.mutation.APIKeyEncrypted(); ok {
		if err := supplierresourcerequest.APIKeyEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "api_key_encrypted", err: fmt.Errorf(`ent: validator failed for field "SupplierResourceRequest.api_key_encrypted": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "SupplierResourceRequest.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := supplierresourcerequest.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "SupplierResourceRequest.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SupportedModels(); !ok {
		return &ValidationError{Name: "supported_models", err: errors.New(`ent: missing required field "SupplierResourceRequest.supported_models"`)}
	}
	if _, ok := _c.mutation.ProbeEnabled(); !ok {
		return &ValidationError{Name: "probe_enabled", err: errors.New(`ent: missing required field "SupplierResourceRequest.probe_enabled"`)}
	}
	if _, ok := _c.mutation.RateMultiplier(); !ok {
		return &ValidationError{Name: "rate_multiplier", err: errors.New(`ent: missing required field "SupplierResourceRequest.rate_multiplier"`)}
	}
	if v, ok := _c.mutation.RateMultiplier(); ok {
		if err := supplierresourcerequest.RateMultiplierValidator(v); err != nil {
			return &ValidationError{Name: "rate_multiplier", err: fmt.Errorf(`ent: validator failed for field "SupplierResourceRequest.rate_multiplier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SupplierResourceRequest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := supplierresourcerequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupplierResourceRequest.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReviewNote(); !ok {
		return &ValidationError{Name: "review_note", err: errors.New(`ent: missing required field "SupplierResourceRequest.review_note"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupplierResourceRequest.created_at"`)}
	}
	if len(_c.mutation.SupplierIDs()) == 0 {
		return &ValidationError{Name: "supplier", err: errors.New(`ent: missing required edge "SupplierResourceRequest.supplier"`)}
	}
	return nil
}

func (_c *SupplierResourceRequestCreate) sqlSave(ctx context.Context) (*SupplierResourceRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupplierResourceRequestCreate) createSpec() (*SupplierResourceRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &SupplierResourceRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supplierresourcerequest.Table, sqlgraph.NewFieldSpec(supplierresourcerequest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GroupName(); ok {
		_spec.SetField(supplierresourcerequest.FieldGroupName, field.TypeString, value)
		_node.GroupName = value
	}
	if value, ok := _c.mutation.RelayName(); ok {
		_spec.SetField(supplierresourcerequest.FieldRelayName, field.TypeString, value)
		_node.RelayName = value
	}
	if value, ok := _c.mutation.RelayURL(); ok {
		_spec.SetField(supplierresourcerequest.FieldRelayURL, field.TypeString, value)
		_node.RelayURL = value
	}
	if value, ok := _c.mutation.APIKeyEncrypted(); ok {
		_spec.SetField(supplierresourcerequest.FieldAPIKeyEncrypted, field.TypeString, value)
		_node.APIKeyEncrypted = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(supplierresourcerequest.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.SupportedModels(); ok {
		_spec.SetField(supplierresourcerequest.FieldSupportedModels, field.TypeJSON, value)
		_node.SupportedModels = value
	}
	if value, ok := _c.mutation.ProbeEnabled(); ok {
		_spec.SetField(supplierresourcerequest.FieldProbeEnabled, field.TypeBool, value)
		_node.ProbeEnabled = value
	}
	if value, ok := _c.mutation.RateMultiplier(); ok {
		_spec.SetField(supplierresourcerequest.FieldRateMultiplier, field.TypeFloat64, value)
		_node.RateMultiplier = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(supplierresourcerequest.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ReviewedBy(); ok {
		_spec.SetField(supplierresourcerequest.FieldReviewedBy, field.TypeInt64, value)
		_node.ReviewedBy = &value
	}
	if value, ok := _c.mutation.ReviewNote(); ok {
		_spec.SetField(supplierresourcerequest.FieldReviewNote, field.TypeString, value)
		_node.ReviewNote = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(supplierresourcerequest.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(supplierresourcerequest.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.MonitorID(); ok {
		_spec.SetField(supplierresourcerequest.FieldMonitorID, field.TypeInt64, value)
		_node.MonitorID = &value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(supplierresourcerequest.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supplierresourcerequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SupplierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supplierresourcerequest.SupplierTable,
			Columns: []string{supplierresourcerequest.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SupplierID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupplierResourceRequest.Create().
//		SetSupplierID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupplierResourceRequestUpsert) {
//			SetSupplierID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupplierResourceRequestCreate) OnConflict(opts ...sql.ConflictOption) *SupplierResourceRequestUpsertOne {
	_c.conflict = opts
	return &SupplierResourceRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupplierResourceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupplierResourceRequestCreate) OnConflictColumns(columns ...string) *SupplierResourceRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupplierResourceRequestUpsertOne{
		create: _c,
	}
}

type (
	// SupplierResourceRequestUpsertOne is the builder for "upsert"-ing
	//  one SupplierResourceRequest node.
	SupplierResourceRequestUpsertOne struct {
		create *SupplierResourceRequestCreate
	}

	// SupplierResourceRequestUpsert is the "OnConflict" setter.
	SupplierResourceRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetSupplierID sets the "supplier_id" field.
func (u *SupplierResourceRequestUpsert) SetSupplierID(v int64) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldSupplierID, v)
	return u
}

// UpdateSupplierID sets the "supplier_id" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateSupplierID() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldSupplierID)
	return u
}

// SetGroupName sets the "group_name" field.
func (u *SupplierResourceRequestUpsert) SetGroupName(v string) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldGroupName, v)
	return u
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateGroupName() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldGroupName)
	return u
}

// SetRelayName sets the "relay_name" field.
func (u *SupplierResourceRequestUpsert) SetRelayName(v string) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldRelayName, v)
	return u
}

// UpdateRelayName sets the "relay_name" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateRelayName() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldRelayName)
	return u
}

// SetRelayURL sets the "relay_url" field.
func (u *SupplierResourceRequestUpsert) SetRelayURL(v string) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldRelayURL, v)
	return u
}

// UpdateRelayURL sets the "relay_url" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateRelayURL() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldRelayURL)
	return u
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (u *SupplierResourceRequestUpsert) SetAPIKeyEncrypted(v string) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldAPIKeyEncrypted, v)
	return u
}

// UpdateAPIKeyEncrypted sets the "api_key_encrypted" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateAPIKeyEncrypted() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldAPIKeyEncrypted)
	return u
}

// SetModel sets the "model" field.
func (u *SupplierResourceRequestUpsert) SetModel(v string) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateModel() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldModel)
	return u
}

// SetSupportedModels sets the "supported_models" field.
func (u *SupplierResourceRequestUpsert) SetSupportedModels(v []string) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldSupportedModels, v)
	return u
}

// UpdateSupportedModels sets the "supported_models" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateSupportedModels() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldSupportedModels)
	return u
}

// SetProbeEnabled sets the "probe_enabled" field.
func (u *SupplierResourceRequestUpsert) SetProbeEnabled(v bool) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldProbeEnabled, v)
	return u
}

// UpdateProbeEnabled sets the "probe_enabled" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateProbeEnabled() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldProbeEnabled)
	return u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *SupplierResourceRequestUpsert) SetRateMultiplier(v float64) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldRateMultiplier, v)
	return u
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateRateMultiplier() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldRateMultiplier)
	return u
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *SupplierResourceRequestUpsert) AddRateMultiplier(v float64) *SupplierResourceRequestUpsert {
	u.Add(supplierresourcerequest.FieldRateMultiplier, v)
	return u
}

// SetStatus sets the "status" field.
func (u *SupplierResourceRequestUpsert) SetStatus(v supplierresourcerequest.Status) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateStatus() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldStatus)
	return u
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *SupplierResourceRequestUpsert) SetReviewedBy(v int64) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldReviewedBy, v)
	return u
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateReviewedBy() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldReviewedBy)
	return u
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *SupplierResourceRequestUpsert) AddReviewedBy(v int64) *SupplierResourceRequestUpsert {
	u.Add(supplierresourcerequest.FieldReviewedBy, v)
	return u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *SupplierResourceRequestUpsert) ClearReviewedBy() *SupplierResourceRequestUpsert {
	u.SetNull(supplierresourcerequest.FieldReviewedBy)
	return u
}

// SetReviewNote sets the "review_note" field.
func (u *SupplierResourceRequestUpsert) SetReviewNote(v string) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldReviewNote, v)
	return u
}

// UpdateReviewNote sets the "review_note" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateReviewNote() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldReviewNote)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SupplierResourceRequestUpsert) SetGroupID(v int64) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateGroupID() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *SupplierResourceRequestUpsert) AddGroupID(v int64) *SupplierResourceRequestUpsert {
	u.Add(supplierresourcerequest.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *SupplierResourceRequestUpsert) ClearGroupID() *SupplierResourceRequestUpsert {
	u.SetNull(supplierresourcerequest.FieldGroupID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *SupplierResourceRequestUpsert) SetAccountID(v int64) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateAccountID() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *SupplierResourceRequestUpsert) AddAccountID(v int64) *SupplierResourceRequestUpsert {
	u.Add(supplierresourcerequest.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *SupplierResourceRequestUpsert) ClearAccountID() *SupplierResourceRequestUpsert {
	u.SetNull(supplierresourcerequest.FieldAccountID)
	return u
}

// SetMonitorID sets the "monitor_id" field.
func (u *SupplierResourceRequestUpsert) SetMonitorID(v int64) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldMonitorID, v)
	return u
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateMonitorID() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldMonitorID)
	return u
}

// AddMonitorID adds v to the "monitor_id" field.
func (u *SupplierResourceRequestUpsert) AddMonitorID(v int64) *SupplierResourceRequestUpsert {
	u.Add(supplierresourcerequest.FieldMonitorID, v)
	return u
}

// ClearMonitorID clears the value of the "monitor_id" field.
func (u *SupplierResourceRequestUpsert) ClearMonitorID() *SupplierResourceRequestUpsert {
	u.SetNull(supplierresourcerequest.FieldMonitorID)
	return u
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *SupplierResourceRequestUpsert) SetReviewedAt(v time.Time) *SupplierResourceRequestUpsert {
	u.Set(supplierresourcerequest.FieldReviewedAt, v)
	return u
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsert) UpdateReviewedAt() *SupplierResourceRequestUpsert {
	u.SetExcluded(supplierresourcerequest.FieldReviewedAt)
	return u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *SupplierResourceRequestUpsert) ClearReviewedAt() *SupplierResourceRequestUpsert {
	u.SetNull(supplierresourcerequest.FieldReviewedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SupplierResourceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupplierResourceRequestUpsertOne) UpdateNewValues() *SupplierResourceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(supplierresourcerequest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupplierResourceRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupplierResourceRequestUpsertOne) Ignore() *SupplierResourceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupplierResourceRequestUpsertOne) DoNothing() *SupplierResourceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupplierResourceRequestCreate.OnConflict
// documentation for more info.
func (u *SupplierResourceRequestUpsertOne) Update(set func(*SupplierResourceRequestUpsert)) *SupplierResourceRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupplierResourceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetSupplierID sets the "supplier_id" field.
func (u *SupplierResourceRequestUpsertOne) SetSupplierID(v int64) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetSupplierID(v)
	})
}

// UpdateSupplierID sets the "supplier_id" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateSupplierID() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateSupplierID()
	})
}

// SetGroupName sets the "group_name" field.
func (u *SupplierResourceRequestUpsertOne) SetGroupName(v string) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateGroupName() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateGroupName()
	})
}

// SetRelayName sets the "relay_name" field.
func (u *SupplierResourceRequestUpsertOne) SetRelayName(v string) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetRelayName(v)
	})
}

// UpdateRelayName sets the "relay_name" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateRelayName() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateRelayName()
	})
}

// SetRelayURL sets the "relay_url" field.
func (u *SupplierResourceRequestUpsertOne) SetRelayURL(v string) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetRelayURL(v)
	})
}

// UpdateRelayURL sets the "relay_url" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateRelayURL() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateRelayURL()
	})
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (u *SupplierResourceRequestUpsertOne) SetAPIKeyEncrypted(v string) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetAPIKeyEncrypted(v)
	})
}

// UpdateAPIKeyEncrypted sets the "api_key_encrypted" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateAPIKeyEncrypted() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateAPIKeyEncrypted()
	})
}

// SetModel sets the "model" field.
func (u *SupplierResourceRequestUpsertOne) SetModel(v string) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateModel() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateModel()
	})
}

// SetSupportedModels sets the "supported_models" field.
func (u *SupplierResourceRequestUpsertOne) SetSupportedModels(v []string) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetSupportedModels(v)
	})
}

// UpdateSupportedModels sets the "supported_models" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateSupportedModels() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateSupportedModels()
	})
}

// SetProbeEnabled sets the "probe_enabled" field.
func (u *SupplierResourceRequestUpsertOne) SetProbeEnabled(v bool) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetProbeEnabled(v)
	})
}

// UpdateProbeEnabled sets the "probe_enabled" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateProbeEnabled() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateProbeEnabled()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *SupplierResourceRequestUpsertOne) SetRateMultiplier(v float64) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *SupplierResourceRequestUpsertOne) AddRateMultiplier(v float64) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateRateMultiplier() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetStatus sets the "status" field.
func (u *SupplierResourceRequestUpsertOne) SetStatus(v supplierresourcerequest.Status) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateStatus() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *SupplierResourceRequestUpsertOne) SetReviewedBy(v int64) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetReviewedBy(v)
	})
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *SupplierResourceRequestUpsertOne) AddReviewedBy(v int64) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.AddReviewedBy(v)
	})
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateReviewedBy() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateReviewedBy()
	})
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *SupplierResourceRequestUpsertOne) ClearReviewedBy() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.ClearReviewedBy()
	})
}

// SetReviewNote sets the "review_note" field.
func (u *SupplierResourceRequestUpsertOne) SetReviewNote(v string) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetReviewNote(v)
	})
}

// UpdateReviewNote sets the "review_note" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateReviewNote() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateReviewNote()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SupplierResourceRequestUpsertOne) SetGroupID(v int64) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SupplierResourceRequestUpsertOne) AddGroupID(v int64) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateGroupID() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *SupplierResourceRequestUpsertOne) ClearGroupID() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *SupplierResourceRequestUpsertOne) SetAccountID(v int64) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *SupplierResourceRequestUpsertOne) AddAccountID(v int64) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateAccountID() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *SupplierResourceRequestUpsertOne) ClearAccountID() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.ClearAccountID()
	})
}

// SetMonitorID sets the "monitor_id" field.
func (u *SupplierResourceRequestUpsertOne) SetMonitorID(v int64) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetMonitorID(v)
	})
}

// AddMonitorID adds v to the "monitor_id" field.
func (u *SupplierResourceRequestUpsertOne) AddMonitorID(v int64) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.AddMonitorID(v)
	})
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateMonitorID() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateMonitorID()
	})
}

// ClearMonitorID clears the value of the "monitor_id" field.
func (u *SupplierResourceRequestUpsertOne) ClearMonitorID() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.ClearMonitorID()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *SupplierResourceRequestUpsertOne) SetReviewedAt(v time.Time) *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertOne) UpdateReviewedAt() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *SupplierResourceRequestUpsertOne) ClearReviewedAt() *SupplierResourceRequestUpsertOne {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.ClearReviewedAt()
	})
}

// Exec executes the query.
func (u *SupplierResourceRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupplierResourceRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupplierResourceRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupplierResourceRequestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupplierResourceRequestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupplierResourceRequestCreateBulk is the builder for creating many SupplierResourceRequest entities in bulk.
type SupplierResourceRequestCreateBulk struct {
	config
	err      error
	builders []*SupplierResourceRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the SupplierResourceRequest entities in the database.
func (_c *SupplierResourceRequestCreateBulk) Save(ctx context.Context) ([]*SupplierResourceRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupplierResourceRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupplierResourceRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupplierResourceRequestCreateBulk) SaveX(ctx context.Context) []*SupplierResourceRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupplierResourceRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupplierResourceRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupplierResourceRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupplierResourceRequestUpsert) {
//			SetSupplierID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupplierResourceRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupplierResourceRequestUpsertBulk {
	_c.conflict = opts
	return &SupplierResourceRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupplierResourceRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupplierResourceRequestCreateBulk) OnConflictColumns(columns ...string) *SupplierResourceRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupplierResourceRequestUpsertBulk{
		create: _c,
	}
}

// SupplierResourceRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of SupplierResourceRequest nodes.
type SupplierResourceRequestUpsertBulk struct {
	create *SupplierResourceRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupplierResourceRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupplierResourceRequestUpsertBulk) UpdateNewValues() *SupplierResourceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(supplierresourcerequest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupplierResourceRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupplierResourceRequestUpsertBulk) Ignore() *SupplierResourceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupplierResourceRequestUpsertBulk) DoNothing() *SupplierResourceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupplierResourceRequestCreateBulk.OnConflict
// documentation for more info.
func (u *SupplierResourceRequestUpsertBulk) Update(set func(*SupplierResourceRequestUpsert)) *SupplierResourceRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupplierResourceRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetSupplierID sets the "supplier_id" field.
func (u *SupplierResourceRequestUpsertBulk) SetSupplierID(v int64) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetSupplierID(v)
	})
}

// UpdateSupplierID sets the "supplier_id" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateSupplierID() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateSupplierID()
	})
}

// SetGroupName sets the "group_name" field.
func (u *SupplierResourceRequestUpsertBulk) SetGroupName(v string) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetGroupName(v)
	})
}

// UpdateGroupName sets the "group_name" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateGroupName() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateGroupName()
	})
}

// SetRelayName sets the "relay_name" field.
func (u *SupplierResourceRequestUpsertBulk) SetRelayName(v string) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetRelayName(v)
	})
}

// UpdateRelayName sets the "relay_name" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateRelayName() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateRelayName()
	})
}

// SetRelayURL sets the "relay_url" field.
func (u *SupplierResourceRequestUpsertBulk) SetRelayURL(v string) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetRelayURL(v)
	})
}

// UpdateRelayURL sets the "relay_url" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateRelayURL() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateRelayURL()
	})
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (u *SupplierResourceRequestUpsertBulk) SetAPIKeyEncrypted(v string) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetAPIKeyEncrypted(v)
	})
}

// UpdateAPIKeyEncrypted sets the "api_key_encrypted" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateAPIKeyEncrypted() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateAPIKeyEncrypted()
	})
}

// SetModel sets the "model" field.
func (u *SupplierResourceRequestUpsertBulk) SetModel(v string) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateModel() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateModel()
	})
}

// SetSupportedModels sets the "supported_models" field.
func (u *SupplierResourceRequestUpsertBulk) SetSupportedModels(v []string) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetSupportedModels(v)
	})
}

// UpdateSupportedModels sets the "supported_models" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateSupportedModels() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateSupportedModels()
	})
}

// SetProbeEnabled sets the "probe_enabled" field.
func (u *SupplierResourceRequestUpsertBulk) SetProbeEnabled(v bool) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetProbeEnabled(v)
	})
}

// UpdateProbeEnabled sets the "probe_enabled" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateProbeEnabled() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateProbeEnabled()
	})
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (u *SupplierResourceRequestUpsertBulk) SetRateMultiplier(v float64) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetRateMultiplier(v)
	})
}

// AddRateMultiplier adds v to the "rate_multiplier" field.
func (u *SupplierResourceRequestUpsertBulk) AddRateMultiplier(v float64) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.AddRateMultiplier(v)
	})
}

// UpdateRateMultiplier sets the "rate_multiplier" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateRateMultiplier() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateRateMultiplier()
	})
}

// SetStatus sets the "status" field.
func (u *SupplierResourceRequestUpsertBulk) SetStatus(v supplierresourcerequest.Status) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateStatus() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *SupplierResourceRequestUpsertBulk) SetReviewedBy(v int64) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetReviewedBy(v)
	})
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *SupplierResourceRequestUpsertBulk) AddReviewedBy(v int64) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.AddReviewedBy(v)
	})
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateReviewedBy() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateReviewedBy()
	})
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *SupplierResourceRequestUpsertBulk) ClearReviewedBy() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.ClearReviewedBy()
	})
}

// SetReviewNote sets the "review_note" field.
func (u *SupplierResourceRequestUpsertBulk) SetReviewNote(v string) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetReviewNote(v)
	})
}

// UpdateReviewNote sets the "review_note" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateReviewNote() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateReviewNote()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SupplierResourceRequestUpsertBulk) SetGroupID(v int64) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SupplierResourceRequestUpsertBulk) AddGroupID(v int64) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateGroupID() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *SupplierResourceRequestUpsertBulk) ClearGroupID() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *SupplierResourceRequestUpsertBulk) SetAccountID(v int64) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *SupplierResourceRequestUpsertBulk) AddAccountID(v int64) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateAccountID() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *SupplierResourceRequestUpsertBulk) ClearAccountID() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.ClearAccountID()
	})
}

// SetMonitorID sets the "monitor_id" field.
func (u *SupplierResourceRequestUpsertBulk) SetMonitorID(v int64) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetMonitorID(v)
	})
}

// AddMonitorID adds v to the "monitor_id" field.
func (u *SupplierResourceRequestUpsertBulk) AddMonitorID(v int64) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.AddMonitorID(v)
	})
}

// UpdateMonitorID sets the "monitor_id" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateMonitorID() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateMonitorID()
	})
}

// ClearMonitorID clears the value of the "monitor_id" field.
func (u *SupplierResourceRequestUpsertBulk) ClearMonitorID() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.ClearMonitorID()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *SupplierResourceRequestUpsertBulk) SetReviewedAt(v time.Time) *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *SupplierResourceRequestUpsertBulk) UpdateReviewedAt() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *SupplierResourceRequestUpsertBulk) ClearReviewedAt() *SupplierResourceRequestUpsertBulk {
	return u.Update(func(s *SupplierResourceRequestUpsert) {
		s.ClearReviewedAt()
	})
}

// Exec executes the query.
func (u *SupplierResourceRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupplierResourceRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupplierResourceRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupplierResourceRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
