// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/suppliermetricbucket"
)

// SupplierMetricBucket is the model entity for the SupplierMetricBucket schema.
type SupplierMetricBucket struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// BucketStart holds the value of the "bucket_start" field.
	BucketStart time.Time `json:"bucket_start,omitempty"`
	// Resolution holds the value of the "resolution" field.
	Resolution suppliermetricbucket.Resolution `json:"resolution,omitempty"`
	// RequestCount holds the value of the "request_count" field.
	RequestCount int64 `json:"request_count,omitempty"`
	// SuccessCount holds the value of the "success_count" field.
	SuccessCount int64 `json:"success_count,omitempty"`
	// TotalTokens holds the value of the "total_tokens" field.
	TotalTokens int64 `json:"total_tokens,omitempty"`
	// CacheReadTokens holds the value of the "cache_read_tokens" field.
	CacheReadTokens int64 `json:"cache_read_tokens,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int64 `json:"input_tokens,omitempty"`
	// DurationMsSum holds the value of the "duration_ms_sum" field.
	DurationMsSum int64 `json:"duration_ms_sum,omitempty"`
	// FirstTokenMsSum holds the value of the "first_token_ms_sum" field.
	FirstTokenMsSum int64 `json:"first_token_ms_sum,omitempty"`
	// FirstTokenCount holds the value of the "first_token_count" field.
	FirstTokenCount int64 `json:"first_token_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupplierMetricBucket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case suppliermetricbucket.FieldID, suppliermetricbucket.FieldGroupID, suppliermetricbucket.FieldRequestCount, suppliermetricbucket.FieldSuccessCount, suppliermetricbucket.FieldTotalTokens, suppliermetricbucket.FieldCacheReadTokens, suppliermetricbucket.FieldInputTokens, suppliermetricbucket.FieldDurationMsSum, suppliermetricbucket.FieldFirstTokenMsSum, suppliermetricbucket.FieldFirstTokenCount:
			values[i] = new(sql.NullInt64)
		case suppliermetricbucket.FieldResolution:
			values[i] = new(sql.NullString)
		case suppliermetricbucket.FieldBucketStart, suppliermetricbucket.FieldCreatedAt, suppliermetricbucket.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupplierMetricBucket fields.
func (_m *SupplierMetricBucket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case suppliermetricbucket.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case suppliermetricbucket.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case suppliermetricbucket.FieldBucketStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_start", values[i])
			} else if value.Valid {
				_m.BucketStart = value.Time
			}
		case suppliermetricbucket.FieldResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution", values[i])
			} else if value.Valid {
				_m.Resolution = suppliermetricbucket.Resolution(value.String)
			}
		case suppliermetricbucket.FieldRequestCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_count", values[i])
			} else if value.Valid {
				_m.RequestCount = value.Int64
			}
		case suppliermetricbucket.FieldSuccessCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field success_count", values[i])
			} else if value.Valid {
				_m.SuccessCount = value.Int64
			}
		case suppliermetricbucket.FieldTotalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tokens", values[i])
			} else if value.Valid {
				_m.TotalTokens = value.Int64
			}
		case suppliermetricbucket.FieldCacheReadTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_tokens", values[i])
			} else if value.Valid {
				_m.CacheReadTokens = value.Int64
			}
		case suppliermetricbucket.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = value.Int64
			}
		case suppliermetricbucket.FieldDurationMsSum:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms_sum", values[i])
			} else if value.Valid {
				_m.DurationMsSum = value.Int64
			}
		case suppliermetricbucket.FieldFirstTokenMsSum:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field first_token_ms_sum", values[i])
			} else if value.Valid {
				_m.FirstTokenMsSum = value.Int64
			}
		case suppliermetricbucket.FieldFirstTokenCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field first_token_count", values[i])
			} else if value.Valid {
				_m.FirstTokenCount = value.Int64
			}
		case suppliermetricbucket.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case suppliermetricbucket.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupplierMetricBucket.
// This includes values selected through modifiers, order, etc.
func (_m *SupplierMetricBucket) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SupplierMetricBucket.
// Note that you need to call SupplierMetricBucket.Unwrap() before calling this method if this SupplierMetricBucket
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupplierMetricBucket) Update() *SupplierMetricBucketUpdateOne {
	return NewSupplierMetricBucketClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupplierMetricBucket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupplierMetricBucket) Unwrap() *SupplierMetricBucket {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupplierMetricBucket is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupplierMetricBucket) String() string {
	var builder strings.Builder
	builder.WriteString("SupplierMetricBucket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("bucket_start=")
	builder.WriteString(_m.BucketStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("resolution=")
	builder.WriteString(fmt.Sprintf("%v", _m.Resolution))
	builder.WriteString(", ")
	builder.WriteString("request_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestCount))
	builder.WriteString(", ")
	builder.WriteString("success_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessCount))
	builder.WriteString(", ")
	builder.WriteString("total_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_read_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadTokens))
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("duration_ms_sum=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMsSum))
	builder.WriteString(", ")
	builder.WriteString("first_token_ms_sum=")
	builder.WriteString(fmt.Sprintf("%v", _m.FirstTokenMsSum))
	builder.WriteString(", ")
	builder.WriteString("first_token_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FirstTokenCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupplierMetricBuckets is a parsable slice of SupplierMetricBucket.
type SupplierMetricBuckets []*SupplierMetricBucket
