// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/supplier"
	"github.com/Wei-Shaw/sub2api/ent/supplierledger"
)

// SupplierLedgerCreate is the builder for creating a SupplierLedger entity.
type SupplierLedgerCreate struct {
	config
	mutation *SupplierLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSupplierID sets the "supplier_id" field.
func (_c *SupplierLedgerCreate) SetSupplierID(v int64) *SupplierLedgerCreate {
	_c.mutation.SetSupplierID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SupplierLedgerCreate) SetGroupID(v int64) *SupplierLedgerCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *SupplierLedgerCreate) SetUsageLogID(v int64) *SupplierLedgerCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *SupplierLedgerCreate) SetNillableUsageLogID(v *int64) *SupplierLedgerCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// SetReversalOfID sets the "reversal_of_id" field.
func (_c *SupplierLedgerCreate) SetReversalOfID(v int64) *SupplierLedgerCreate {
	_c.mutation.SetReversalOfID(v)
	return _c
}

// SetNillableReversalOfID sets the "reversal_of_id" field if the given value is not nil.
func (_c *SupplierLedgerCreate) SetNillableReversalOfID(v *int64) *SupplierLedgerCreate {
	if v != nil {
		_c.SetReversalOfID(*v)
	}
	return _c
}

// SetEventKey sets the "event_key" field.
func (_c *SupplierLedgerCreate) SetEventKey(v string) *SupplierLedgerCreate {
	_c.mutation.SetEventKey(v)
	return _c
}

// SetEntryType sets the "entry_type" field.
func (_c *SupplierLedgerCreate) SetEntryType(v supplierledger.EntryType) *SupplierLedgerCreate {
	_c.mutation.SetEntryType(v)
	return _c
}

// SetBucket sets the "bucket" field.
func (_c *SupplierLedgerCreate) SetBucket(v supplierledger.Bucket) *SupplierLedgerCreate {
	_c.mutation.SetBucket(v)
	return _c
}

// SetBaseRate sets the "base_rate" field.
func (_c *SupplierLedgerCreate) SetBaseRate(v float64) *SupplierLedgerCreate {
	_c.mutation.SetBaseRate(v)
	return _c
}

// SetAdminAdjustment sets the "admin_adjustment" field.
func (_c *SupplierLedgerCreate) SetAdminAdjustment(v float64) *SupplierLedgerCreate {
	_c.mutation.SetAdminAdjustment(v)
	return _c
}

// SetEffectiveRate sets the "effective_rate" field.
func (_c *SupplierLedgerCreate) SetEffectiveRate(v float64) *SupplierLedgerCreate {
	_c.mutation.SetEffectiveRate(v)
	return _c
}

// SetModelCostUsd sets the "model_cost_usd" field.
func (_c *SupplierLedgerCreate) SetModelCostUsd(v float64) *SupplierLedgerCreate {
	_c.mutation.SetModelCostUsd(v)
	return _c
}

// SetRechargeRatio sets the "recharge_ratio" field.
func (_c *SupplierLedgerCreate) SetRechargeRatio(v float64) *SupplierLedgerCreate {
	_c.mutation.SetRechargeRatio(v)
	return _c
}

// SetEarningUsd sets the "earning_usd" field.
func (_c *SupplierLedgerCreate) SetEarningUsd(v float64) *SupplierLedgerCreate {
	_c.mutation.SetEarningUsd(v)
	return _c
}

// SetAmountCny sets the "amount_cny" field.
func (_c *SupplierLedgerCreate) SetAmountCny(v float64) *SupplierLedgerCreate {
	_c.mutation.SetAmountCny(v)
	return _c
}

// SetAvailableAt sets the "available_at" field.
func (_c *SupplierLedgerCreate) SetAvailableAt(v time.Time) *SupplierLedgerCreate {
	_c.mutation.SetAvailableAt(v)
	return _c
}

// SetNillableAvailableAt sets the "available_at" field if the given value is not nil.
func (_c *SupplierLedgerCreate) SetNillableAvailableAt(v *time.Time) *SupplierLedgerCreate {
	if v != nil {
		_c.SetAvailableAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupplierLedgerCreate) SetCreatedAt(v time.Time) *SupplierLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupplierLedgerCreate) SetNillableCreatedAt(v *time.Time) *SupplierLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSupplier sets the "supplier" edge to the Supplier entity.
func (_c *SupplierLedgerCreate) SetSupplier(v *Supplier) *SupplierLedgerCreate {
	return _c.SetSupplierID(v.ID)
}

// Mutation returns the SupplierLedgerMutation object of the builder.
func (_c *SupplierLedgerCreate) Mutation() *SupplierLedgerMutation {
	return _c.mutation
}

// Save creates the SupplierLedger in the database.
func (_c *SupplierLedgerCreate) Save(ctx context.Context) (*SupplierLedger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupplierLedgerCreate) SaveX(ctx context.Context) *SupplierLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupplierLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupplierLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupplierLedgerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := supplierledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupplierLedgerCreate) check() error {
	if _, ok := _c.mutation.SupplierID(); !ok {
		return &ValidationError{Name: "supplier_id", err: errors.New(`ent: missing required field "SupplierLedger.supplier_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SupplierLedger.group_id"`)}
	}
	if _, ok := _c.mutation.EventKey(); !ok {
		return &ValidationError{Name: "event_key", err: errors.New(`ent: missing required field "SupplierLedger.event_key"`)}
	}
	if v, ok := _c.mutation.EventKey(); ok {
		if err := supplierledger.EventKeyValidator(v); err != nil {
			return &ValidationError{Name: "event_key", err: fmt.Errorf(`ent: validator failed for field "SupplierLedger.event_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntryType(); !ok {
		return &ValidationError{Name: "entry_type", err: errors.New(`ent: missing required field "SupplierLedger.entry_type"`)}
	}
	if v, ok := _c.mutation.EntryType(); ok {
		if err := supplierledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "SupplierLedger.entry_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Bucket(); !ok {
		return &ValidationError{Name: "bucket", err: errors.New(`ent: missing required field "SupplierLedger.bucket"`)}
	}
	if v, ok := _c.mutation.Bucket(); ok {
		if err := supplierledger.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "SupplierLedger.bucket": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseRate(); !ok {
		return &ValidationError{Name: "base_rate", err: errors.New(`ent: missing required field "SupplierLedger.base_rate"`)}
	}
	if _, ok := _c.mutation.AdminAdjustment(); !ok {
		return &ValidationError{Name: "admin_adjustment", err: errors.New(`ent: missing required field "SupplierLedger.admin_adjustment"`)}
	}
	if _, ok := _c.mutation.EffectiveRate(); !ok {
		return &ValidationError{Name: "effective_rate", err: errors.New(`ent: missing required field "SupplierLedger.effective_rate"`)}
	}
	if _, ok := _c.mutation.ModelCostUsd(); !ok {
		return &ValidationError{Name: "model_cost_usd", err: errors.New(`ent: missing required field "SupplierLedger.model_cost_usd"`)}
	}
	if _, ok := _c.mutation.RechargeRatio(); !ok {
		return &ValidationError{Name: "recharge_ratio", err: errors.New(`ent: missing required field "SupplierLedger.recharge_ratio"`)}
	}
	if _, ok := _c.mutation.EarningUsd(); !ok {
		return &ValidationError{Name: "earning_usd", err: errors.New(`ent: missing required field "SupplierLedger.earning_usd"`)}
	}
	if _, ok := _c.mutation.AmountCny(); !ok {
		return &ValidationError{Name: "amount_cny", err: errors.New(`ent: missing required field "SupplierLedger.amount_cny"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupplierLedger.created_at"`)}
	}
	if len(_c.mutation.SupplierIDs()) == 0 {
		return &ValidationError{Name: "supplier", err: errors.New(`ent: missing required edge "SupplierLedger.supplier"`)}
	}
	return nil
}

func (_c *SupplierLedgerCreate) sqlSave(ctx context.Context) (*SupplierLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupplierLedgerCreate) createSpec() (*SupplierLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &SupplierLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supplierledger.Table, sqlgraph.NewFieldSpec(supplierledger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(supplierledger.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(supplierledger.FieldUsageLogID, field.TypeInt64, value)
		_node.UsageLogID = &value
	}
	if value, ok := _c.mutation.ReversalOfID(); ok {
		_spec.SetField(supplierledger.FieldReversalOfID, field.TypeInt64, value)
		_node.ReversalOfID = &value
	}
	if value, ok := _c.mutation.EventKey(); ok {
		_spec.SetField(supplierledger.FieldEventKey, field.TypeString, value)
		_node.EventKey = value
	}
	if value, ok := _c.mutation.EntryType(); ok {
		_spec.SetField(supplierledger.FieldEntryType, field.TypeEnum, value)
		_node.EntryType = value
	}
	if value, ok := _c.mutation.Bucket(); ok {
		_spec.SetField(supplierledger.FieldBucket, field.TypeEnum, value)
		_node.Bucket = value
	}
	if value, ok := _c.mutation.BaseRate(); ok {
		_spec.SetField(supplierledger.FieldBaseRate, field.TypeFloat64, value)
		_node.BaseRate = value
	}
	if value, ok := _c.mutation.AdminAdjustment(); ok {
		_spec.SetField(supplierledger.FieldAdminAdjustment, field.TypeFloat64, value)
		_node.AdminAdjustment = value
	}
	if value, ok := _c.mutation.EffectiveRate(); ok {
		_spec.SetField(supplierledger.FieldEffectiveRate, field.TypeFloat64, value)
		_node.EffectiveRate = value
	}
	if value, ok := _c.mutation.ModelCostUsd(); ok {
		_spec.SetField(supplierledger.FieldModelCostUsd, field.TypeFloat64, value)
		_node.ModelCostUsd = value
	}
	if value, ok := _c.mutation.RechargeRatio(); ok {
		_spec.SetField(supplierledger.FieldRechargeRatio, field.TypeFloat64, value)
		_node.RechargeRatio = value
	}
	if value, ok := _c.mutation.EarningUsd(); ok {
		_spec.SetField(supplierledger.FieldEarningUsd, field.TypeFloat64, value)
		_node.EarningUsd = value
	}
	if value, ok := _c.mutation.AmountCny(); ok {
		_spec.SetField(supplierledger.FieldAmountCny, field.TypeFloat64, value)
		_node.AmountCny = value
	}
	if value, ok := _c.mutation.AvailableAt(); ok {
		_spec.SetField(supplierledger.FieldAvailableAt, field.TypeTime, value)
		_node.AvailableAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supplierledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SupplierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supplierledger.SupplierTable,
			Columns: []string{supplierledger.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SupplierID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupplierLedger.Create().
//		SetSupplierID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupplierLedgerUpsert) {
//			SetSupplierID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupplierLedgerCreate) OnConflict(opts ...sql.ConflictOption) *SupplierLedgerUpsertOne {
	_c.conflict = opts
	return &SupplierLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupplierLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupplierLedgerCreate) OnConflictColumns(columns ...string) *SupplierLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupplierLedgerUpsertOne{
		create: _c,
	}
}

type (
	// SupplierLedgerUpsertOne is the builder for "upsert"-ing
	//  one SupplierLedger node.
	SupplierLedgerUpsertOne struct {
		create *SupplierLedgerCreate
	}

	// SupplierLedgerUpsert is the "OnConflict" setter.
	SupplierLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetSupplierID sets the "supplier_id" field.
func (u *SupplierLedgerUpsert) SetSupplierID(v int64) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldSupplierID, v)
	return u
}

// UpdateSupplierID sets the "supplier_id" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateSupplierID() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldSupplierID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SupplierLedgerUpsert) SetGroupID(v int64) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateGroupID() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *SupplierLedgerUpsert) AddGroupID(v int64) *SupplierLedgerUpsert {
	u.Add(supplierledger.FieldGroupID, v)
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *SupplierLedgerUpsert) SetUsageLogID(v int64) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateUsageLogID() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldUsageLogID)
	return u
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *SupplierLedgerUpsert) AddUsageLogID(v int64) *SupplierLedgerUpsert {
	u.Add(supplierledger.FieldUsageLogID, v)
	return u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *SupplierLedgerUpsert) ClearUsageLogID() *SupplierLedgerUpsert {
	u.SetNull(supplierledger.FieldUsageLogID)
	return u
}

// SetReversalOfID sets the "reversal_of_id" field.
func (u *SupplierLedgerUpsert) SetReversalOfID(v int64) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldReversalOfID, v)
	return u
}

// UpdateReversalOfID sets the "reversal_of_id" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateReversalOfID() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldReversalOfID)
	return u
}

// AddReversalOfID adds v to the "reversal_of_id" field.
func (u *SupplierLedgerUpsert) AddReversalOfID(v int64) *SupplierLedgerUpsert {
	u.Add(supplierledger.FieldReversalOfID, v)
	return u
}

// ClearReversalOfID clears the value of the "reversal_of_id" field.
func (u *SupplierLedgerUpsert) ClearReversalOfID() *SupplierLedgerUpsert {
	u.SetNull(supplierledger.FieldReversalOfID)
	return u
}

// SetEventKey sets the "event_key" field.
func (u *SupplierLedgerUpsert) SetEventKey(v string) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldEventKey, v)
	return u
}

// UpdateEventKey sets the "event_key" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateEventKey() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldEventKey)
	return u
}

// SetEntryType sets the "entry_type" field.
func (u *SupplierLedgerUpsert) SetEntryType(v supplierledger.EntryType) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldEntryType, v)
	return u
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateEntryType() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldEntryType)
	return u
}

// SetBucket sets the "bucket" field.
func (u *SupplierLedgerUpsert) SetBucket(v supplierledger.Bucket) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldBucket, v)
	return u
}

// UpdateBucket sets the "bucket" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateBucket() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldBucket)
	return u
}

// SetBaseRate sets the "base_rate" field.
func (u *SupplierLedgerUpsert) SetBaseRate(v float64) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldBaseRate, v)
	return u
}

// UpdateBaseRate sets the "base_rate" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateBaseRate() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldBaseRate)
	return u
}

// AddBaseRate adds v to the "base_rate" field.
func (u *SupplierLedgerUpsert) AddBaseRate(v float64) *SupplierLedgerUpsert {
	u.Add(supplierledger.FieldBaseRate, v)
	return u
}

// SetAdminAdjustment sets the "admin_adjustment" field.
func (u *SupplierLedgerUpsert) SetAdminAdjustment(v float64) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldAdminAdjustment, v)
	return u
}

// UpdateAdminAdjustment sets the "admin_adjustment" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateAdminAdjustment() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldAdminAdjustment)
	return u
}

// AddAdminAdjustment adds v to the "admin_adjustment" field.
func (u *SupplierLedgerUpsert) AddAdminAdjustment(v float64) *SupplierLedgerUpsert {
	u.Add(supplierledger.FieldAdminAdjustment, v)
	return u
}

// SetEffectiveRate sets the "effective_rate" field.
func (u *SupplierLedgerUpsert) SetEffectiveRate(v float64) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldEffectiveRate, v)
	return u
}

// UpdateEffectiveRate sets the "effective_rate" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateEffectiveRate() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldEffectiveRate)
	return u
}

// AddEffectiveRate adds v to the "effective_rate" field.
func (u *SupplierLedgerUpsert) AddEffectiveRate(v float64) *SupplierLedgerUpsert {
	u.Add(supplierledger.FieldEffectiveRate, v)
	return u
}

// SetModelCostUsd sets the "model_cost_usd" field.
func (u *SupplierLedgerUpsert) SetModelCostUsd(v float64) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldModelCostUsd, v)
	return u
}

// UpdateModelCostUsd sets the "model_cost_usd" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateModelCostUsd() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldModelCostUsd)
	return u
}

// AddModelCostUsd adds v to the "model_cost_usd" field.
func (u *SupplierLedgerUpsert) AddModelCostUsd(v float64) *SupplierLedgerUpsert {
	u.Add(supplierledger.FieldModelCostUsd, v)
	return u
}

// SetRechargeRatio sets the "recharge_ratio" field.
func (u *SupplierLedgerUpsert) SetRechargeRatio(v float64) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldRechargeRatio, v)
	return u
}

// UpdateRechargeRatio sets the "recharge_ratio" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateRechargeRatio() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldRechargeRatio)
	return u
}

// AddRechargeRatio adds v to the "recharge_ratio" field.
func (u *SupplierLedgerUpsert) AddRechargeRatio(v float64) *SupplierLedgerUpsert {
	u.Add(supplierledger.FieldRechargeRatio, v)
	return u
}

// SetEarningUsd sets the "earning_usd" field.
func (u *SupplierLedgerUpsert) SetEarningUsd(v float64) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldEarningUsd, v)
	return u
}

// UpdateEarningUsd sets the "earning_usd" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateEarningUsd() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldEarningUsd)
	return u
}

// AddEarningUsd adds v to the "earning_usd" field.
func (u *SupplierLedgerUpsert) AddEarningUsd(v float64) *SupplierLedgerUpsert {
	u.Add(supplierledger.FieldEarningUsd, v)
	return u
}

// SetAmountCny sets the "amount_cny" field.
func (u *SupplierLedgerUpsert) SetAmountCny(v float64) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldAmountCny, v)
	return u
}

// UpdateAmountCny sets the "amount_cny" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateAmountCny() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldAmountCny)
	return u
}

// AddAmountCny adds v to the "amount_cny" field.
func (u *SupplierLedgerUpsert) AddAmountCny(v float64) *SupplierLedgerUpsert {
	u.Add(supplierledger.FieldAmountCny, v)
	return u
}

// SetAvailableAt sets the "available_at" field.
func (u *SupplierLedgerUpsert) SetAvailableAt(v time.Time) *SupplierLedgerUpsert {
	u.Set(supplierledger.FieldAvailableAt, v)
	return u
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *SupplierLedgerUpsert) UpdateAvailableAt() *SupplierLedgerUpsert {
	u.SetExcluded(supplierledger.FieldAvailableAt)
	return u
}

// ClearAvailableAt clears the value of the "available_at" field.
func (u *SupplierLedgerUpsert) ClearAvailableAt() *SupplierLedgerUpsert {
	u.SetNull(supplierledger.FieldAvailableAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SupplierLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupplierLedgerUpsertOne) UpdateNewValues() *SupplierLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(supplierledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupplierLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupplierLedgerUpsertOne) Ignore() *SupplierLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupplierLedgerUpsertOne) DoNothing() *SupplierLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupplierLedgerCreate.OnConflict
// documentation for more info.
func (u *SupplierLedgerUpsertOne) Update(set func(*SupplierLedgerUpsert)) *SupplierLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupplierLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetSupplierID sets the "supplier_id" field.
func (u *SupplierLedgerUpsertOne) SetSupplierID(v int64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetSupplierID(v)
	})
}

// UpdateSupplierID sets the "supplier_id" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateSupplierID() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateSupplierID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SupplierLedgerUpsertOne) SetGroupID(v int64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SupplierLedgerUpsertOne) AddGroupID(v int64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateGroupID() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateGroupID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *SupplierLedgerUpsertOne) SetUsageLogID(v int64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *SupplierLedgerUpsertOne) AddUsageLogID(v int64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateUsageLogID() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *SupplierLedgerUpsertOne) ClearUsageLogID() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.ClearUsageLogID()
	})
}

// SetReversalOfID sets the "reversal_of_id" field.
func (u *SupplierLedgerUpsertOne) SetReversalOfID(v int64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetReversalOfID(v)
	})
}

// AddReversalOfID adds v to the "reversal_of_id" field.
func (u *SupplierLedgerUpsertOne) AddReversalOfID(v int64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddReversalOfID(v)
	})
}

// UpdateReversalOfID sets the "reversal_of_id" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateReversalOfID() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateReversalOfID()
	})
}

// ClearReversalOfID clears the value of the "reversal_of_id" field.
func (u *SupplierLedgerUpsertOne) ClearReversalOfID() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.ClearReversalOfID()
	})
}

// SetEventKey sets the "event_key" field.
func (u *SupplierLedgerUpsertOne) SetEventKey(v string) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetEventKey(v)
	})
}

// UpdateEventKey sets the "event_key" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateEventKey() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateEventKey()
	})
}

// SetEntryType sets the "entry_type" field.
func (u *SupplierLedgerUpsertOne) SetEntryType(v supplierledger.EntryType) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetEntryType(v)
	})
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateEntryType() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateEntryType()
	})
}

// SetBucket sets the "bucket" field.
func (u *SupplierLedgerUpsertOne) SetBucket(v supplierledger.Bucket) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetBucket(v)
	})
}

// UpdateBucket sets the "bucket" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateBucket() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateBucket()
	})
}

// SetBaseRate sets the "base_rate" field.
func (u *SupplierLedgerUpsertOne) SetBaseRate(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetBaseRate(v)
	})
}

// AddBaseRate adds v to the "base_rate" field.
func (u *SupplierLedgerUpsertOne) AddBaseRate(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddBaseRate(v)
	})
}

// UpdateBaseRate sets the "base_rate" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateBaseRate() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateBaseRate()
	})
}

// SetAdminAdjustment sets the "admin_adjustment" field.
func (u *SupplierLedgerUpsertOne) SetAdminAdjustment(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetAdminAdjustment(v)
	})
}

// AddAdminAdjustment adds v to the "admin_adjustment" field.
func (u *SupplierLedgerUpsertOne) AddAdminAdjustment(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddAdminAdjustment(v)
	})
}

// UpdateAdminAdjustment sets the "admin_adjustment" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateAdminAdjustment() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateAdminAdjustment()
	})
}

// SetEffectiveRate sets the "effective_rate" field.
func (u *SupplierLedgerUpsertOne) SetEffectiveRate(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetEffectiveRate(v)
	})
}

// AddEffectiveRate adds v to the "effective_rate" field.
func (u *SupplierLedgerUpsertOne) AddEffectiveRate(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddEffectiveRate(v)
	})
}

// UpdateEffectiveRate sets the "effective_rate" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateEffectiveRate() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateEffectiveRate()
	})
}

// SetModelCostUsd sets the "model_cost_usd" field.
func (u *SupplierLedgerUpsertOne) SetModelCostUsd(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetModelCostUsd(v)
	})
}

// AddModelCostUsd adds v to the "model_cost_usd" field.
func (u *SupplierLedgerUpsertOne) AddModelCostUsd(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddModelCostUsd(v)
	})
}

// UpdateModelCostUsd sets the "model_cost_usd" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateModelCostUsd() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateModelCostUsd()
	})
}

// SetRechargeRatio sets the "recharge_ratio" field.
func (u *SupplierLedgerUpsertOne) SetRechargeRatio(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetRechargeRatio(v)
	})
}

// AddRechargeRatio adds v to the "recharge_ratio" field.
func (u *SupplierLedgerUpsertOne) AddRechargeRatio(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddRechargeRatio(v)
	})
}

// UpdateRechargeRatio sets the "recharge_ratio" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateRechargeRatio() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateRechargeRatio()
	})
}

// SetEarningUsd sets the "earning_usd" field.
func (u *SupplierLedgerUpsertOne) SetEarningUsd(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetEarningUsd(v)
	})
}

// AddEarningUsd adds v to the "earning_usd" field.
func (u *SupplierLedgerUpsertOne) AddEarningUsd(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddEarningUsd(v)
	})
}

// UpdateEarningUsd sets the "earning_usd" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateEarningUsd() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateEarningUsd()
	})
}

// SetAmountCny sets the "amount_cny" field.
func (u *SupplierLedgerUpsertOne) SetAmountCny(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetAmountCny(v)
	})
}

// AddAmountCny adds v to the "amount_cny" field.
func (u *SupplierLedgerUpsertOne) AddAmountCny(v float64) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddAmountCny(v)
	})
}

// UpdateAmountCny sets the "amount_cny" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateAmountCny() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateAmountCny()
	})
}

// SetAvailableAt sets the "available_at" field.
func (u *SupplierLedgerUpsertOne) SetAvailableAt(v time.Time) *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetAvailableAt(v)
	})
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *SupplierLedgerUpsertOne) UpdateAvailableAt() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateAvailableAt()
	})
}

// ClearAvailableAt clears the value of the "available_at" field.
func (u *SupplierLedgerUpsertOne) ClearAvailableAt() *SupplierLedgerUpsertOne {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.ClearAvailableAt()
	})
}

// Exec executes the query.
func (u *SupplierLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupplierLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupplierLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupplierLedgerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupplierLedgerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupplierLedgerCreateBulk is the builder for creating many SupplierLedger entities in bulk.
type SupplierLedgerCreateBulk struct {
	config
	err      error
	builders []*SupplierLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the SupplierLedger entities in the database.
func (_c *SupplierLedgerCreateBulk) Save(ctx context.Context) ([]*SupplierLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupplierLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupplierLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupplierLedgerCreateBulk) SaveX(ctx context.Context) []*SupplierLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupplierLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupplierLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupplierLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupplierLedgerUpsert) {
//			SetSupplierID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupplierLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupplierLedgerUpsertBulk {
	_c.conflict = opts
	return &SupplierLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupplierLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupplierLedgerCreateBulk) OnConflictColumns(columns ...string) *SupplierLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupplierLedgerUpsertBulk{
		create: _c,
	}
}

// SupplierLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of SupplierLedger nodes.
type SupplierLedgerUpsertBulk struct {
	create *SupplierLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupplierLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupplierLedgerUpsertBulk) UpdateNewValues() *SupplierLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(supplierledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupplierLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupplierLedgerUpsertBulk) Ignore() *SupplierLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupplierLedgerUpsertBulk) DoNothing() *SupplierLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupplierLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *SupplierLedgerUpsertBulk) Update(set func(*SupplierLedgerUpsert)) *SupplierLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupplierLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetSupplierID sets the "supplier_id" field.
func (u *SupplierLedgerUpsertBulk) SetSupplierID(v int64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetSupplierID(v)
	})
}

// UpdateSupplierID sets the "supplier_id" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateSupplierID() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateSupplierID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SupplierLedgerUpsertBulk) SetGroupID(v int64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SupplierLedgerUpsertBulk) AddGroupID(v int64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateGroupID() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateGroupID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *SupplierLedgerUpsertBulk) SetUsageLogID(v int64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *SupplierLedgerUpsertBulk) AddUsageLogID(v int64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateUsageLogID() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *SupplierLedgerUpsertBulk) ClearUsageLogID() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.ClearUsageLogID()
	})
}

// SetReversalOfID sets the "reversal_of_id" field.
func (u *SupplierLedgerUpsertBulk) SetReversalOfID(v int64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetReversalOfID(v)
	})
}

// AddReversalOfID adds v to the "reversal_of_id" field.
func (u *SupplierLedgerUpsertBulk) AddReversalOfID(v int64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddReversalOfID(v)
	})
}

// UpdateReversalOfID sets the "reversal_of_id" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateReversalOfID() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateReversalOfID()
	})
}

// ClearReversalOfID clears the value of the "reversal_of_id" field.
func (u *SupplierLedgerUpsertBulk) ClearReversalOfID() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.ClearReversalOfID()
	})
}

// SetEventKey sets the "event_key" field.
func (u *SupplierLedgerUpsertBulk) SetEventKey(v string) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetEventKey(v)
	})
}

// UpdateEventKey sets the "event_key" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateEventKey() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateEventKey()
	})
}

// SetEntryType sets the "entry_type" field.
func (u *SupplierLedgerUpsertBulk) SetEntryType(v supplierledger.EntryType) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetEntryType(v)
	})
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateEntryType() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateEntryType()
	})
}

// SetBucket sets the "bucket" field.
func (u *SupplierLedgerUpsertBulk) SetBucket(v supplierledger.Bucket) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetBucket(v)
	})
}

// UpdateBucket sets the "bucket" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateBucket() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateBucket()
	})
}

// SetBaseRate sets the "base_rate" field.
func (u *SupplierLedgerUpsertBulk) SetBaseRate(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetBaseRate(v)
	})
}

// AddBaseRate adds v to the "base_rate" field.
func (u *SupplierLedgerUpsertBulk) AddBaseRate(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddBaseRate(v)
	})
}

// UpdateBaseRate sets the "base_rate" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateBaseRate() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateBaseRate()
	})
}

// SetAdminAdjustment sets the "admin_adjustment" field.
func (u *SupplierLedgerUpsertBulk) SetAdminAdjustment(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetAdminAdjustment(v)
	})
}

// AddAdminAdjustment adds v to the "admin_adjustment" field.
func (u *SupplierLedgerUpsertBulk) AddAdminAdjustment(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddAdminAdjustment(v)
	})
}

// UpdateAdminAdjustment sets the "admin_adjustment" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateAdminAdjustment() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateAdminAdjustment()
	})
}

// SetEffectiveRate sets the "effective_rate" field.
func (u *SupplierLedgerUpsertBulk) SetEffectiveRate(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetEffectiveRate(v)
	})
}

// AddEffectiveRate adds v to the "effective_rate" field.
func (u *SupplierLedgerUpsertBulk) AddEffectiveRate(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddEffectiveRate(v)
	})
}

// UpdateEffectiveRate sets the "effective_rate" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateEffectiveRate() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateEffectiveRate()
	})
}

// SetModelCostUsd sets the "model_cost_usd" field.
func (u *SupplierLedgerUpsertBulk) SetModelCostUsd(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetModelCostUsd(v)
	})
}

// AddModelCostUsd adds v to the "model_cost_usd" field.
func (u *SupplierLedgerUpsertBulk) AddModelCostUsd(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddModelCostUsd(v)
	})
}

// UpdateModelCostUsd sets the "model_cost_usd" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateModelCostUsd() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateModelCostUsd()
	})
}

// SetRechargeRatio sets the "recharge_ratio" field.
func (u *SupplierLedgerUpsertBulk) SetRechargeRatio(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetRechargeRatio(v)
	})
}

// AddRechargeRatio adds v to the "recharge_ratio" field.
func (u *SupplierLedgerUpsertBulk) AddRechargeRatio(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddRechargeRatio(v)
	})
}

// UpdateRechargeRatio sets the "recharge_ratio" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateRechargeRatio() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateRechargeRatio()
	})
}

// SetEarningUsd sets the "earning_usd" field.
func (u *SupplierLedgerUpsertBulk) SetEarningUsd(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetEarningUsd(v)
	})
}

// AddEarningUsd adds v to the "earning_usd" field.
func (u *SupplierLedgerUpsertBulk) AddEarningUsd(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddEarningUsd(v)
	})
}

// UpdateEarningUsd sets the "earning_usd" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateEarningUsd() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateEarningUsd()
	})
}

// SetAmountCny sets the "amount_cny" field.
func (u *SupplierLedgerUpsertBulk) SetAmountCny(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetAmountCny(v)
	})
}

// AddAmountCny adds v to the "amount_cny" field.
func (u *SupplierLedgerUpsertBulk) AddAmountCny(v float64) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.AddAmountCny(v)
	})
}

// UpdateAmountCny sets the "amount_cny" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateAmountCny() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateAmountCny()
	})
}

// SetAvailableAt sets the "available_at" field.
func (u *SupplierLedgerUpsertBulk) SetAvailableAt(v time.Time) *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.SetAvailableAt(v)
	})
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *SupplierLedgerUpsertBulk) UpdateAvailableAt() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.UpdateAvailableAt()
	})
}

// ClearAvailableAt clears the value of the "available_at" field.
func (u *SupplierLedgerUpsertBulk) ClearAvailableAt() *SupplierLedgerUpsertBulk {
	return u.Update(func(s *SupplierLedgerUpsert) {
		s.ClearAvailableAt()
	})
}

// Exec executes the query.
func (u *SupplierLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupplierLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupplierLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupplierLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
