// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supplier"
	"github.com/Wei-Shaw/sub2api/ent/supplierwithdrawal"
)

// SupplierWithdrawalUpdate is the builder for updating SupplierWithdrawal entities.
type SupplierWithdrawalUpdate struct {
	config
	hooks    []Hook
	mutation *SupplierWithdrawalMutation
}

// Where appends a list predicates to the SupplierWithdrawalUpdate builder.
func (_u *SupplierWithdrawalUpdate) Where(ps ...predicate.SupplierWithdrawal) *SupplierWithdrawalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSupplierID sets the "supplier_id" field.
func (_u *SupplierWithdrawalUpdate) SetSupplierID(v int64) *SupplierWithdrawalUpdate {
	_u.mutation.SetSupplierID(v)
	return _u
}

// SetNillableSupplierID sets the "supplier_id" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdate) SetNillableSupplierID(v *int64) *SupplierWithdrawalUpdate {
	if v != nil {
		_u.SetSupplierID(*v)
	}
	return _u
}

// SetRequestNo sets the "request_no" field.
func (_u *SupplierWithdrawalUpdate) SetRequestNo(v string) *SupplierWithdrawalUpdate {
	_u.mutation.SetRequestNo(v)
	return _u
}

// SetNillableRequestNo sets the "request_no" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdate) SetNillableRequestNo(v *string) *SupplierWithdrawalUpdate {
	if v != nil {
		_u.SetRequestNo(*v)
	}
	return _u
}

// SetAmountCny sets the "amount_cny" field.
func (_u *SupplierWithdrawalUpdate) SetAmountCny(v float64) *SupplierWithdrawalUpdate {
	_u.mutation.ResetAmountCny()
	_u.mutation.SetAmountCny(v)
	return _u
}

// SetNillableAmountCny sets the "amount_cny" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdate) SetNillableAmountCny(v *float64) *SupplierWithdrawalUpdate {
	if v != nil {
		_u.SetAmountCny(*v)
	}
	return _u
}

// AddAmountCny adds value to the "amount_cny" field.
func (_u *SupplierWithdrawalUpdate) AddAmountCny(v float64) *SupplierWithdrawalUpdate {
	_u.mutation.AddAmountCny(v)
	return _u
}

// SetMethod sets the "method" field.
func (_u *SupplierWithdrawalUpdate) SetMethod(v supplierwithdrawal.Method) *SupplierWithdrawalUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdate) SetNillableMethod(v *supplierwithdrawal.Method) *SupplierWithdrawalUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPayoutSnapshot sets the "payout_snapshot" field.
func (_u *SupplierWithdrawalUpdate) SetPayoutSnapshot(v map[string]interface{}) *SupplierWithdrawalUpdate {
	_u.mutation.SetPayoutSnapshot(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupplierWithdrawalUpdate) SetStatus(v supplierwithdrawal.Status) *SupplierWithdrawalUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdate) SetNillableStatus(v *supplierwithdrawal.Status) *SupplierWithdrawalUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *SupplierWithdrawalUpdate) SetReviewedBy(v int64) *SupplierWithdrawalUpdate {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdate) SetNillableReviewedBy(v *int64) *SupplierWithdrawalUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *SupplierWithdrawalUpdate) AddReviewedBy(v int64) *SupplierWithdrawalUpdate {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *SupplierWithdrawalUpdate) ClearReviewedBy() *SupplierWithdrawalUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewNote sets the "review_note" field.
func (_u *SupplierWithdrawalUpdate) SetReviewNote(v string) *SupplierWithdrawalUpdate {
	_u.mutation.SetReviewNote(v)
	return _u
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdate) SetNillableReviewNote(v *string) *SupplierWithdrawalUpdate {
	if v != nil {
		_u.SetReviewNote(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *SupplierWithdrawalUpdate) SetReviewedAt(v time.Time) *SupplierWithdrawalUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdate) SetNillableReviewedAt(v *time.Time) *SupplierWithdrawalUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *SupplierWithdrawalUpdate) ClearReviewedAt() *SupplierWithdrawalUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetPaymentProofKey sets the "payment_proof_key" field.
func (_u *SupplierWithdrawalUpdate) SetPaymentProofKey(v string) *SupplierWithdrawalUpdate {
	_u.mutation.SetPaymentProofKey(v)
	return _u
}

// SetNillablePaymentProofKey sets the "payment_proof_key" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdate) SetNillablePaymentProofKey(v *string) *SupplierWithdrawalUpdate {
	if v != nil {
		_u.SetPaymentProofKey(*v)
	}
	return _u
}

// ClearPaymentProofKey clears the value of the "payment_proof_key" field.
func (_u *SupplierWithdrawalUpdate) ClearPaymentProofKey() *SupplierWithdrawalUpdate {
	_u.mutation.ClearPaymentProofKey()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *SupplierWithdrawalUpdate) SetPaidAt(v time.Time) *SupplierWithdrawalUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdate) SetNillablePaidAt(v *time.Time) *SupplierWithdrawalUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *SupplierWithdrawalUpdate) ClearPaidAt() *SupplierWithdrawalUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupplierWithdrawalUpdate) SetUpdatedAt(v time.Time) *SupplierWithdrawalUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSupplier sets the "supplier" edge to the Supplier entity.
func (_u *SupplierWithdrawalUpdate) SetSupplier(v *Supplier) *SupplierWithdrawalUpdate {
	return _u.SetSupplierID(v.ID)
}

// Mutation returns the SupplierWithdrawalMutation object of the builder.
func (_u *SupplierWithdrawalUpdate) Mutation() *SupplierWithdrawalMutation {
	return _u.mutation
}

// ClearSupplier clears the "supplier" edge to the Supplier entity.
func (_u *SupplierWithdrawalUpdate) ClearSupplier() *SupplierWithdrawalUpdate {
	_u.mutation.ClearSupplier()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupplierWithdrawalUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupplierWithdrawalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupplierWithdrawalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupplierWithdrawalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupplierWithdrawalUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supplierwithdrawal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupplierWithdrawalUpdate) check() error {
	if v, ok := _u.mutation.RequestNo(); ok {
		if err := supplierwithdrawal.RequestNoValidator(v); err != nil {
			return &ValidationError{Name: "request_no", err: fmt.Errorf(`ent: validator failed for field "SupplierWithdrawal.request_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := supplierwithdrawal.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "SupplierWithdrawal.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supplierwithdrawal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupplierWithdrawal.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentProofKey(); ok {
		if err := supplierwithdrawal.PaymentProofKeyValidator(v); err != nil {
			return &ValidationError{Name: "payment_proof_key", err: fmt.Errorf(`ent: validator failed for field "SupplierWithdrawal.payment_proof_key": %w`, err)}
		}
	}
	if _u.mutation.SupplierCleared() && len(_u.mutation.SupplierIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupplierWithdrawal.supplier"`)
	}
	return nil
}

func (_u *SupplierWithdrawalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supplierwithdrawal.Table, supplierwithdrawal.Columns, sqlgraph.NewFieldSpec(supplierwithdrawal.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestNo(); ok {
		_spec.SetField(supplierwithdrawal.FieldRequestNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountCny(); ok {
		_spec.SetField(supplierwithdrawal.FieldAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCny(); ok {
		_spec.AddField(supplierwithdrawal.FieldAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(supplierwithdrawal.FieldMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PayoutSnapshot(); ok {
		_spec.SetField(supplierwithdrawal.FieldPayoutSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supplierwithdrawal.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(supplierwithdrawal.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(supplierwithdrawal.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(supplierwithdrawal.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewNote(); ok {
		_spec.SetField(supplierwithdrawal.FieldReviewNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(supplierwithdrawal.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(supplierwithdrawal.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PaymentProofKey(); ok {
		_spec.SetField(supplierwithdrawal.FieldPaymentProofKey, field.TypeString, value)
	}
	if _u.mutation.PaymentProofKeyCleared() {
		_spec.ClearField(supplierwithdrawal.FieldPaymentProofKey, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(supplierwithdrawal.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(supplierwithdrawal.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supplierwithdrawal.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SupplierCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supplierwithdrawal.SupplierTable,
			Columns: []string{supplierwithdrawal.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SupplierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supplierwithdrawal.SupplierTable,
			Columns: []string{supplierwithdrawal.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplierwithdrawal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupplierWithdrawalUpdateOne is the builder for updating a single SupplierWithdrawal entity.
type SupplierWithdrawalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupplierWithdrawalMutation
}

// SetSupplierID sets the "supplier_id" field.
func (_u *SupplierWithdrawalUpdateOne) SetSupplierID(v int64) *SupplierWithdrawalUpdateOne {
	_u.mutation.SetSupplierID(v)
	return _u
}

// SetNillableSupplierID sets the "supplier_id" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdateOne) SetNillableSupplierID(v *int64) *SupplierWithdrawalUpdateOne {
	if v != nil {
		_u.SetSupplierID(*v)
	}
	return _u
}

// SetRequestNo sets the "request_no" field.
func (_u *SupplierWithdrawalUpdateOne) SetRequestNo(v string) *SupplierWithdrawalUpdateOne {
	_u.mutation.SetRequestNo(v)
	return _u
}

// SetNillableRequestNo sets the "request_no" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdateOne) SetNillableRequestNo(v *string) *SupplierWithdrawalUpdateOne {
	if v != nil {
		_u.SetRequestNo(*v)
	}
	return _u
}

// SetAmountCny sets the "amount_cny" field.
func (_u *SupplierWithdrawalUpdateOne) SetAmountCny(v float64) *SupplierWithdrawalUpdateOne {
	_u.mutation.ResetAmountCny()
	_u.mutation.SetAmountCny(v)
	return _u
}

// SetNillableAmountCny sets the "amount_cny" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdateOne) SetNillableAmountCny(v *float64) *SupplierWithdrawalUpdateOne {
	if v != nil {
		_u.SetAmountCny(*v)
	}
	return _u
}

// AddAmountCny adds value to the "amount_cny" field.
func (_u *SupplierWithdrawalUpdateOne) AddAmountCny(v float64) *SupplierWithdrawalUpdateOne {
	_u.mutation.AddAmountCny(v)
	return _u
}

// SetMethod sets the "method" field.
func (_u *SupplierWithdrawalUpdateOne) SetMethod(v supplierwithdrawal.Method) *SupplierWithdrawalUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdateOne) SetNillableMethod(v *supplierwithdrawal.Method) *SupplierWithdrawalUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPayoutSnapshot sets the "payout_snapshot" field.
func (_u *SupplierWithdrawalUpdateOne) SetPayoutSnapshot(v map[string]interface{}) *SupplierWithdrawalUpdateOne {
	_u.mutation.SetPayoutSnapshot(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupplierWithdrawalUpdateOne) SetStatus(v supplierwithdrawal.Status) *SupplierWithdrawalUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdateOne) SetNillableStatus(v *supplierwithdrawal.Status) *SupplierWithdrawalUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *SupplierWithdrawalUpdateOne) SetReviewedBy(v int64) *SupplierWithdrawalUpdateOne {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdateOne) SetNillableReviewedBy(v *int64) *SupplierWithdrawalUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *SupplierWithdrawalUpdateOne) AddReviewedBy(v int64) *SupplierWithdrawalUpdateOne {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *SupplierWithdrawalUpdateOne) ClearReviewedBy() *SupplierWithdrawalUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewNote sets the "review_note" field.
func (_u *SupplierWithdrawalUpdateOne) SetReviewNote(v string) *SupplierWithdrawalUpdateOne {
	_u.mutation.SetReviewNote(v)
	return _u
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdateOne) SetNillableReviewNote(v *string) *SupplierWithdrawalUpdateOne {
	if v != nil {
		_u.SetReviewNote(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *SupplierWithdrawalUpdateOne) SetReviewedAt(v time.Time) *SupplierWithdrawalUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdateOne) SetNillableReviewedAt(v *time.Time) *SupplierWithdrawalUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *SupplierWithdrawalUpdateOne) ClearReviewedAt() *SupplierWithdrawalUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetPaymentProofKey sets the "payment_proof_key" field.
func (_u *SupplierWithdrawalUpdateOne) SetPaymentProofKey(v string) *SupplierWithdrawalUpdateOne {
	_u.mutation.SetPaymentProofKey(v)
	return _u
}

// SetNillablePaymentProofKey sets the "payment_proof_key" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdateOne) SetNillablePaymentProofKey(v *string) *SupplierWithdrawalUpdateOne {
	if v != nil {
		_u.SetPaymentProofKey(*v)
	}
	return _u
}

// ClearPaymentProofKey clears the value of the "payment_proof_key" field.
func (_u *SupplierWithdrawalUpdateOne) ClearPaymentProofKey() *SupplierWithdrawalUpdateOne {
	_u.mutation.ClearPaymentProofKey()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *SupplierWithdrawalUpdateOne) SetPaidAt(v time.Time) *SupplierWithdrawalUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *SupplierWithdrawalUpdateOne) SetNillablePaidAt(v *time.Time) *SupplierWithdrawalUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *SupplierWithdrawalUpdateOne) ClearPaidAt() *SupplierWithdrawalUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupplierWithdrawalUpdateOne) SetUpdatedAt(v time.Time) *SupplierWithdrawalUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSupplier sets the "supplier" edge to the Supplier entity.
func (_u *SupplierWithdrawalUpdateOne) SetSupplier(v *Supplier) *SupplierWithdrawalUpdateOne {
	return _u.SetSupplierID(v.ID)
}

// Mutation returns the SupplierWithdrawalMutation object of the builder.
func (_u *SupplierWithdrawalUpdateOne) Mutation() *SupplierWithdrawalMutation {
	return _u.mutation
}

// ClearSupplier clears the "supplier" edge to the Supplier entity.
func (_u *SupplierWithdrawalUpdateOne) ClearSupplier() *SupplierWithdrawalUpdateOne {
	_u.mutation.ClearSupplier()
	return _u
}

// Where appends a list predicates to the SupplierWithdrawalUpdate builder.
func (_u *SupplierWithdrawalUpdateOne) Where(ps ...predicate.SupplierWithdrawal) *SupplierWithdrawalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupplierWithdrawalUpdateOne) Select(field string, fields ...string) *SupplierWithdrawalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupplierWithdrawal entity.
func (_u *SupplierWithdrawalUpdateOne) Save(ctx context.Context) (*SupplierWithdrawal, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupplierWithdrawalUpdateOne) SaveX(ctx context.Context) *SupplierWithdrawal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupplierWithdrawalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupplierWithdrawalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupplierWithdrawalUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supplierwithdrawal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupplierWithdrawalUpdateOne) check() error {
	if v, ok := _u.mutation.RequestNo(); ok {
		if err := supplierwithdrawal.RequestNoValidator(v); err != nil {
			return &ValidationError{Name: "request_no", err: fmt.Errorf(`ent: validator failed for field "SupplierWithdrawal.request_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := supplierwithdrawal.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "SupplierWithdrawal.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supplierwithdrawal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupplierWithdrawal.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentProofKey(); ok {
		if err := supplierwithdrawal.PaymentProofKeyValidator(v); err != nil {
			return &ValidationError{Name: "payment_proof_key", err: fmt.Errorf(`ent: validator failed for field "SupplierWithdrawal.payment_proof_key": %w`, err)}
		}
	}
	if _u.mutation.SupplierCleared() && len(_u.mutation.SupplierIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupplierWithdrawal.supplier"`)
	}
	return nil
}

func (_u *SupplierWithdrawalUpdateOne) sqlSave(ctx context.Context) (_node *SupplierWithdrawal, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supplierwithdrawal.Table, supplierwithdrawal.Columns, sqlgraph.NewFieldSpec(supplierwithdrawal.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupplierWithdrawal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supplierwithdrawal.FieldID)
		for _, f := range fields {
			if !supplierwithdrawal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supplierwithdrawal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestNo(); ok {
		_spec.SetField(supplierwithdrawal.FieldRequestNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountCny(); ok {
		_spec.SetField(supplierwithdrawal.FieldAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCny(); ok {
		_spec.AddField(supplierwithdrawal.FieldAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(supplierwithdrawal.FieldMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PayoutSnapshot(); ok {
		_spec.SetField(supplierwithdrawal.FieldPayoutSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supplierwithdrawal.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(supplierwithdrawal.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(supplierwithdrawal.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(supplierwithdrawal.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewNote(); ok {
		_spec.SetField(supplierwithdrawal.FieldReviewNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(supplierwithdrawal.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(supplierwithdrawal.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PaymentProofKey(); ok {
		_spec.SetField(supplierwithdrawal.FieldPaymentProofKey, field.TypeString, value)
	}
	if _u.mutation.PaymentProofKeyCleared() {
		_spec.ClearField(supplierwithdrawal.FieldPaymentProofKey, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(supplierwithdrawal.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(supplierwithdrawal.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supplierwithdrawal.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SupplierCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supplierwithdrawal.SupplierTable,
			Columns: []string{supplierwithdrawal.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SupplierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supplierwithdrawal.SupplierTable,
			Columns: []string{supplierwithdrawal.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupplierWithdrawal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplierwithdrawal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
