// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supplier"
	"github.com/Wei-Shaw/sub2api/ent/supplierdocument"
)

// SupplierDocumentUpdate is the builder for updating SupplierDocument entities.
type SupplierDocumentUpdate struct {
	config
	hooks    []Hook
	mutation *SupplierDocumentMutation
}

// Where appends a list predicates to the SupplierDocumentUpdate builder.
func (_u *SupplierDocumentUpdate) Where(ps ...predicate.SupplierDocument) *SupplierDocumentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSupplierID sets the "supplier_id" field.
func (_u *SupplierDocumentUpdate) SetSupplierID(v int64) *SupplierDocumentUpdate {
	_u.mutation.SetSupplierID(v)
	return _u
}

// SetNillableSupplierID sets the "supplier_id" field if the given value is not nil.
func (_u *SupplierDocumentUpdate) SetNillableSupplierID(v *int64) *SupplierDocumentUpdate {
	if v != nil {
		_u.SetSupplierID(*v)
	}
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *SupplierDocumentUpdate) SetStorageKey(v string) *SupplierDocumentUpdate {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *SupplierDocumentUpdate) SetNillableStorageKey(v *string) *SupplierDocumentUpdate {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *SupplierDocumentUpdate) SetOriginalName(v string) *SupplierDocumentUpdate {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *SupplierDocumentUpdate) SetNillableOriginalName(v *string) *SupplierDocumentUpdate {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *SupplierDocumentUpdate) SetContentType(v string) *SupplierDocumentUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *SupplierDocumentUpdate) SetNillableContentType(v *string) *SupplierDocumentUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *SupplierDocumentUpdate) SetSizeBytes(v int64) *SupplierDocumentUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *SupplierDocumentUpdate) SetNillableSizeBytes(v *int64) *SupplierDocumentUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *SupplierDocumentUpdate) AddSizeBytes(v int64) *SupplierDocumentUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetSupplier sets the "supplier" edge to the Supplier entity.
func (_u *SupplierDocumentUpdate) SetSupplier(v *Supplier) *SupplierDocumentUpdate {
	return _u.SetSupplierID(v.ID)
}

// Mutation returns the SupplierDocumentMutation object of the builder.
func (_u *SupplierDocumentUpdate) Mutation() *SupplierDocumentMutation {
	return _u.mutation
}

// ClearSupplier clears the "supplier" edge to the Supplier entity.
func (_u *SupplierDocumentUpdate) ClearSupplier() *SupplierDocumentUpdate {
	_u.mutation.ClearSupplier()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupplierDocumentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupplierDocumentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupplierDocumentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupplierDocumentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupplierDocumentUpdate) check() error {
	if v, ok := _u.mutation.StorageKey(); ok {
		if err := supplierdocument.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "SupplierDocument.storage_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalName(); ok {
		if err := supplierdocument.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "SupplierDocument.original_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := supplierdocument.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "SupplierDocument.content_type": %w`, err)}
		}
	}
	if _u.mutation.SupplierCleared() && len(_u.mutation.SupplierIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupplierDocument.supplier"`)
	}
	return nil
}

func (_u *SupplierDocumentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supplierdocument.Table, supplierdocument.Columns, sqlgraph.NewFieldSpec(supplierdocument.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(supplierdocument.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(supplierdocument.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(supplierdocument.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(supplierdocument.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(supplierdocument.FieldSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.SupplierCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supplierdocument.SupplierTable,
			Columns: []string{supplierdocument.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SupplierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supplierdocument.SupplierTable,
			Columns: []string{supplierdocument.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplierdocument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupplierDocumentUpdateOne is the builder for updating a single SupplierDocument entity.
type SupplierDocumentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupplierDocumentMutation
}

// SetSupplierID sets the "supplier_id" field.
func (_u *SupplierDocumentUpdateOne) SetSupplierID(v int64) *SupplierDocumentUpdateOne {
	_u.mutation.SetSupplierID(v)
	return _u
}

// SetNillableSupplierID sets the "supplier_id" field if the given value is not nil.
func (_u *SupplierDocumentUpdateOne) SetNillableSupplierID(v *int64) *SupplierDocumentUpdateOne {
	if v != nil {
		_u.SetSupplierID(*v)
	}
	return _u
}

// SetStorageKey sets the "storage_key" field.
func (_u *SupplierDocumentUpdateOne) SetStorageKey(v string) *SupplierDocumentUpdateOne {
	_u.mutation.SetStorageKey(v)
	return _u
}

// SetNillableStorageKey sets the "storage_key" field if the given value is not nil.
func (_u *SupplierDocumentUpdateOne) SetNillableStorageKey(v *string) *SupplierDocumentUpdateOne {
	if v != nil {
		_u.SetStorageKey(*v)
	}
	return _u
}

// SetOriginalName sets the "original_name" field.
func (_u *SupplierDocumentUpdateOne) SetOriginalName(v string) *SupplierDocumentUpdateOne {
	_u.mutation.SetOriginalName(v)
	return _u
}

// SetNillableOriginalName sets the "original_name" field if the given value is not nil.
func (_u *SupplierDocumentUpdateOne) SetNillableOriginalName(v *string) *SupplierDocumentUpdateOne {
	if v != nil {
		_u.SetOriginalName(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *SupplierDocumentUpdateOne) SetContentType(v string) *SupplierDocumentUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *SupplierDocumentUpdateOne) SetNillableContentType(v *string) *SupplierDocumentUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *SupplierDocumentUpdateOne) SetSizeBytes(v int64) *SupplierDocumentUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *SupplierDocumentUpdateOne) SetNillableSizeBytes(v *int64) *SupplierDocumentUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *SupplierDocumentUpdateOne) AddSizeBytes(v int64) *SupplierDocumentUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetSupplier sets the "supplier" edge to the Supplier entity.
func (_u *SupplierDocumentUpdateOne) SetSupplier(v *Supplier) *SupplierDocumentUpdateOne {
	return _u.SetSupplierID(v.ID)
}

// Mutation returns the SupplierDocumentMutation object of the builder.
func (_u *SupplierDocumentUpdateOne) Mutation() *SupplierDocumentMutation {
	return _u.mutation
}

// ClearSupplier clears the "supplier" edge to the Supplier entity.
func (_u *SupplierDocumentUpdateOne) ClearSupplier() *SupplierDocumentUpdateOne {
	_u.mutation.ClearSupplier()
	return _u
}

// Where appends a list predicates to the SupplierDocumentUpdate builder.
func (_u *SupplierDocumentUpdateOne) Where(ps ...predicate.SupplierDocument) *SupplierDocumentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupplierDocumentUpdateOne) Select(field string, fields ...string) *SupplierDocumentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupplierDocument entity.
func (_u *SupplierDocumentUpdateOne) Save(ctx context.Context) (*SupplierDocument, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupplierDocumentUpdateOne) SaveX(ctx context.Context) *SupplierDocument {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupplierDocumentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupplierDocumentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupplierDocumentUpdateOne) check() error {
	if v, ok := _u.mutation.StorageKey(); ok {
		if err := supplierdocument.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "SupplierDocument.storage_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalName(); ok {
		if err := supplierdocument.OriginalNameValidator(v); err != nil {
			return &ValidationError{Name: "original_name", err: fmt.Errorf(`ent: validator failed for field "SupplierDocument.original_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := supplierdocument.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "SupplierDocument.content_type": %w`, err)}
		}
	}
	if _u.mutation.SupplierCleared() && len(_u.mutation.SupplierIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupplierDocument.supplier"`)
	}
	return nil
}

func (_u *SupplierDocumentUpdateOne) sqlSave(ctx context.Context) (_node *SupplierDocument, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supplierdocument.Table, supplierdocument.Columns, sqlgraph.NewFieldSpec(supplierdocument.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupplierDocument.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supplierdocument.FieldID)
		for _, f := range fields {
			if !supplierdocument.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supplierdocument.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StorageKey(); ok {
		_spec.SetField(supplierdocument.FieldStorageKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalName(); ok {
		_spec.SetField(supplierdocument.FieldOriginalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(supplierdocument.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(supplierdocument.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(supplierdocument.FieldSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.SupplierCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supplierdocument.SupplierTable,
			Columns: []string{supplierdocument.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SupplierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supplierdocument.SupplierTable,
			Columns: []string{supplierdocument.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupplierDocument{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplierdocument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
