// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supplier"
	"github.com/Wei-Shaw/sub2api/ent/supplierdocument"
	"github.com/Wei-Shaw/sub2api/ent/supplierledger"
	"github.com/Wei-Shaw/sub2api/ent/supplierresourcerequest"
	"github.com/Wei-Shaw/sub2api/ent/supplierwithdrawal"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupplierUpdate is the builder for updating Supplier entities.
type SupplierUpdate struct {
	config
	hooks    []Hook
	mutation *SupplierMutation
}

// Where appends a list predicates to the SupplierUpdate builder.
func (_u *SupplierUpdate) Where(ps ...predicate.Supplier) *SupplierUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SupplierUpdate) SetUserID(v int64) *SupplierUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableUserID(v *int64) *SupplierUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SupplierUpdate) SetName(v string) *SupplierUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableName(v *string) *SupplierUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRelayURL sets the "relay_url" field.
func (_u *SupplierUpdate) SetRelayURL(v string) *SupplierUpdate {
	_u.mutation.SetRelayURL(v)
	return _u
}

// SetNillableRelayURL sets the "relay_url" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableRelayURL(v *string) *SupplierUpdate {
	if v != nil {
		_u.SetRelayURL(*v)
	}
	return _u
}

// SetApplicationNote sets the "application_note" field.
func (_u *SupplierUpdate) SetApplicationNote(v string) *SupplierUpdate {
	_u.mutation.SetApplicationNote(v)
	return _u
}

// SetNillableApplicationNote sets the "application_note" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableApplicationNote(v *string) *SupplierUpdate {
	if v != nil {
		_u.SetApplicationNote(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupplierUpdate) SetStatus(v supplier.Status) *SupplierUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableStatus(v *supplier.Status) *SupplierUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *SupplierUpdate) SetReviewedBy(v int64) *SupplierUpdate {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableReviewedBy(v *int64) *SupplierUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *SupplierUpdate) AddReviewedBy(v int64) *SupplierUpdate {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *SupplierUpdate) ClearReviewedBy() *SupplierUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewNote sets the "review_note" field.
func (_u *SupplierUpdate) SetReviewNote(v string) *SupplierUpdate {
	_u.mutation.SetReviewNote(v)
	return _u
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableReviewNote(v *string) *SupplierUpdate {
	if v != nil {
		_u.SetReviewNote(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *SupplierUpdate) SetReviewedAt(v time.Time) *SupplierUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableReviewedAt(v *time.Time) *SupplierUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *SupplierUpdate) ClearReviewedAt() *SupplierUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetFreezeReason sets the "freeze_reason" field.
func (_u *SupplierUpdate) SetFreezeReason(v string) *SupplierUpdate {
	_u.mutation.SetFreezeReason(v)
	return _u
}

// SetNillableFreezeReason sets the "freeze_reason" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableFreezeReason(v *string) *SupplierUpdate {
	if v != nil {
		_u.SetFreezeReason(*v)
	}
	return _u
}

// SetPendingBalanceCny sets the "pending_balance_cny" field.
func (_u *SupplierUpdate) SetPendingBalanceCny(v float64) *SupplierUpdate {
	_u.mutation.ResetPendingBalanceCny()
	_u.mutation.SetPendingBalanceCny(v)
	return _u
}

// SetNillablePendingBalanceCny sets the "pending_balance_cny" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillablePendingBalanceCny(v *float64) *SupplierUpdate {
	if v != nil {
		_u.SetPendingBalanceCny(*v)
	}
	return _u
}

// AddPendingBalanceCny adds value to the "pending_balance_cny" field.
func (_u *SupplierUpdate) AddPendingBalanceCny(v float64) *SupplierUpdate {
	_u.mutation.AddPendingBalanceCny(v)
	return _u
}

// SetAvailableBalanceCny sets the "available_balance_cny" field.
func (_u *SupplierUpdate) SetAvailableBalanceCny(v float64) *SupplierUpdate {
	_u.mutation.ResetAvailableBalanceCny()
	_u.mutation.SetAvailableBalanceCny(v)
	return _u
}

// SetNillableAvailableBalanceCny sets the "available_balance_cny" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableAvailableBalanceCny(v *float64) *SupplierUpdate {
	if v != nil {
		_u.SetAvailableBalanceCny(*v)
	}
	return _u
}

// AddAvailableBalanceCny adds value to the "available_balance_cny" field.
func (_u *SupplierUpdate) AddAvailableBalanceCny(v float64) *SupplierUpdate {
	_u.mutation.AddAvailableBalanceCny(v)
	return _u
}

// SetFrozenBalanceCny sets the "frozen_balance_cny" field.
func (_u *SupplierUpdate) SetFrozenBalanceCny(v float64) *SupplierUpdate {
	_u.mutation.ResetFrozenBalanceCny()
	_u.mutation.SetFrozenBalanceCny(v)
	return _u
}

// SetNillableFrozenBalanceCny sets the "frozen_balance_cny" field if the given value is not nil.
func (_u *SupplierUpdate) SetNillableFrozenBalanceCny(v *float64) *SupplierUpdate {
	if v != nil {
		_u.SetFrozenBalanceCny(*v)
	}
	return _u
}

// AddFrozenBalanceCny adds value to the "frozen_balance_cny" field.
func (_u *SupplierUpdate) AddFrozenBalanceCny(v float64) *SupplierUpdate {
	_u.mutation.AddFrozenBalanceCny(v)
	return _u
}

// SetPayoutProfile sets the "payout_profile" field.
func (_u *SupplierUpdate) SetPayoutProfile(v map[string]interface{}) *SupplierUpdate {
	_u.mutation.SetPayoutProfile(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupplierUpdate) SetUpdatedAt(v time.Time) *SupplierUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SupplierUpdate) SetUser(v *User) *SupplierUpdate {
	return _u.SetUserID(v.ID)
}

// AddDocumentIDs adds the "documents" edge to the SupplierDocument entity by IDs.
func (_u *SupplierUpdate) AddDocumentIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.AddDocumentIDs(ids...)
	return _u
}

// AddDocuments adds the "documents" edges to the SupplierDocument entity.
func (_u *SupplierUpdate) AddDocuments(v ...*SupplierDocument) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *SupplierUpdate) AddGroupIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *SupplierUpdate) AddGroups(v ...*Group) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *SupplierUpdate) AddAccountIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *SupplierUpdate) AddAccounts(v ...*Account) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddLedgerEntryIDs adds the "ledger_entries" edge to the SupplierLedger entity by IDs.
func (_u *SupplierUpdate) AddLedgerEntryIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.AddLedgerEntryIDs(ids...)
	return _u
}

// AddLedgerEntries adds the "ledger_entries" edges to the SupplierLedger entity.
func (_u *SupplierUpdate) AddLedgerEntries(v ...*SupplierLedger) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedgerEntryIDs(ids...)
}

// AddWithdrawalIDs adds the "withdrawals" edge to the SupplierWithdrawal entity by IDs.
func (_u *SupplierUpdate) AddWithdrawalIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.AddWithdrawalIDs(ids...)
	return _u
}

// AddWithdrawals adds the "withdrawals" edges to the SupplierWithdrawal entity.
func (_u *SupplierUpdate) AddWithdrawals(v ...*SupplierWithdrawal) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWithdrawalIDs(ids...)
}

// AddResourceRequestIDs adds the "resource_requests" edge to the SupplierResourceRequest entity by IDs.
func (_u *SupplierUpdate) AddResourceRequestIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.AddResourceRequestIDs(ids...)
	return _u
}

// AddResourceRequests adds the "resource_requests" edges to the SupplierResourceRequest entity.
func (_u *SupplierUpdate) AddResourceRequests(v ...*SupplierResourceRequest) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResourceRequestIDs(ids...)
}

// Mutation returns the SupplierMutation object of the builder.
func (_u *SupplierUpdate) Mutation() *SupplierMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SupplierUpdate) ClearUser() *SupplierUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearDocuments clears all "documents" edges to the SupplierDocument entity.
func (_u *SupplierUpdate) ClearDocuments() *SupplierUpdate {
	_u.mutation.ClearDocuments()
	return _u
}

// RemoveDocumentIDs removes the "documents" edge to SupplierDocument entities by IDs.
func (_u *SupplierUpdate) RemoveDocumentIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.RemoveDocumentIDs(ids...)
	return _u
}

// RemoveDocuments removes "documents" edges to SupplierDocument entities.
func (_u *SupplierUpdate) RemoveDocuments(v ...*SupplierDocument) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *SupplierUpdate) ClearGroups() *SupplierUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *SupplierUpdate) RemoveGroupIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *SupplierUpdate) RemoveGroups(v ...*Group) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *SupplierUpdate) ClearAccounts() *SupplierUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *SupplierUpdate) RemoveAccountIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *SupplierUpdate) RemoveAccounts(v ...*Account) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearLedgerEntries clears all "ledger_entries" edges to the SupplierLedger entity.
func (_u *SupplierUpdate) ClearLedgerEntries() *SupplierUpdate {
	_u.mutation.ClearLedgerEntries()
	return _u
}

// RemoveLedgerEntryIDs removes the "ledger_entries" edge to SupplierLedger entities by IDs.
func (_u *SupplierUpdate) RemoveLedgerEntryIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.RemoveLedgerEntryIDs(ids...)
	return _u
}

// RemoveLedgerEntries removes "ledger_entries" edges to SupplierLedger entities.
func (_u *SupplierUpdate) RemoveLedgerEntries(v ...*SupplierLedger) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedgerEntryIDs(ids...)
}

// ClearWithdrawals clears all "withdrawals" edges to the SupplierWithdrawal entity.
func (_u *SupplierUpdate) ClearWithdrawals() *SupplierUpdate {
	_u.mutation.ClearWithdrawals()
	return _u
}

// RemoveWithdrawalIDs removes the "withdrawals" edge to SupplierWithdrawal entities by IDs.
func (_u *SupplierUpdate) RemoveWithdrawalIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.RemoveWithdrawalIDs(ids...)
	return _u
}

// RemoveWithdrawals removes "withdrawals" edges to SupplierWithdrawal entities.
func (_u *SupplierUpdate) RemoveWithdrawals(v ...*SupplierWithdrawal) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWithdrawalIDs(ids...)
}

// ClearResourceRequests clears all "resource_requests" edges to the SupplierResourceRequest entity.
func (_u *SupplierUpdate) ClearResourceRequests() *SupplierUpdate {
	_u.mutation.ClearResourceRequests()
	return _u
}

// RemoveResourceRequestIDs removes the "resource_requests" edge to SupplierResourceRequest entities by IDs.
func (_u *SupplierUpdate) RemoveResourceRequestIDs(ids ...int64) *SupplierUpdate {
	_u.mutation.RemoveResourceRequestIDs(ids...)
	return _u
}

// RemoveResourceRequests removes "resource_requests" edges to SupplierResourceRequest entities.
func (_u *SupplierUpdate) RemoveResourceRequests(v ...*SupplierResourceRequest) *SupplierUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResourceRequestIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupplierUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupplierUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupplierUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupplierUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupplierUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supplier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupplierUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := supplier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Supplier.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RelayURL(); ok {
		if err := supplier.RelayURLValidator(v); err != nil {
			return &ValidationError{Name: "relay_url", err: fmt.Errorf(`ent: validator failed for field "Supplier.relay_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supplier.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Supplier.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Supplier.user"`)
	}
	return nil
}

func (_u *SupplierUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supplier.Table, supplier.Columns, sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(supplier.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RelayURL(); ok {
		_spec.SetField(supplier.FieldRelayURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApplicationNote(); ok {
		_spec.SetField(supplier.FieldApplicationNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supplier.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(supplier.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(supplier.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(supplier.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewNote(); ok {
		_spec.SetField(supplier.FieldReviewNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(supplier.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(supplier.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FreezeReason(); ok {
		_spec.SetField(supplier.FieldFreezeReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.PendingBalanceCny(); ok {
		_spec.SetField(supplier.FieldPendingBalanceCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPendingBalanceCny(); ok {
		_spec.AddField(supplier.FieldPendingBalanceCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AvailableBalanceCny(); ok {
		_spec.SetField(supplier.FieldAvailableBalanceCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAvailableBalanceCny(); ok {
		_spec.AddField(supplier.FieldAvailableBalanceCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FrozenBalanceCny(); ok {
		_spec.SetField(supplier.FieldFrozenBalanceCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrozenBalanceCny(); ok {
		_spec.AddField(supplier.FieldFrozenBalanceCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PayoutProfile(); ok {
		_spec.SetField(supplier.FieldPayoutProfile, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supplier.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supplier.UserTable,
			Columns: []string{supplier.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supplier.UserTable,
			Columns: []string{supplier.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.DocumentsTable,
			Columns: []string{supplier.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierdocument.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentsIDs(); len(nodes) > 0 && !_u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.DocumentsTable,
			Columns: []string{supplier.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierdocument.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.DocumentsTable,
			Columns: []string{supplier.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierdocument.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.GroupsTable,
			Columns: []string{supplier.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.GroupsTable,
			Columns: []string{supplier.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.GroupsTable,
			Columns: []string{supplier.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgerEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.LedgerEntriesTable,
			Columns: []string{supplier.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierledger.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedgerEntriesIDs(); len(nodes) > 0 && !_u.mutation.LedgerEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.LedgerEntriesTable,
			Columns: []string{supplier.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierledger.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.LedgerEntriesTable,
			Columns: []string{supplier.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierledger.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.WithdrawalsTable,
			Columns: []string{supplier.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierwithdrawal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWithdrawalsIDs(); len(nodes) > 0 && !_u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.WithdrawalsTable,
			Columns: []string{supplier.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierwithdrawal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.WithdrawalsTable,
			Columns: []string{supplier.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierwithdrawal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResourceRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.ResourceRequestsTable,
			Columns: []string{supplier.ResourceRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierresourcerequest.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResourceRequestsIDs(); len(nodes) > 0 && !_u.mutation.ResourceRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.ResourceRequestsTable,
			Columns: []string{supplier.ResourceRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierresourcerequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResourceRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.ResourceRequestsTable,
			Columns: []string{supplier.ResourceRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierresourcerequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupplierUpdateOne is the builder for updating a single Supplier entity.
type SupplierUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupplierMutation
}

// SetUserID sets the "user_id" field.
func (_u *SupplierUpdateOne) SetUserID(v int64) *SupplierUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableUserID(v *int64) *SupplierUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SupplierUpdateOne) SetName(v string) *SupplierUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableName(v *string) *SupplierUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRelayURL sets the "relay_url" field.
func (_u *SupplierUpdateOne) SetRelayURL(v string) *SupplierUpdateOne {
	_u.mutation.SetRelayURL(v)
	return _u
}

// SetNillableRelayURL sets the "relay_url" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableRelayURL(v *string) *SupplierUpdateOne {
	if v != nil {
		_u.SetRelayURL(*v)
	}
	return _u
}

// SetApplicationNote sets the "application_note" field.
func (_u *SupplierUpdateOne) SetApplicationNote(v string) *SupplierUpdateOne {
	_u.mutation.SetApplicationNote(v)
	return _u
}

// SetNillableApplicationNote sets the "application_note" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableApplicationNote(v *string) *SupplierUpdateOne {
	if v != nil {
		_u.SetApplicationNote(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupplierUpdateOne) SetStatus(v supplier.Status) *SupplierUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableStatus(v *supplier.Status) *SupplierUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *SupplierUpdateOne) SetReviewedBy(v int64) *SupplierUpdateOne {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableReviewedBy(v *int64) *SupplierUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *SupplierUpdateOne) AddReviewedBy(v int64) *SupplierUpdateOne {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *SupplierUpdateOne) ClearReviewedBy() *SupplierUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewNote sets the "review_note" field.
func (_u *SupplierUpdateOne) SetReviewNote(v string) *SupplierUpdateOne {
	_u.mutation.SetReviewNote(v)
	return _u
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableReviewNote(v *string) *SupplierUpdateOne {
	if v != nil {
		_u.SetReviewNote(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *SupplierUpdateOne) SetReviewedAt(v time.Time) *SupplierUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableReviewedAt(v *time.Time) *SupplierUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *SupplierUpdateOne) ClearReviewedAt() *SupplierUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetFreezeReason sets the "freeze_reason" field.
func (_u *SupplierUpdateOne) SetFreezeReason(v string) *SupplierUpdateOne {
	_u.mutation.SetFreezeReason(v)
	return _u
}

// SetNillableFreezeReason sets the "freeze_reason" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableFreezeReason(v *string) *SupplierUpdateOne {
	if v != nil {
		_u.SetFreezeReason(*v)
	}
	return _u
}

// SetPendingBalanceCny sets the "pending_balance_cny" field.
func (_u *SupplierUpdateOne) SetPendingBalanceCny(v float64) *SupplierUpdateOne {
	_u.mutation.ResetPendingBalanceCny()
	_u.mutation.SetPendingBalanceCny(v)
	return _u
}

// SetNillablePendingBalanceCny sets the "pending_balance_cny" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillablePendingBalanceCny(v *float64) *SupplierUpdateOne {
	if v != nil {
		_u.SetPendingBalanceCny(*v)
	}
	return _u
}

// AddPendingBalanceCny adds value to the "pending_balance_cny" field.
func (_u *SupplierUpdateOne) AddPendingBalanceCny(v float64) *SupplierUpdateOne {
	_u.mutation.AddPendingBalanceCny(v)
	return _u
}

// SetAvailableBalanceCny sets the "available_balance_cny" field.
func (_u *SupplierUpdateOne) SetAvailableBalanceCny(v float64) *SupplierUpdateOne {
	_u.mutation.ResetAvailableBalanceCny()
	_u.mutation.SetAvailableBalanceCny(v)
	return _u
}

// SetNillableAvailableBalanceCny sets the "available_balance_cny" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableAvailableBalanceCny(v *float64) *SupplierUpdateOne {
	if v != nil {
		_u.SetAvailableBalanceCny(*v)
	}
	return _u
}

// AddAvailableBalanceCny adds value to the "available_balance_cny" field.
func (_u *SupplierUpdateOne) AddAvailableBalanceCny(v float64) *SupplierUpdateOne {
	_u.mutation.AddAvailableBalanceCny(v)
	return _u
}

// SetFrozenBalanceCny sets the "frozen_balance_cny" field.
func (_u *SupplierUpdateOne) SetFrozenBalanceCny(v float64) *SupplierUpdateOne {
	_u.mutation.ResetFrozenBalanceCny()
	_u.mutation.SetFrozenBalanceCny(v)
	return _u
}

// SetNillableFrozenBalanceCny sets the "frozen_balance_cny" field if the given value is not nil.
func (_u *SupplierUpdateOne) SetNillableFrozenBalanceCny(v *float64) *SupplierUpdateOne {
	if v != nil {
		_u.SetFrozenBalanceCny(*v)
	}
	return _u
}

// AddFrozenBalanceCny adds value to the "frozen_balance_cny" field.
func (_u *SupplierUpdateOne) AddFrozenBalanceCny(v float64) *SupplierUpdateOne {
	_u.mutation.AddFrozenBalanceCny(v)
	return _u
}

// SetPayoutProfile sets the "payout_profile" field.
func (_u *SupplierUpdateOne) SetPayoutProfile(v map[string]interface{}) *SupplierUpdateOne {
	_u.mutation.SetPayoutProfile(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupplierUpdateOne) SetUpdatedAt(v time.Time) *SupplierUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SupplierUpdateOne) SetUser(v *User) *SupplierUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddDocumentIDs adds the "documents" edge to the SupplierDocument entity by IDs.
func (_u *SupplierUpdateOne) AddDocumentIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.AddDocumentIDs(ids...)
	return _u
}

// AddDocuments adds the "documents" edges to the SupplierDocument entity.
func (_u *SupplierUpdateOne) AddDocuments(v ...*SupplierDocument) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDocumentIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *SupplierUpdateOne) AddGroupIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *SupplierUpdateOne) AddGroups(v ...*Group) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *SupplierUpdateOne) AddAccountIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *SupplierUpdateOne) AddAccounts(v ...*Account) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddLedgerEntryIDs adds the "ledger_entries" edge to the SupplierLedger entity by IDs.
func (_u *SupplierUpdateOne) AddLedgerEntryIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.AddLedgerEntryIDs(ids...)
	return _u
}

// AddLedgerEntries adds the "ledger_entries" edges to the SupplierLedger entity.
func (_u *SupplierUpdateOne) AddLedgerEntries(v ...*SupplierLedger) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedgerEntryIDs(ids...)
}

// AddWithdrawalIDs adds the "withdrawals" edge to the SupplierWithdrawal entity by IDs.
func (_u *SupplierUpdateOne) AddWithdrawalIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.AddWithdrawalIDs(ids...)
	return _u
}

// AddWithdrawals adds the "withdrawals" edges to the SupplierWithdrawal entity.
func (_u *SupplierUpdateOne) AddWithdrawals(v ...*SupplierWithdrawal) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWithdrawalIDs(ids...)
}

// AddResourceRequestIDs adds the "resource_requests" edge to the SupplierResourceRequest entity by IDs.
func (_u *SupplierUpdateOne) AddResourceRequestIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.AddResourceRequestIDs(ids...)
	return _u
}

// AddResourceRequests adds the "resource_requests" edges to the SupplierResourceRequest entity.
func (_u *SupplierUpdateOne) AddResourceRequests(v ...*SupplierResourceRequest) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResourceRequestIDs(ids...)
}

// Mutation returns the SupplierMutation object of the builder.
func (_u *SupplierUpdateOne) Mutation() *SupplierMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SupplierUpdateOne) ClearUser() *SupplierUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearDocuments clears all "documents" edges to the SupplierDocument entity.
func (_u *SupplierUpdateOne) ClearDocuments() *SupplierUpdateOne {
	_u.mutation.ClearDocuments()
	return _u
}

// RemoveDocumentIDs removes the "documents" edge to SupplierDocument entities by IDs.
func (_u *SupplierUpdateOne) RemoveDocumentIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.RemoveDocumentIDs(ids...)
	return _u
}

// RemoveDocuments removes "documents" edges to SupplierDocument entities.
func (_u *SupplierUpdateOne) RemoveDocuments(v ...*SupplierDocument) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDocumentIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *SupplierUpdateOne) ClearGroups() *SupplierUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *SupplierUpdateOne) RemoveGroupIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *SupplierUpdateOne) RemoveGroups(v ...*Group) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *SupplierUpdateOne) ClearAccounts() *SupplierUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *SupplierUpdateOne) RemoveAccountIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *SupplierUpdateOne) RemoveAccounts(v ...*Account) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearLedgerEntries clears all "ledger_entries" edges to the SupplierLedger entity.
func (_u *SupplierUpdateOne) ClearLedgerEntries() *SupplierUpdateOne {
	_u.mutation.ClearLedgerEntries()
	return _u
}

// RemoveLedgerEntryIDs removes the "ledger_entries" edge to SupplierLedger entities by IDs.
func (_u *SupplierUpdateOne) RemoveLedgerEntryIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.RemoveLedgerEntryIDs(ids...)
	return _u
}

// RemoveLedgerEntries removes "ledger_entries" edges to SupplierLedger entities.
func (_u *SupplierUpdateOne) RemoveLedgerEntries(v ...*SupplierLedger) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedgerEntryIDs(ids...)
}

// ClearWithdrawals clears all "withdrawals" edges to the SupplierWithdrawal entity.
func (_u *SupplierUpdateOne) ClearWithdrawals() *SupplierUpdateOne {
	_u.mutation.ClearWithdrawals()
	return _u
}

// RemoveWithdrawalIDs removes the "withdrawals" edge to SupplierWithdrawal entities by IDs.
func (_u *SupplierUpdateOne) RemoveWithdrawalIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.RemoveWithdrawalIDs(ids...)
	return _u
}

// RemoveWithdrawals removes "withdrawals" edges to SupplierWithdrawal entities.
func (_u *SupplierUpdateOne) RemoveWithdrawals(v ...*SupplierWithdrawal) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWithdrawalIDs(ids...)
}

// ClearResourceRequests clears all "resource_requests" edges to the SupplierResourceRequest entity.
func (_u *SupplierUpdateOne) ClearResourceRequests() *SupplierUpdateOne {
	_u.mutation.ClearResourceRequests()
	return _u
}

// RemoveResourceRequestIDs removes the "resource_requests" edge to SupplierResourceRequest entities by IDs.
func (_u *SupplierUpdateOne) RemoveResourceRequestIDs(ids ...int64) *SupplierUpdateOne {
	_u.mutation.RemoveResourceRequestIDs(ids...)
	return _u
}

// RemoveResourceRequests removes "resource_requests" edges to SupplierResourceRequest entities.
func (_u *SupplierUpdateOne) RemoveResourceRequests(v ...*SupplierResourceRequest) *SupplierUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResourceRequestIDs(ids...)
}

// Where appends a list predicates to the SupplierUpdate builder.
func (_u *SupplierUpdateOne) Where(ps ...predicate.Supplier) *SupplierUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupplierUpdateOne) Select(field string, fields ...string) *SupplierUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Supplier entity.
func (_u *SupplierUpdateOne) Save(ctx context.Context) (*Supplier, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupplierUpdateOne) SaveX(ctx context.Context) *Supplier {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupplierUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupplierUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupplierUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supplier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupplierUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := supplier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Supplier.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RelayURL(); ok {
		if err := supplier.RelayURLValidator(v); err != nil {
			return &ValidationError{Name: "relay_url", err: fmt.Errorf(`ent: validator failed for field "Supplier.relay_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supplier.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Supplier.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Supplier.user"`)
	}
	return nil
}

func (_u *SupplierUpdateOne) sqlSave(ctx context.Context) (_node *Supplier, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supplier.Table, supplier.Columns, sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Supplier.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supplier.FieldID)
		for _, f := range fields {
			if !supplier.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supplier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(supplier.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RelayURL(); ok {
		_spec.SetField(supplier.FieldRelayURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApplicationNote(); ok {
		_spec.SetField(supplier.FieldApplicationNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supplier.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(supplier.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(supplier.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(supplier.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewNote(); ok {
		_spec.SetField(supplier.FieldReviewNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(supplier.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(supplier.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FreezeReason(); ok {
		_spec.SetField(supplier.FieldFreezeReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.PendingBalanceCny(); ok {
		_spec.SetField(supplier.FieldPendingBalanceCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPendingBalanceCny(); ok {
		_spec.AddField(supplier.FieldPendingBalanceCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AvailableBalanceCny(); ok {
		_spec.SetField(supplier.FieldAvailableBalanceCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAvailableBalanceCny(); ok {
		_spec.AddField(supplier.FieldAvailableBalanceCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FrozenBalanceCny(); ok {
		_spec.SetField(supplier.FieldFrozenBalanceCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFrozenBalanceCny(); ok {
		_spec.AddField(supplier.FieldFrozenBalanceCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PayoutProfile(); ok {
		_spec.SetField(supplier.FieldPayoutProfile, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supplier.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supplier.UserTable,
			Columns: []string{supplier.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supplier.UserTable,
			Columns: []string{supplier.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.DocumentsTable,
			Columns: []string{supplier.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierdocument.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDocumentsIDs(); len(nodes) > 0 && !_u.mutation.DocumentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.DocumentsTable,
			Columns: []string{supplier.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierdocument.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.DocumentsTable,
			Columns: []string{supplier.DocumentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierdocument.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.GroupsTable,
			Columns: []string{supplier.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.GroupsTable,
			Columns: []string{supplier.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.GroupsTable,
			Columns: []string{supplier.GroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.AccountsTable,
			Columns: []string{supplier.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgerEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.LedgerEntriesTable,
			Columns: []string{supplier.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierledger.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedgerEntriesIDs(); len(nodes) > 0 && !_u.mutation.LedgerEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.LedgerEntriesTable,
			Columns: []string{supplier.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierledger.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.LedgerEntriesTable,
			Columns: []string{supplier.LedgerEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierledger.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.WithdrawalsTable,
			Columns: []string{supplier.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierwithdrawal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWithdrawalsIDs(); len(nodes) > 0 && !_u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.WithdrawalsTable,
			Columns: []string{supplier.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierwithdrawal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.WithdrawalsTable,
			Columns: []string{supplier.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierwithdrawal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResourceRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.ResourceRequestsTable,
			Columns: []string{supplier.ResourceRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierresourcerequest.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResourceRequestsIDs(); len(nodes) > 0 && !_u.mutation.ResourceRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.ResourceRequestsTable,
			Columns: []string{supplier.ResourceRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierresourcerequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResourceRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplier.ResourceRequestsTable,
			Columns: []string{supplier.ResourceRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierresourcerequest.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Supplier{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
