// Code generated by ent, DO NOT EDIT.

package suppliermetricbucket

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the suppliermetricbucket type in the database.
	Label = "supplier_metric_bucket"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldBucketStart holds the string denoting the bucket_start field in the database.
	FieldBucketStart = "bucket_start"
	// FieldResolution holds the string denoting the resolution field in the database.
	FieldResolution = "resolution"
	// FieldRequestCount holds the string denoting the request_count field in the database.
	FieldRequestCount = "request_count"
	// FieldSuccessCount holds the string denoting the success_count field in the database.
	FieldSuccessCount = "success_count"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldCacheReadTokens holds the string denoting the cache_read_tokens field in the database.
	FieldCacheReadTokens = "cache_read_tokens"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldDurationMsSum holds the string denoting the duration_ms_sum field in the database.
	FieldDurationMsSum = "duration_ms_sum"
	// FieldFirstTokenMsSum holds the string denoting the first_token_ms_sum field in the database.
	FieldFirstTokenMsSum = "first_token_ms_sum"
	// FieldFirstTokenCount holds the string denoting the first_token_count field in the database.
	FieldFirstTokenCount = "first_token_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the suppliermetricbucket in the database.
	Table = "supplier_metric_buckets"
)

// Columns holds all SQL columns for suppliermetricbucket fields.
var Columns = []string{
	FieldID,
	FieldGroupID,
	FieldBucketStart,
	FieldResolution,
	FieldRequestCount,
	FieldSuccessCount,
	FieldTotalTokens,
	FieldCacheReadTokens,
	FieldInputTokens,
	FieldDurationMsSum,
	FieldFirstTokenMsSum,
	FieldFirstTokenCount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRequestCount holds the default value on creation for the "request_count" field.
	DefaultRequestCount int64
	// DefaultSuccessCount holds the default value on creation for the "success_count" field.
	DefaultSuccessCount int64
	// DefaultTotalTokens holds the default value on creation for the "total_tokens" field.
	DefaultTotalTokens int64
	// DefaultCacheReadTokens holds the default value on creation for the "cache_read_tokens" field.
	DefaultCacheReadTokens int64
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int64
	// DefaultDurationMsSum holds the default value on creation for the "duration_ms_sum" field.
	DefaultDurationMsSum int64
	// DefaultFirstTokenMsSum holds the default value on creation for the "first_token_ms_sum" field.
	DefaultFirstTokenMsSum int64
	// DefaultFirstTokenCount holds the default value on creation for the "first_token_count" field.
	DefaultFirstTokenCount int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Resolution defines the type for the "resolution" enum field.
type Resolution string

// Resolution values.
const (
	Resolution5m Resolution = "5m"
	Resolution1h Resolution = "1h"
	Resolution1d Resolution = "1d"
)

func (r Resolution) String() string {
	return string(r)
}

// ResolutionValidator is a validator for the "resolution" field enum values. It is called by the builders before save.
func ResolutionValidator(r Resolution) error {
	switch r {
	case Resolution5m, Resolution1h, Resolution1d:
		return nil
	default:
		return fmt.Errorf("suppliermetricbucket: invalid enum value for resolution field: %q", r)
	}
}

// OrderOption defines the ordering options for the SupplierMetricBucket queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByBucketStart orders the results by the bucket_start field.
func ByBucketStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucketStart, opts...).ToFunc()
}

// ByResolution orders the results by the resolution field.
func ByResolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolution, opts...).ToFunc()
}

// ByRequestCount orders the results by the request_count field.
func ByRequestCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestCount, opts...).ToFunc()
}

// BySuccessCount orders the results by the success_count field.
func BySuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessCount, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByCacheReadTokens orders the results by the cache_read_tokens field.
func ByCacheReadTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadTokens, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByDurationMsSum orders the results by the duration_ms_sum field.
func ByDurationMsSum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMsSum, opts...).ToFunc()
}

// ByFirstTokenMsSum orders the results by the first_token_ms_sum field.
func ByFirstTokenMsSum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstTokenMsSum, opts...).ToFunc()
}

// ByFirstTokenCount orders the results by the first_token_count field.
func ByFirstTokenCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstTokenCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
