// Code generated by ent, DO NOT EDIT.

package suppliermetricbucket

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldGroupID, v))
}

// BucketStart applies equality check predicate on the "bucket_start" field. It's identical to BucketStartEQ.
func BucketStart(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldBucketStart, v))
}

// RequestCount applies equality check predicate on the "request_count" field. It's identical to RequestCountEQ.
func RequestCount(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldRequestCount, v))
}

// SuccessCount applies equality check predicate on the "success_count" field. It's identical to SuccessCountEQ.
func SuccessCount(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldSuccessCount, v))
}

// TotalTokens applies equality check predicate on the "total_tokens" field. It's identical to TotalTokensEQ.
func TotalTokens(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldTotalTokens, v))
}

// CacheReadTokens applies equality check predicate on the "cache_read_tokens" field. It's identical to CacheReadTokensEQ.
func CacheReadTokens(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldCacheReadTokens, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldInputTokens, v))
}

// DurationMsSum applies equality check predicate on the "duration_ms_sum" field. It's identical to DurationMsSumEQ.
func DurationMsSum(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldDurationMsSum, v))
}

// FirstTokenMsSum applies equality check predicate on the "first_token_ms_sum" field. It's identical to FirstTokenMsSumEQ.
func FirstTokenMsSum(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldFirstTokenMsSum, v))
}

// FirstTokenCount applies equality check predicate on the "first_token_count" field. It's identical to FirstTokenCountEQ.
func FirstTokenCount(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldFirstTokenCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldGroupID, v))
}

// BucketStartEQ applies the EQ predicate on the "bucket_start" field.
func BucketStartEQ(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldBucketStart, v))
}

// BucketStartNEQ applies the NEQ predicate on the "bucket_start" field.
func BucketStartNEQ(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldBucketStart, v))
}

// BucketStartIn applies the In predicate on the "bucket_start" field.
func BucketStartIn(vs ...time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldBucketStart, vs...))
}

// BucketStartNotIn applies the NotIn predicate on the "bucket_start" field.
func BucketStartNotIn(vs ...time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldBucketStart, vs...))
}

// BucketStartGT applies the GT predicate on the "bucket_start" field.
func BucketStartGT(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldBucketStart, v))
}

// BucketStartGTE applies the GTE predicate on the "bucket_start" field.
func BucketStartGTE(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldBucketStart, v))
}

// BucketStartLT applies the LT predicate on the "bucket_start" field.
func BucketStartLT(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldBucketStart, v))
}

// BucketStartLTE applies the LTE predicate on the "bucket_start" field.
func BucketStartLTE(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldBucketStart, v))
}

// ResolutionEQ applies the EQ predicate on the "resolution" field.
func ResolutionEQ(v Resolution) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldResolution, v))
}

// ResolutionNEQ applies the NEQ predicate on the "resolution" field.
func ResolutionNEQ(v Resolution) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldResolution, v))
}

// ResolutionIn applies the In predicate on the "resolution" field.
func ResolutionIn(vs ...Resolution) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldResolution, vs...))
}

// ResolutionNotIn applies the NotIn predicate on the "resolution" field.
func ResolutionNotIn(vs ...Resolution) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldResolution, vs...))
}

// RequestCountEQ applies the EQ predicate on the "request_count" field.
func RequestCountEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldRequestCount, v))
}

// RequestCountNEQ applies the NEQ predicate on the "request_count" field.
func RequestCountNEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldRequestCount, v))
}

// RequestCountIn applies the In predicate on the "request_count" field.
func RequestCountIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldRequestCount, vs...))
}

// RequestCountNotIn applies the NotIn predicate on the "request_count" field.
func RequestCountNotIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldRequestCount, vs...))
}

// RequestCountGT applies the GT predicate on the "request_count" field.
func RequestCountGT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldRequestCount, v))
}

// RequestCountGTE applies the GTE predicate on the "request_count" field.
func RequestCountGTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldRequestCount, v))
}

// RequestCountLT applies the LT predicate on the "request_count" field.
func RequestCountLT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldRequestCount, v))
}

// RequestCountLTE applies the LTE predicate on the "request_count" field.
func RequestCountLTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldRequestCount, v))
}

// SuccessCountEQ applies the EQ predicate on the "success_count" field.
func SuccessCountEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldSuccessCount, v))
}

// SuccessCountNEQ applies the NEQ predicate on the "success_count" field.
func SuccessCountNEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldSuccessCount, v))
}

// SuccessCountIn applies the In predicate on the "success_count" field.
func SuccessCountIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldSuccessCount, vs...))
}

// SuccessCountNotIn applies the NotIn predicate on the "success_count" field.
func SuccessCountNotIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldSuccessCount, vs...))
}

// SuccessCountGT applies the GT predicate on the "success_count" field.
func SuccessCountGT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldSuccessCount, v))
}

// SuccessCountGTE applies the GTE predicate on the "success_count" field.
func SuccessCountGTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldSuccessCount, v))
}

// SuccessCountLT applies the LT predicate on the "success_count" field.
func SuccessCountLT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldSuccessCount, v))
}

// SuccessCountLTE applies the LTE predicate on the "success_count" field.
func SuccessCountLTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldSuccessCount, v))
}

// TotalTokensEQ applies the EQ predicate on the "total_tokens" field.
func TotalTokensEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalTokensNEQ applies the NEQ predicate on the "total_tokens" field.
func TotalTokensNEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldTotalTokens, v))
}

// TotalTokensIn applies the In predicate on the "total_tokens" field.
func TotalTokensIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldTotalTokens, vs...))
}

// TotalTokensNotIn applies the NotIn predicate on the "total_tokens" field.
func TotalTokensNotIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldTotalTokens, vs...))
}

// TotalTokensGT applies the GT predicate on the "total_tokens" field.
func TotalTokensGT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldTotalTokens, v))
}

// TotalTokensGTE applies the GTE predicate on the "total_tokens" field.
func TotalTokensGTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldTotalTokens, v))
}

// TotalTokensLT applies the LT predicate on the "total_tokens" field.
func TotalTokensLT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldTotalTokens, v))
}

// TotalTokensLTE applies the LTE predicate on the "total_tokens" field.
func TotalTokensLTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldTotalTokens, v))
}

// CacheReadTokensEQ applies the EQ predicate on the "cache_read_tokens" field.
func CacheReadTokensEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensNEQ applies the NEQ predicate on the "cache_read_tokens" field.
func CacheReadTokensNEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldCacheReadTokens, v))
}

// CacheReadTokensIn applies the In predicate on the "cache_read_tokens" field.
func CacheReadTokensIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensNotIn applies the NotIn predicate on the "cache_read_tokens" field.
func CacheReadTokensNotIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldCacheReadTokens, vs...))
}

// CacheReadTokensGT applies the GT predicate on the "cache_read_tokens" field.
func CacheReadTokensGT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldCacheReadTokens, v))
}

// CacheReadTokensGTE applies the GTE predicate on the "cache_read_tokens" field.
func CacheReadTokensGTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldCacheReadTokens, v))
}

// CacheReadTokensLT applies the LT predicate on the "cache_read_tokens" field.
func CacheReadTokensLT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldCacheReadTokens, v))
}

// CacheReadTokensLTE applies the LTE predicate on the "cache_read_tokens" field.
func CacheReadTokensLTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldCacheReadTokens, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldInputTokens, v))
}

// DurationMsSumEQ applies the EQ predicate on the "duration_ms_sum" field.
func DurationMsSumEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldDurationMsSum, v))
}

// DurationMsSumNEQ applies the NEQ predicate on the "duration_ms_sum" field.
func DurationMsSumNEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldDurationMsSum, v))
}

// DurationMsSumIn applies the In predicate on the "duration_ms_sum" field.
func DurationMsSumIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldDurationMsSum, vs...))
}

// DurationMsSumNotIn applies the NotIn predicate on the "duration_ms_sum" field.
func DurationMsSumNotIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldDurationMsSum, vs...))
}

// DurationMsSumGT applies the GT predicate on the "duration_ms_sum" field.
func DurationMsSumGT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldDurationMsSum, v))
}

// DurationMsSumGTE applies the GTE predicate on the "duration_ms_sum" field.
func DurationMsSumGTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldDurationMsSum, v))
}

// DurationMsSumLT applies the LT predicate on the "duration_ms_sum" field.
func DurationMsSumLT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldDurationMsSum, v))
}

// DurationMsSumLTE applies the LTE predicate on the "duration_ms_sum" field.
func DurationMsSumLTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldDurationMsSum, v))
}

// FirstTokenMsSumEQ applies the EQ predicate on the "first_token_ms_sum" field.
func FirstTokenMsSumEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldFirstTokenMsSum, v))
}

// FirstTokenMsSumNEQ applies the NEQ predicate on the "first_token_ms_sum" field.
func FirstTokenMsSumNEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldFirstTokenMsSum, v))
}

// FirstTokenMsSumIn applies the In predicate on the "first_token_ms_sum" field.
func FirstTokenMsSumIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldFirstTokenMsSum, vs...))
}

// FirstTokenMsSumNotIn applies the NotIn predicate on the "first_token_ms_sum" field.
func FirstTokenMsSumNotIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldFirstTokenMsSum, vs...))
}

// FirstTokenMsSumGT applies the GT predicate on the "first_token_ms_sum" field.
func FirstTokenMsSumGT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldFirstTokenMsSum, v))
}

// FirstTokenMsSumGTE applies the GTE predicate on the "first_token_ms_sum" field.
func FirstTokenMsSumGTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldFirstTokenMsSum, v))
}

// FirstTokenMsSumLT applies the LT predicate on the "first_token_ms_sum" field.
func FirstTokenMsSumLT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldFirstTokenMsSum, v))
}

// FirstTokenMsSumLTE applies the LTE predicate on the "first_token_ms_sum" field.
func FirstTokenMsSumLTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldFirstTokenMsSum, v))
}

// FirstTokenCountEQ applies the EQ predicate on the "first_token_count" field.
func FirstTokenCountEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldFirstTokenCount, v))
}

// FirstTokenCountNEQ applies the NEQ predicate on the "first_token_count" field.
func FirstTokenCountNEQ(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldFirstTokenCount, v))
}

// FirstTokenCountIn applies the In predicate on the "first_token_count" field.
func FirstTokenCountIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldFirstTokenCount, vs...))
}

// FirstTokenCountNotIn applies the NotIn predicate on the "first_token_count" field.
func FirstTokenCountNotIn(vs ...int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldFirstTokenCount, vs...))
}

// FirstTokenCountGT applies the GT predicate on the "first_token_count" field.
func FirstTokenCountGT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldFirstTokenCount, v))
}

// FirstTokenCountGTE applies the GTE predicate on the "first_token_count" field.
func FirstTokenCountGTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldFirstTokenCount, v))
}

// FirstTokenCountLT applies the LT predicate on the "first_token_count" field.
func FirstTokenCountLT(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldFirstTokenCount, v))
}

// FirstTokenCountLTE applies the LTE predicate on the "first_token_count" field.
func FirstTokenCountLTE(v int64) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldFirstTokenCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupplierMetricBucket) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupplierMetricBucket) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupplierMetricBucket) predicate.SupplierMetricBucket {
	return predicate.SupplierMetricBucket(sql.NotPredicates(p))
}
