// Code generated by ent, DO NOT EDIT.

package supplier

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the supplier type in the database.
	Label = "supplier"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRelayURL holds the string denoting the relay_url field in the database.
	FieldRelayURL = "relay_url"
	// FieldApplicationNote holds the string denoting the application_note field in the database.
	FieldApplicationNote = "application_note"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReviewedBy holds the string denoting the reviewed_by field in the database.
	FieldReviewedBy = "reviewed_by"
	// FieldReviewNote holds the string denoting the review_note field in the database.
	FieldReviewNote = "review_note"
	// FieldReviewedAt holds the string denoting the reviewed_at field in the database.
	FieldReviewedAt = "reviewed_at"
	// FieldFreezeReason holds the string denoting the freeze_reason field in the database.
	FieldFreezeReason = "freeze_reason"
	// FieldPendingBalanceCny holds the string denoting the pending_balance_cny field in the database.
	FieldPendingBalanceCny = "pending_balance_cny"
	// FieldAvailableBalanceCny holds the string denoting the available_balance_cny field in the database.
	FieldAvailableBalanceCny = "available_balance_cny"
	// FieldFrozenBalanceCny holds the string denoting the frozen_balance_cny field in the database.
	FieldFrozenBalanceCny = "frozen_balance_cny"
	// FieldPayoutProfile holds the string denoting the payout_profile field in the database.
	FieldPayoutProfile = "payout_profile"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeDocuments holds the string denoting the documents edge name in mutations.
	EdgeDocuments = "documents"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// EdgeLedgerEntries holds the string denoting the ledger_entries edge name in mutations.
	EdgeLedgerEntries = "ledger_entries"
	// EdgeWithdrawals holds the string denoting the withdrawals edge name in mutations.
	EdgeWithdrawals = "withdrawals"
	// EdgeResourceRequests holds the string denoting the resource_requests edge name in mutations.
	EdgeResourceRequests = "resource_requests"
	// Table holds the table name of the supplier in the database.
	Table = "suppliers"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "suppliers"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// DocumentsTable is the table that holds the documents relation/edge.
	DocumentsTable = "supplier_documents"
	// DocumentsInverseTable is the table name for the SupplierDocument entity.
	// It exists in this package in order to avoid circular dependency with the "supplierdocument" package.
	DocumentsInverseTable = "supplier_documents"
	// DocumentsColumn is the table column denoting the documents relation/edge.
	DocumentsColumn = "supplier_id"
	// GroupsTable is the table that holds the groups relation/edge.
	GroupsTable = "groups"
	// GroupsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupsInverseTable = "groups"
	// GroupsColumn is the table column denoting the groups relation/edge.
	GroupsColumn = "supplier_id"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "accounts"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "supplier_id"
	// LedgerEntriesTable is the table that holds the ledger_entries relation/edge.
	LedgerEntriesTable = "supplier_ledgers"
	// LedgerEntriesInverseTable is the table name for the SupplierLedger entity.
	// It exists in this package in order to avoid circular dependency with the "supplierledger" package.
	LedgerEntriesInverseTable = "supplier_ledgers"
	// LedgerEntriesColumn is the table column denoting the ledger_entries relation/edge.
	LedgerEntriesColumn = "supplier_id"
	// WithdrawalsTable is the table that holds the withdrawals relation/edge.
	WithdrawalsTable = "supplier_withdrawals"
	// WithdrawalsInverseTable is the table name for the SupplierWithdrawal entity.
	// It exists in this package in order to avoid circular dependency with the "supplierwithdrawal" package.
	WithdrawalsInverseTable = "supplier_withdrawals"
	// WithdrawalsColumn is the table column denoting the withdrawals relation/edge.
	WithdrawalsColumn = "supplier_id"
	// ResourceRequestsTable is the table that holds the resource_requests relation/edge.
	ResourceRequestsTable = "supplier_resource_requests"
	// ResourceRequestsInverseTable is the table name for the SupplierResourceRequest entity.
	// It exists in this package in order to avoid circular dependency with the "supplierresourcerequest" package.
	ResourceRequestsInverseTable = "supplier_resource_requests"
	// ResourceRequestsColumn is the table column denoting the resource_requests relation/edge.
	ResourceRequestsColumn = "supplier_id"
)

// Columns holds all SQL columns for supplier fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldName,
	FieldRelayURL,
	FieldApplicationNote,
	FieldStatus,
	FieldReviewedBy,
	FieldReviewNote,
	FieldReviewedAt,
	FieldFreezeReason,
	FieldPendingBalanceCny,
	FieldAvailableBalanceCny,
	FieldFrozenBalanceCny,
	FieldPayoutProfile,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// RelayURLValidator is a validator for the "relay_url" field. It is called by the builders before save.
	RelayURLValidator func(string) error
	// DefaultApplicationNote holds the default value on creation for the "application_note" field.
	DefaultApplicationNote string
	// DefaultReviewNote holds the default value on creation for the "review_note" field.
	DefaultReviewNote string
	// DefaultFreezeReason holds the default value on creation for the "freeze_reason" field.
	DefaultFreezeReason string
	// DefaultPendingBalanceCny holds the default value on creation for the "pending_balance_cny" field.
	DefaultPendingBalanceCny float64
	// DefaultAvailableBalanceCny holds the default value on creation for the "available_balance_cny" field.
	DefaultAvailableBalanceCny float64
	// DefaultFrozenBalanceCny holds the default value on creation for the "frozen_balance_cny" field.
	DefaultFrozenBalanceCny float64
	// DefaultPayoutProfile holds the default value on creation for the "payout_profile" field.
	DefaultPayoutProfile map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending  Status = "pending"
	StatusApproved Status = "approved"
	StatusRejected Status = "rejected"
	StatusFrozen   Status = "frozen"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusApproved, StatusRejected, StatusFrozen:
		return nil
	default:
		return fmt.Errorf("supplier: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Supplier queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByRelayURL orders the results by the relay_url field.
func ByRelayURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelayURL, opts...).ToFunc()
}

// ByApplicationNote orders the results by the application_note field.
func ByApplicationNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplicationNote, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReviewedBy orders the results by the reviewed_by field.
func ByReviewedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedBy, opts...).ToFunc()
}

// ByReviewNote orders the results by the review_note field.
func ByReviewNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewNote, opts...).ToFunc()
}

// ByReviewedAt orders the results by the reviewed_at field.
func ByReviewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewedAt, opts...).ToFunc()
}

// ByFreezeReason orders the results by the freeze_reason field.
func ByFreezeReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFreezeReason, opts...).ToFunc()
}

// ByPendingBalanceCny orders the results by the pending_balance_cny field.
func ByPendingBalanceCny(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPendingBalanceCny, opts...).ToFunc()
}

// ByAvailableBalanceCny orders the results by the available_balance_cny field.
func ByAvailableBalanceCny(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableBalanceCny, opts...).ToFunc()
}

// ByFrozenBalanceCny orders the results by the frozen_balance_cny field.
func ByFrozenBalanceCny(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFrozenBalanceCny, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByDocumentsCount orders the results by documents count.
func ByDocumentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDocumentsStep(), opts...)
	}
}

// ByDocuments orders the results by documents terms.
func ByDocuments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDocumentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGroupsCount orders the results by groups count.
func ByGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupsStep(), opts...)
	}
}

// ByGroups orders the results by groups terms.
func ByGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLedgerEntriesCount orders the results by ledger_entries count.
func ByLedgerEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLedgerEntriesStep(), opts...)
	}
}

// ByLedgerEntries orders the results by ledger_entries terms.
func ByLedgerEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLedgerEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWithdrawalsCount orders the results by withdrawals count.
func ByWithdrawalsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWithdrawalsStep(), opts...)
	}
}

// ByWithdrawals orders the results by withdrawals terms.
func ByWithdrawals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWithdrawalsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByResourceRequestsCount orders the results by resource_requests count.
func ByResourceRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newResourceRequestsStep(), opts...)
	}
}

// ByResourceRequests orders the results by resource_requests terms.
func ByResourceRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResourceRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
func newDocumentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DocumentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DocumentsTable, DocumentsColumn),
	)
}
func newGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
	)
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
	)
}
func newLedgerEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LedgerEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LedgerEntriesTable, LedgerEntriesColumn),
	)
}
func newWithdrawalsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WithdrawalsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, WithdrawalsTable, WithdrawalsColumn),
	)
}
func newResourceRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResourceRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ResourceRequestsTable, ResourceRequestsColumn),
	)
}
