// Code generated by ent, DO NOT EDIT.

package supplier

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldName, v))
}

// RelayURL applies equality check predicate on the "relay_url" field. It's identical to RelayURLEQ.
func RelayURL(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldRelayURL, v))
}

// ApplicationNote applies equality check predicate on the "application_note" field. It's identical to ApplicationNoteEQ.
func ApplicationNote(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldApplicationNote, v))
}

// ReviewedBy applies equality check predicate on the "reviewed_by" field. It's identical to ReviewedByEQ.
func ReviewedBy(v int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewNote applies equality check predicate on the "review_note" field. It's identical to ReviewNoteEQ.
func ReviewNote(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldReviewNote, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldReviewedAt, v))
}

// FreezeReason applies equality check predicate on the "freeze_reason" field. It's identical to FreezeReasonEQ.
func FreezeReason(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldFreezeReason, v))
}

// PendingBalanceCny applies equality check predicate on the "pending_balance_cny" field. It's identical to PendingBalanceCnyEQ.
func PendingBalanceCny(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldPendingBalanceCny, v))
}

// AvailableBalanceCny applies equality check predicate on the "available_balance_cny" field. It's identical to AvailableBalanceCnyEQ.
func AvailableBalanceCny(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldAvailableBalanceCny, v))
}

// FrozenBalanceCny applies equality check predicate on the "frozen_balance_cny" field. It's identical to FrozenBalanceCnyEQ.
func FrozenBalanceCny(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldFrozenBalanceCny, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldUserID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContainsFold(FieldName, v))
}

// RelayURLEQ applies the EQ predicate on the "relay_url" field.
func RelayURLEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldRelayURL, v))
}

// RelayURLNEQ applies the NEQ predicate on the "relay_url" field.
func RelayURLNEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldRelayURL, v))
}

// RelayURLIn applies the In predicate on the "relay_url" field.
func RelayURLIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldRelayURL, vs...))
}

// RelayURLNotIn applies the NotIn predicate on the "relay_url" field.
func RelayURLNotIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldRelayURL, vs...))
}

// RelayURLGT applies the GT predicate on the "relay_url" field.
func RelayURLGT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldRelayURL, v))
}

// RelayURLGTE applies the GTE predicate on the "relay_url" field.
func RelayURLGTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldRelayURL, v))
}

// RelayURLLT applies the LT predicate on the "relay_url" field.
func RelayURLLT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldRelayURL, v))
}

// RelayURLLTE applies the LTE predicate on the "relay_url" field.
func RelayURLLTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldRelayURL, v))
}

// RelayURLContains applies the Contains predicate on the "relay_url" field.
func RelayURLContains(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContains(FieldRelayURL, v))
}

// RelayURLHasPrefix applies the HasPrefix predicate on the "relay_url" field.
func RelayURLHasPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasPrefix(FieldRelayURL, v))
}

// RelayURLHasSuffix applies the HasSuffix predicate on the "relay_url" field.
func RelayURLHasSuffix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasSuffix(FieldRelayURL, v))
}

// RelayURLEqualFold applies the EqualFold predicate on the "relay_url" field.
func RelayURLEqualFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEqualFold(FieldRelayURL, v))
}

// RelayURLContainsFold applies the ContainsFold predicate on the "relay_url" field.
func RelayURLContainsFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContainsFold(FieldRelayURL, v))
}

// ApplicationNoteEQ applies the EQ predicate on the "application_note" field.
func ApplicationNoteEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldApplicationNote, v))
}

// ApplicationNoteNEQ applies the NEQ predicate on the "application_note" field.
func ApplicationNoteNEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldApplicationNote, v))
}

// ApplicationNoteIn applies the In predicate on the "application_note" field.
func ApplicationNoteIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldApplicationNote, vs...))
}

// ApplicationNoteNotIn applies the NotIn predicate on the "application_note" field.
func ApplicationNoteNotIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldApplicationNote, vs...))
}

// ApplicationNoteGT applies the GT predicate on the "application_note" field.
func ApplicationNoteGT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldApplicationNote, v))
}

// ApplicationNoteGTE applies the GTE predicate on the "application_note" field.
func ApplicationNoteGTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldApplicationNote, v))
}

// ApplicationNoteLT applies the LT predicate on the "application_note" field.
func ApplicationNoteLT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldApplicationNote, v))
}

// ApplicationNoteLTE applies the LTE predicate on the "application_note" field.
func ApplicationNoteLTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldApplicationNote, v))
}

// ApplicationNoteContains applies the Contains predicate on the "application_note" field.
func ApplicationNoteContains(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContains(FieldApplicationNote, v))
}

// ApplicationNoteHasPrefix applies the HasPrefix predicate on the "application_note" field.
func ApplicationNoteHasPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasPrefix(FieldApplicationNote, v))
}

// ApplicationNoteHasSuffix applies the HasSuffix predicate on the "application_note" field.
func ApplicationNoteHasSuffix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasSuffix(FieldApplicationNote, v))
}

// ApplicationNoteEqualFold applies the EqualFold predicate on the "application_note" field.
func ApplicationNoteEqualFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEqualFold(FieldApplicationNote, v))
}

// ApplicationNoteContainsFold applies the ContainsFold predicate on the "application_note" field.
func ApplicationNoteContainsFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContainsFold(FieldApplicationNote, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldStatus, vs...))
}

// ReviewedByEQ applies the EQ predicate on the "reviewed_by" field.
func ReviewedByEQ(v int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedByNEQ applies the NEQ predicate on the "reviewed_by" field.
func ReviewedByNEQ(v int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldReviewedBy, v))
}

// ReviewedByIn applies the In predicate on the "reviewed_by" field.
func ReviewedByIn(vs ...int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldReviewedBy, vs...))
}

// ReviewedByNotIn applies the NotIn predicate on the "reviewed_by" field.
func ReviewedByNotIn(vs ...int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldReviewedBy, vs...))
}

// ReviewedByGT applies the GT predicate on the "reviewed_by" field.
func ReviewedByGT(v int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldReviewedBy, v))
}

// ReviewedByGTE applies the GTE predicate on the "reviewed_by" field.
func ReviewedByGTE(v int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldReviewedBy, v))
}

// ReviewedByLT applies the LT predicate on the "reviewed_by" field.
func ReviewedByLT(v int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldReviewedBy, v))
}

// ReviewedByLTE applies the LTE predicate on the "reviewed_by" field.
func ReviewedByLTE(v int64) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldReviewedBy, v))
}

// ReviewedByIsNil applies the IsNil predicate on the "reviewed_by" field.
func ReviewedByIsNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldIsNull(FieldReviewedBy))
}

// ReviewedByNotNil applies the NotNil predicate on the "reviewed_by" field.
func ReviewedByNotNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldNotNull(FieldReviewedBy))
}

// ReviewNoteEQ applies the EQ predicate on the "review_note" field.
func ReviewNoteEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldReviewNote, v))
}

// ReviewNoteNEQ applies the NEQ predicate on the "review_note" field.
func ReviewNoteNEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldReviewNote, v))
}

// ReviewNoteIn applies the In predicate on the "review_note" field.
func ReviewNoteIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldReviewNote, vs...))
}

// ReviewNoteNotIn applies the NotIn predicate on the "review_note" field.
func ReviewNoteNotIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldReviewNote, vs...))
}

// ReviewNoteGT applies the GT predicate on the "review_note" field.
func ReviewNoteGT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldReviewNote, v))
}

// ReviewNoteGTE applies the GTE predicate on the "review_note" field.
func ReviewNoteGTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldReviewNote, v))
}

// ReviewNoteLT applies the LT predicate on the "review_note" field.
func ReviewNoteLT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldReviewNote, v))
}

// ReviewNoteLTE applies the LTE predicate on the "review_note" field.
func ReviewNoteLTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldReviewNote, v))
}

// ReviewNoteContains applies the Contains predicate on the "review_note" field.
func ReviewNoteContains(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContains(FieldReviewNote, v))
}

// ReviewNoteHasPrefix applies the HasPrefix predicate on the "review_note" field.
func ReviewNoteHasPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasPrefix(FieldReviewNote, v))
}

// ReviewNoteHasSuffix applies the HasSuffix predicate on the "review_note" field.
func ReviewNoteHasSuffix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasSuffix(FieldReviewNote, v))
}

// ReviewNoteEqualFold applies the EqualFold predicate on the "review_note" field.
func ReviewNoteEqualFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEqualFold(FieldReviewNote, v))
}

// ReviewNoteContainsFold applies the ContainsFold predicate on the "review_note" field.
func ReviewNoteContainsFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContainsFold(FieldReviewNote, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.Supplier {
	return predicate.Supplier(sql.FieldNotNull(FieldReviewedAt))
}

// FreezeReasonEQ applies the EQ predicate on the "freeze_reason" field.
func FreezeReasonEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldFreezeReason, v))
}

// FreezeReasonNEQ applies the NEQ predicate on the "freeze_reason" field.
func FreezeReasonNEQ(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldFreezeReason, v))
}

// FreezeReasonIn applies the In predicate on the "freeze_reason" field.
func FreezeReasonIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldFreezeReason, vs...))
}

// FreezeReasonNotIn applies the NotIn predicate on the "freeze_reason" field.
func FreezeReasonNotIn(vs ...string) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldFreezeReason, vs...))
}

// FreezeReasonGT applies the GT predicate on the "freeze_reason" field.
func FreezeReasonGT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldFreezeReason, v))
}

// FreezeReasonGTE applies the GTE predicate on the "freeze_reason" field.
func FreezeReasonGTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldFreezeReason, v))
}

// FreezeReasonLT applies the LT predicate on the "freeze_reason" field.
func FreezeReasonLT(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldFreezeReason, v))
}

// FreezeReasonLTE applies the LTE predicate on the "freeze_reason" field.
func FreezeReasonLTE(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldFreezeReason, v))
}

// FreezeReasonContains applies the Contains predicate on the "freeze_reason" field.
func FreezeReasonContains(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContains(FieldFreezeReason, v))
}

// FreezeReasonHasPrefix applies the HasPrefix predicate on the "freeze_reason" field.
func FreezeReasonHasPrefix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasPrefix(FieldFreezeReason, v))
}

// FreezeReasonHasSuffix applies the HasSuffix predicate on the "freeze_reason" field.
func FreezeReasonHasSuffix(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldHasSuffix(FieldFreezeReason, v))
}

// FreezeReasonEqualFold applies the EqualFold predicate on the "freeze_reason" field.
func FreezeReasonEqualFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldEqualFold(FieldFreezeReason, v))
}

// FreezeReasonContainsFold applies the ContainsFold predicate on the "freeze_reason" field.
func FreezeReasonContainsFold(v string) predicate.Supplier {
	return predicate.Supplier(sql.FieldContainsFold(FieldFreezeReason, v))
}

// PendingBalanceCnyEQ applies the EQ predicate on the "pending_balance_cny" field.
func PendingBalanceCnyEQ(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldPendingBalanceCny, v))
}

// PendingBalanceCnyNEQ applies the NEQ predicate on the "pending_balance_cny" field.
func PendingBalanceCnyNEQ(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldPendingBalanceCny, v))
}

// PendingBalanceCnyIn applies the In predicate on the "pending_balance_cny" field.
func PendingBalanceCnyIn(vs ...float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldPendingBalanceCny, vs...))
}

// PendingBalanceCnyNotIn applies the NotIn predicate on the "pending_balance_cny" field.
func PendingBalanceCnyNotIn(vs ...float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldPendingBalanceCny, vs...))
}

// PendingBalanceCnyGT applies the GT predicate on the "pending_balance_cny" field.
func PendingBalanceCnyGT(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldPendingBalanceCny, v))
}

// PendingBalanceCnyGTE applies the GTE predicate on the "pending_balance_cny" field.
func PendingBalanceCnyGTE(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldPendingBalanceCny, v))
}

// PendingBalanceCnyLT applies the LT predicate on the "pending_balance_cny" field.
func PendingBalanceCnyLT(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldPendingBalanceCny, v))
}

// PendingBalanceCnyLTE applies the LTE predicate on the "pending_balance_cny" field.
func PendingBalanceCnyLTE(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldPendingBalanceCny, v))
}

// AvailableBalanceCnyEQ applies the EQ predicate on the "available_balance_cny" field.
func AvailableBalanceCnyEQ(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldAvailableBalanceCny, v))
}

// AvailableBalanceCnyNEQ applies the NEQ predicate on the "available_balance_cny" field.
func AvailableBalanceCnyNEQ(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldAvailableBalanceCny, v))
}

// AvailableBalanceCnyIn applies the In predicate on the "available_balance_cny" field.
func AvailableBalanceCnyIn(vs ...float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldAvailableBalanceCny, vs...))
}

// AvailableBalanceCnyNotIn applies the NotIn predicate on the "available_balance_cny" field.
func AvailableBalanceCnyNotIn(vs ...float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldAvailableBalanceCny, vs...))
}

// AvailableBalanceCnyGT applies the GT predicate on the "available_balance_cny" field.
func AvailableBalanceCnyGT(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldAvailableBalanceCny, v))
}

// AvailableBalanceCnyGTE applies the GTE predicate on the "available_balance_cny" field.
func AvailableBalanceCnyGTE(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldAvailableBalanceCny, v))
}

// AvailableBalanceCnyLT applies the LT predicate on the "available_balance_cny" field.
func AvailableBalanceCnyLT(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldAvailableBalanceCny, v))
}

// AvailableBalanceCnyLTE applies the LTE predicate on the "available_balance_cny" field.
func AvailableBalanceCnyLTE(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldAvailableBalanceCny, v))
}

// FrozenBalanceCnyEQ applies the EQ predicate on the "frozen_balance_cny" field.
func FrozenBalanceCnyEQ(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldFrozenBalanceCny, v))
}

// FrozenBalanceCnyNEQ applies the NEQ predicate on the "frozen_balance_cny" field.
func FrozenBalanceCnyNEQ(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldFrozenBalanceCny, v))
}

// FrozenBalanceCnyIn applies the In predicate on the "frozen_balance_cny" field.
func FrozenBalanceCnyIn(vs ...float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldFrozenBalanceCny, vs...))
}

// FrozenBalanceCnyNotIn applies the NotIn predicate on the "frozen_balance_cny" field.
func FrozenBalanceCnyNotIn(vs ...float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldFrozenBalanceCny, vs...))
}

// FrozenBalanceCnyGT applies the GT predicate on the "frozen_balance_cny" field.
func FrozenBalanceCnyGT(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldFrozenBalanceCny, v))
}

// FrozenBalanceCnyGTE applies the GTE predicate on the "frozen_balance_cny" field.
func FrozenBalanceCnyGTE(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldFrozenBalanceCny, v))
}

// FrozenBalanceCnyLT applies the LT predicate on the "frozen_balance_cny" field.
func FrozenBalanceCnyLT(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldFrozenBalanceCny, v))
}

// FrozenBalanceCnyLTE applies the LTE predicate on the "frozen_balance_cny" field.
func FrozenBalanceCnyLTE(v float64) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldFrozenBalanceCny, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Supplier {
	return predicate.Supplier(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDocuments applies the HasEdge predicate on the "documents" edge.
func HasDocuments() predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DocumentsTable, DocumentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocumentsWith applies the HasEdge predicate on the "documents" edge with a given conditions (other predicates).
func HasDocumentsWith(preds ...predicate.SupplierDocument) predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := newDocumentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroups applies the HasEdge predicate on the "groups" edge.
func HasGroups() predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GroupsTable, GroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupsWith applies the HasEdge predicate on the "groups" edge with a given conditions (other predicates).
func HasGroupsWith(preds ...predicate.Group) predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := newGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLedgerEntries applies the HasEdge predicate on the "ledger_entries" edge.
func HasLedgerEntries() predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LedgerEntriesTable, LedgerEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerEntriesWith applies the HasEdge predicate on the "ledger_entries" edge with a given conditions (other predicates).
func HasLedgerEntriesWith(preds ...predicate.SupplierLedger) predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := newLedgerEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWithdrawals applies the HasEdge predicate on the "withdrawals" edge.
func HasWithdrawals() predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WithdrawalsTable, WithdrawalsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWithdrawalsWith applies the HasEdge predicate on the "withdrawals" edge with a given conditions (other predicates).
func HasWithdrawalsWith(preds ...predicate.SupplierWithdrawal) predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := newWithdrawalsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResourceRequests applies the HasEdge predicate on the "resource_requests" edge.
func HasResourceRequests() predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResourceRequestsTable, ResourceRequestsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResourceRequestsWith applies the HasEdge predicate on the "resource_requests" edge with a given conditions (other predicates).
func HasResourceRequestsWith(preds ...predicate.SupplierResourceRequest) predicate.Supplier {
	return predicate.Supplier(func(s *sql.Selector) {
		step := newResourceRequestsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Supplier) predicate.Supplier {
	return predicate.Supplier(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Supplier) predicate.Supplier {
	return predicate.Supplier(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Supplier) predicate.Supplier {
	return predicate.Supplier(sql.NotPredicates(p))
}
