// Code generated by ent, DO NOT EDIT.

package supplierresourcerequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldID, id))
}

// SupplierID applies equality check predicate on the "supplier_id" field. It's identical to SupplierIDEQ.
func SupplierID(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldSupplierID, v))
}

// GroupName applies equality check predicate on the "group_name" field. It's identical to GroupNameEQ.
func GroupName(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldGroupName, v))
}

// RelayName applies equality check predicate on the "relay_name" field. It's identical to RelayNameEQ.
func RelayName(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldRelayName, v))
}

// RelayURL applies equality check predicate on the "relay_url" field. It's identical to RelayURLEQ.
func RelayURL(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldRelayURL, v))
}

// APIKeyEncrypted applies equality check predicate on the "api_key_encrypted" field. It's identical to APIKeyEncryptedEQ.
func APIKeyEncrypted(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldAPIKeyEncrypted, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldModel, v))
}

// ProbeEnabled applies equality check predicate on the "probe_enabled" field. It's identical to ProbeEnabledEQ.
func ProbeEnabled(v bool) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldProbeEnabled, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldRateMultiplier, v))
}

// ReviewedBy applies equality check predicate on the "reviewed_by" field. It's identical to ReviewedByEQ.
func ReviewedBy(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewNote applies equality check predicate on the "review_note" field. It's identical to ReviewNoteEQ.
func ReviewNote(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldReviewNote, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldGroupID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldAccountID, v))
}

// MonitorID applies equality check predicate on the "monitor_id" field. It's identical to MonitorIDEQ.
func MonitorID(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldMonitorID, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldReviewedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// SupplierIDEQ applies the EQ predicate on the "supplier_id" field.
func SupplierIDEQ(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldSupplierID, v))
}

// SupplierIDNEQ applies the NEQ predicate on the "supplier_id" field.
func SupplierIDNEQ(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldSupplierID, v))
}

// SupplierIDIn applies the In predicate on the "supplier_id" field.
func SupplierIDIn(vs ...int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldSupplierID, vs...))
}

// SupplierIDNotIn applies the NotIn predicate on the "supplier_id" field.
func SupplierIDNotIn(vs ...int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldSupplierID, vs...))
}

// GroupNameEQ applies the EQ predicate on the "group_name" field.
func GroupNameEQ(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldGroupName, v))
}

// GroupNameNEQ applies the NEQ predicate on the "group_name" field.
func GroupNameNEQ(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldGroupName, v))
}

// GroupNameIn applies the In predicate on the "group_name" field.
func GroupNameIn(vs ...string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldGroupName, vs...))
}

// GroupNameNotIn applies the NotIn predicate on the "group_name" field.
func GroupNameNotIn(vs ...string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldGroupName, vs...))
}

// GroupNameGT applies the GT predicate on the "group_name" field.
func GroupNameGT(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldGroupName, v))
}

// GroupNameGTE applies the GTE predicate on the "group_name" field.
func GroupNameGTE(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldGroupName, v))
}

// GroupNameLT applies the LT predicate on the "group_name" field.
func GroupNameLT(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldGroupName, v))
}

// GroupNameLTE applies the LTE predicate on the "group_name" field.
func GroupNameLTE(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldGroupName, v))
}

// GroupNameContains applies the Contains predicate on the "group_name" field.
func GroupNameContains(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldContains(FieldGroupName, v))
}

// GroupNameHasPrefix applies the HasPrefix predicate on the "group_name" field.
func GroupNameHasPrefix(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldHasPrefix(FieldGroupName, v))
}

// GroupNameHasSuffix applies the HasSuffix predicate on the "group_name" field.
func GroupNameHasSuffix(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldHasSuffix(FieldGroupName, v))
}

// GroupNameEqualFold applies the EqualFold predicate on the "group_name" field.
func GroupNameEqualFold(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEqualFold(FieldGroupName, v))
}

// GroupNameContainsFold applies the ContainsFold predicate on the "group_name" field.
func GroupNameContainsFold(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldContainsFold(FieldGroupName, v))
}

// RelayNameEQ applies the EQ predicate on the "relay_name" field.
func RelayNameEQ(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldRelayName, v))
}

// RelayNameNEQ applies the NEQ predicate on the "relay_name" field.
func RelayNameNEQ(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldRelayName, v))
}

// RelayNameIn applies the In predicate on the "relay_name" field.
func RelayNameIn(vs ...string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldRelayName, vs...))
}

// RelayNameNotIn applies the NotIn predicate on the "relay_name" field.
func RelayNameNotIn(vs ...string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldRelayName, vs...))
}

// RelayNameGT applies the GT predicate on the "relay_name" field.
func RelayNameGT(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldRelayName, v))
}

// RelayNameGTE applies the GTE predicate on the "relay_name" field.
func RelayNameGTE(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldRelayName, v))
}

// RelayNameLT applies the LT predicate on the "relay_name" field.
func RelayNameLT(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldRelayName, v))
}

// RelayNameLTE applies the LTE predicate on the "relay_name" field.
func RelayNameLTE(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldRelayName, v))
}

// RelayNameContains applies the Contains predicate on the "relay_name" field.
func RelayNameContains(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldContains(FieldRelayName, v))
}

// RelayNameHasPrefix applies the HasPrefix predicate on the "relay_name" field.
func RelayNameHasPrefix(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldHasPrefix(FieldRelayName, v))
}

// RelayNameHasSuffix applies the HasSuffix predicate on the "relay_name" field.
func RelayNameHasSuffix(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldHasSuffix(FieldRelayName, v))
}

// RelayNameEqualFold applies the EqualFold predicate on the "relay_name" field.
func RelayNameEqualFold(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEqualFold(FieldRelayName, v))
}

// RelayNameContainsFold applies the ContainsFold predicate on the "relay_name" field.
func RelayNameContainsFold(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldContainsFold(FieldRelayName, v))
}

// RelayURLEQ applies the EQ predicate on the "relay_url" field.
func RelayURLEQ(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldRelayURL, v))
}

// RelayURLNEQ applies the NEQ predicate on the "relay_url" field.
func RelayURLNEQ(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldRelayURL, v))
}

// RelayURLIn applies the In predicate on the "relay_url" field.
func RelayURLIn(vs ...string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldRelayURL, vs...))
}

// RelayURLNotIn applies the NotIn predicate on the "relay_url" field.
func RelayURLNotIn(vs ...string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldRelayURL, vs...))
}

// RelayURLGT applies the GT predicate on the "relay_url" field.
func RelayURLGT(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldRelayURL, v))
}

// RelayURLGTE applies the GTE predicate on the "relay_url" field.
func RelayURLGTE(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldRelayURL, v))
}

// RelayURLLT applies the LT predicate on the "relay_url" field.
func RelayURLLT(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldRelayURL, v))
}

// RelayURLLTE applies the LTE predicate on the "relay_url" field.
func RelayURLLTE(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldRelayURL, v))
}

// RelayURLContains applies the Contains predicate on the "relay_url" field.
func RelayURLContains(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldContains(FieldRelayURL, v))
}

// RelayURLHasPrefix applies the HasPrefix predicate on the "relay_url" field.
func RelayURLHasPrefix(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldHasPrefix(FieldRelayURL, v))
}

// RelayURLHasSuffix applies the HasSuffix predicate on the "relay_url" field.
func RelayURLHasSuffix(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldHasSuffix(FieldRelayURL, v))
}

// RelayURLEqualFold applies the EqualFold predicate on the "relay_url" field.
func RelayURLEqualFold(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEqualFold(FieldRelayURL, v))
}

// RelayURLContainsFold applies the ContainsFold predicate on the "relay_url" field.
func RelayURLContainsFold(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldContainsFold(FieldRelayURL, v))
}

// APIKeyEncryptedEQ applies the EQ predicate on the "api_key_encrypted" field.
func APIKeyEncryptedEQ(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedNEQ applies the NEQ predicate on the "api_key_encrypted" field.
func APIKeyEncryptedNEQ(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedIn applies the In predicate on the "api_key_encrypted" field.
func APIKeyEncryptedIn(vs ...string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldAPIKeyEncrypted, vs...))
}

// APIKeyEncryptedNotIn applies the NotIn predicate on the "api_key_encrypted" field.
func APIKeyEncryptedNotIn(vs ...string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldAPIKeyEncrypted, vs...))
}

// APIKeyEncryptedGT applies the GT predicate on the "api_key_encrypted" field.
func APIKeyEncryptedGT(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedGTE applies the GTE predicate on the "api_key_encrypted" field.
func APIKeyEncryptedGTE(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedLT applies the LT predicate on the "api_key_encrypted" field.
func APIKeyEncryptedLT(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedLTE applies the LTE predicate on the "api_key_encrypted" field.
func APIKeyEncryptedLTE(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedContains applies the Contains predicate on the "api_key_encrypted" field.
func APIKeyEncryptedContains(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldContains(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedHasPrefix applies the HasPrefix predicate on the "api_key_encrypted" field.
func APIKeyEncryptedHasPrefix(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldHasPrefix(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedHasSuffix applies the HasSuffix predicate on the "api_key_encrypted" field.
func APIKeyEncryptedHasSuffix(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldHasSuffix(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedEqualFold applies the EqualFold predicate on the "api_key_encrypted" field.
func APIKeyEncryptedEqualFold(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEqualFold(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedContainsFold applies the ContainsFold predicate on the "api_key_encrypted" field.
func APIKeyEncryptedContainsFold(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldContainsFold(FieldAPIKeyEncrypted, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldContainsFold(FieldModel, v))
}

// ProbeEnabledEQ applies the EQ predicate on the "probe_enabled" field.
func ProbeEnabledEQ(v bool) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldProbeEnabled, v))
}

// ProbeEnabledNEQ applies the NEQ predicate on the "probe_enabled" field.
func ProbeEnabledNEQ(v bool) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldProbeEnabled, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldRateMultiplier, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// ReviewedByEQ applies the EQ predicate on the "reviewed_by" field.
func ReviewedByEQ(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedByNEQ applies the NEQ predicate on the "reviewed_by" field.
func ReviewedByNEQ(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldReviewedBy, v))
}

// ReviewedByIn applies the In predicate on the "reviewed_by" field.
func ReviewedByIn(vs ...int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldReviewedBy, vs...))
}

// ReviewedByNotIn applies the NotIn predicate on the "reviewed_by" field.
func ReviewedByNotIn(vs ...int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldReviewedBy, vs...))
}

// ReviewedByGT applies the GT predicate on the "reviewed_by" field.
func ReviewedByGT(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldReviewedBy, v))
}

// ReviewedByGTE applies the GTE predicate on the "reviewed_by" field.
func ReviewedByGTE(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldReviewedBy, v))
}

// ReviewedByLT applies the LT predicate on the "reviewed_by" field.
func ReviewedByLT(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldReviewedBy, v))
}

// ReviewedByLTE applies the LTE predicate on the "reviewed_by" field.
func ReviewedByLTE(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldReviewedBy, v))
}

// ReviewedByIsNil applies the IsNil predicate on the "reviewed_by" field.
func ReviewedByIsNil() predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIsNull(FieldReviewedBy))
}

// ReviewedByNotNil applies the NotNil predicate on the "reviewed_by" field.
func ReviewedByNotNil() predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotNull(FieldReviewedBy))
}

// ReviewNoteEQ applies the EQ predicate on the "review_note" field.
func ReviewNoteEQ(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldReviewNote, v))
}

// ReviewNoteNEQ applies the NEQ predicate on the "review_note" field.
func ReviewNoteNEQ(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldReviewNote, v))
}

// ReviewNoteIn applies the In predicate on the "review_note" field.
func ReviewNoteIn(vs ...string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldReviewNote, vs...))
}

// ReviewNoteNotIn applies the NotIn predicate on the "review_note" field.
func ReviewNoteNotIn(vs ...string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldReviewNote, vs...))
}

// ReviewNoteGT applies the GT predicate on the "review_note" field.
func ReviewNoteGT(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldReviewNote, v))
}

// ReviewNoteGTE applies the GTE predicate on the "review_note" field.
func ReviewNoteGTE(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldReviewNote, v))
}

// ReviewNoteLT applies the LT predicate on the "review_note" field.
func ReviewNoteLT(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldReviewNote, v))
}

// ReviewNoteLTE applies the LTE predicate on the "review_note" field.
func ReviewNoteLTE(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldReviewNote, v))
}

// ReviewNoteContains applies the Contains predicate on the "review_note" field.
func ReviewNoteContains(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldContains(FieldReviewNote, v))
}

// ReviewNoteHasPrefix applies the HasPrefix predicate on the "review_note" field.
func ReviewNoteHasPrefix(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldHasPrefix(FieldReviewNote, v))
}

// ReviewNoteHasSuffix applies the HasSuffix predicate on the "review_note" field.
func ReviewNoteHasSuffix(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldHasSuffix(FieldReviewNote, v))
}

// ReviewNoteEqualFold applies the EqualFold predicate on the "review_note" field.
func ReviewNoteEqualFold(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEqualFold(FieldReviewNote, v))
}

// ReviewNoteContainsFold applies the ContainsFold predicate on the "review_note" field.
func ReviewNoteContainsFold(v string) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldContainsFold(FieldReviewNote, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotNull(FieldGroupID))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotNull(FieldAccountID))
}

// MonitorIDEQ applies the EQ predicate on the "monitor_id" field.
func MonitorIDEQ(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldMonitorID, v))
}

// MonitorIDNEQ applies the NEQ predicate on the "monitor_id" field.
func MonitorIDNEQ(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldMonitorID, v))
}

// MonitorIDIn applies the In predicate on the "monitor_id" field.
func MonitorIDIn(vs ...int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldMonitorID, vs...))
}

// MonitorIDNotIn applies the NotIn predicate on the "monitor_id" field.
func MonitorIDNotIn(vs ...int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldMonitorID, vs...))
}

// MonitorIDGT applies the GT predicate on the "monitor_id" field.
func MonitorIDGT(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldMonitorID, v))
}

// MonitorIDGTE applies the GTE predicate on the "monitor_id" field.
func MonitorIDGTE(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldMonitorID, v))
}

// MonitorIDLT applies the LT predicate on the "monitor_id" field.
func MonitorIDLT(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldMonitorID, v))
}

// MonitorIDLTE applies the LTE predicate on the "monitor_id" field.
func MonitorIDLTE(v int64) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldMonitorID, v))
}

// MonitorIDIsNil applies the IsNil predicate on the "monitor_id" field.
func MonitorIDIsNil() predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIsNull(FieldMonitorID))
}

// MonitorIDNotNil applies the NotNil predicate on the "monitor_id" field.
func MonitorIDNotNil() predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotNull(FieldMonitorID))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotNull(FieldReviewedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSupplier applies the HasEdge predicate on the "supplier" edge.
func HasSupplier() predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SupplierTable, SupplierColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSupplierWith applies the HasEdge predicate on the "supplier" edge with a given conditions (other predicates).
func HasSupplierWith(preds ...predicate.Supplier) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(func(s *sql.Selector) {
		step := newSupplierStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupplierResourceRequest) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupplierResourceRequest) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupplierResourceRequest) predicate.SupplierResourceRequest {
	return predicate.SupplierResourceRequest(sql.NotPredicates(p))
}
