<template><AppLayout><div class="mx-auto max-w-7xl space-y-7 p-4 md:p-7"><header><h1 class="text-xl font-semibold">供应商工作台</h1><p class="mt-1 text-sm text-gray-500">管理入驻状态、中转资源申请与结算账单。</p></header>
<div v-if="loading" class="rounded-lg border bg-white py-20 text-center text-gray-400">加载中...</div>
<form v-else-if="!profile||profile.status==='rejected'" class="max-w-2xl space-y-5 rounded-lg border bg-white p-6 shadow-sm" @submit.prevent="submitSupplier"><div><h2 class="font-semibold">申请供应商入驻</h2><p class="mt-1 text-sm text-gray-500">该信息仅用于入驻审核，通过后才能提交中转资源。</p></div><label class="block text-sm font-medium">供应商名称<input v-model="supplierForm.name" required placeholder="公司、团队或个人品牌名称" class="input mt-2 w-full" /></label><label class="block text-sm font-medium">官方网站或中转站地址<input v-model="supplierForm.relay_url" type="url" required placeholder="https://example.com" class="input mt-2 w-full" /></label><label class="block text-sm font-medium">申请说明<textarea v-model="supplierForm.application_note" rows="4" placeholder="请说明资源来源、服务能力和联系方式" class="input mt-2 w-full" /></label><button class="rounded-lg bg-teal-600 px-5 py-2.5 font-medium text-white">提交入驻审核</button></form>
<div v-else-if="profile.status!=='approved'" class="rounded-lg border bg-white py-16 text-center shadow-sm"><div class="font-medium">{{profile.status==='pending'?'入驻申请审核中':'供应商已冻结'}}</div><p class="mt-2 text-sm text-gray-500">{{profile.review_note||profile.freeze_reason||'请等待管理员处理'}}</p></div>
<template v-else><section class="rounded-lg border bg-white p-5 shadow-sm dark:bg-gray-900"><h2 class="font-semibold">提交新的中转资源</h2><p class="mt-1 text-sm text-gray-500">管理员批准后，系统会自动创建公开分组、调度账号并开启 GPT-5.5 监听。</p><form class="mt-5 grid gap-5 md:grid-cols-2" @submit.prevent="submitResource"><Field label="大厅分组名称" hint="用户在供应商大厅看到的名称，例如“高速 GPT 专线”。"><input v-model="resourceForm.group_name" required placeholder="高速 GPT 专线" class="input mt-2 w-full" /></Field><Field label="中转站名称" hint="用于管理员识别资源来源。"><input v-model="resourceForm.relay_name" required placeholder="香港中转一号" class="input mt-2 w-full" /></Field><Field label="API 基础地址" hint="兼容 OpenAI 的 HTTPS 根地址，不包含模型路径。"><input v-model="resourceForm.relay_url" type="url" required placeholder="https://api.example.com" class="input mt-2 w-full" /></Field><Field label="中转站 API Key" hint="加密保存，不会展示给其他用户。"><input v-model="resourceForm.api_key" type="password" required autocomplete="new-password" placeholder="sk-..." class="input mt-2 w-full" /></Field><Field label="默认监听模型" hint="审核通过后自动开启可用性检测。"><input v-model="resourceForm.model" readonly class="input mt-2 w-full bg-gray-50" /></Field><div class="flex items-end"><button class="rounded-lg bg-teal-600 px-5 py-2.5 font-medium text-white hover:bg-teal-700">提交资源审核</button></div></form></section>
<section><h2 class="mb-3 font-semibold">资源申请记录</h2><div class="overflow-x-auto rounded-lg border bg-white shadow-sm"><table class="w-full min-w-[700px] text-sm"><thead class="bg-gray-50 text-left text-xs text-gray-500"><tr><th class="p-3">分组</th><th>中转站</th><th>模型</th><th>状态</th><th>审核备注</th></tr></thead><tbody><tr v-for="r in requests" :key="r.id" class="border-t"><td class="p-3 font-medium">{{r.group_name}}</td><td>{{r.relay_name}}</td><td>{{r.model}}</td><td><StatusBadge :status="r.status" /></td><td>{{r.review_note||'--'}}</td></tr><tr v-if="!requests.length"><td colspan="5" class="p-10 text-center text-gray-400">暂无资源申请</td></tr></tbody></table></div></section>
<section><div class="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold">收益账单</h2><p class="mt-1 text-xs text-gray-500">账单已隐藏用户、API 密钥和请求来源信息。</p></div><div class="flex gap-1"><button v-for="f in billFilters" :key="f.value" class="rounded-lg px-3 py-1.5 text-xs" :class="billStatus===f.value?'bg-teal-600 text-white':'bg-gray-100 text-gray-600'" @click="setBillStatus(f.value)">{{f.label}}</button></div></div><div class="overflow-x-auto rounded-lg border bg-white shadow-sm"><table class="w-full min-w-[920px] text-sm"><thead class="bg-gray-50 text-left text-xs text-gray-500"><tr><th class="p-3">调用时间</th><th>分组/模型</th><th>Token</th><th>倍率</th><th>收益</th><th>状态</th><th>可提现时间</th></tr></thead><tbody><tr v-for="b in bills" :key="b.id" class="border-t"><td class="p-3">{{date(b.created_at)}}</td><td><div class="font-medium">{{b.group_name||'#'+b.group_id}}</div><div class="text-xs text-gray-500">{{b.model||'--'}}</div></td><td>输入 {{b.input_tokens}} / 输出 {{b.output_tokens}}<div class="text-xs text-gray-500">缓存 {{b.cache_read_tokens}}</div></td><td>{{number(b.base_rate)}} → {{number(b.effective_rate)}}</td><td class="font-medium text-emerald-700">¥{{money(b.amount_cny)}}</td><td>{{b.status==='pending'?'待结算':b.status==='available'?'可提现':'冻结'}}</td><td>{{b.available_at?date(b.available_at):'--'}}</td></tr><tr v-if="!bills.length"><td colspan="7" class="p-12 text-center text-gray-400">暂无账单记录</td></tr></tbody></table></div></section></template>
</div></AppLayout></template>
<script setup lang="ts">
import { defineComponent, h, onMounted, reactive, ref } from 'vue'
import AppLayout from '@/components/layout/AppLayout.vue'
import { supplierAPI, type Supplier, type SupplierBill, type SupplierResourceRequest } from '@/api/suppliers'
const Field=defineComponent({props:{label:String,hint:String},setup(p,{slots}){return()=>h('label',{class:'text-sm font-medium'},[p.label,h('span',{class:'mt-1 block text-xs font-normal text-gray-500'},p.hint),slots.default?.()])}})
const StatusBadge=defineComponent({props:{status:String},setup(p){return()=>h('span',{class:'inline-flex rounded-full px-2.5 py-1 text-xs font-medium '+(p.status==='approved'?'bg-emerald-50 text-emerald-700':p.status==='rejected'?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700')},p.status==='approved'?'已通过':p.status==='rejected'?'已驳回':'审核中')}})
const loading=ref(true),profile=ref<Supplier|null>(null),requests=ref<SupplierResourceRequest[]>([]),bills=ref<SupplierBill[]>([]),billStatus=ref('')
const billFilters=[{label:'全部',value:''},{label:'待结算',value:'pending'},{label:'可提现',value:'available'}]
const supplierForm=reactive({name:'',relay_url:'',application_note:''}),resourceForm=reactive({group_name:'',relay_name:'',relay_url:'',api_key:'',model:'gpt-5.5'})
async function load(){try{const p=await supplierAPI.me();profile.value=p;if(p.status==='approved'){const[r,b]=await Promise.all([supplierAPI.resourceRequests(),supplierAPI.bills(billStatus.value)]);requests.value=r.items||[];bills.value=b.items||[]}}catch{profile.value=null}finally{loading.value=false}}
async function submitSupplier(){profile.value=await supplierAPI.apply(supplierForm)} async function submitResource(){await supplierAPI.createResourceRequest(resourceForm);Object.assign(resourceForm,{group_name:'',relay_name:'',relay_url:'',api_key:'',model:'gpt-5.5'});await load()} async function setBillStatus(v:string){billStatus.value=v;bills.value=(await supplierAPI.bills(v)).items||[]}
const date=(v:string)=>new Date(v).toLocaleString(),number=(v:unknown)=>Number(v||0).toFixed(4),money=(v:unknown)=>Number(v||0).toFixed(4)
onMounted(load)
</script>
